Добавил линтинг и CI-проверки
feature-sliced/documentation pull request #137
Opened 2021-07-04 20:24 UTC by martis-git

## CHANGELOG

## Чеклист

- [ ] `docs` Использованы github-дискуссии

- [ ] `by-issue` Проведена проверка по требованиям задачи

- [ ] Проведено self-review изменений

2021-07-04 20:29 UTC, martis-git commented
Тест прошел успешно 😎 

![image](https://user-images.githubusercontent.com/42924400/124398666-98126880-dd1f-11eb-92b1-4c8f27a1b0cf.png)

2021-07-04 23:26 UTC, martis-git commented on .github/workflows/testing.yml
> +        working-directory: ./website
Показалось, что лучше отдельно параллелить процессы, т.к. они о разном всеж

Но если кто спец в github-actions, мб можно тут более грамотно распараллелить (например, после установки зависимостей)

2021-07-04 23:27 UTC, martis-git reviewed
self-reviewed

2021-07-04 23:27 UTC, martis-git commented on website/src/pages/index.jsx
> +import Layout from "@theme/Layout";
Ну тут никак не хотел резолвить импорт((

![image](https://user-images.githubusercontent.com/42924400/124402368-8093a980-dd38-11eb-8c40-1a2fecd13e8d.png)

2021-07-04 23:41 UTC, martis-git reviewed
self-reviewed

2021-07-04 23:43 UTC, martis-git reviewed
self-reviewed

2021-07-05 04:26 UTC, sergeysova requested changes

2021-07-05 04:26 UTC, sergeysova commented on .github/pull_request_template.md
> +- [ ] Если PR связан с задачей, то должна быть проверка, что **все требования по задаче выполнены**
```suggestion
- [ ] Если PR связан с задачей, то необходимо проверить, что **все требования по задаче выполнены**
```

2021-07-05 07:04 UTC, martis-git reviewed
self-reviewed

2021-07-05 15:12 UTC, AlexandrHoroshih submitted a review, later dismissed

2021-07-05 19:11 UTC, AlexandrHoroshih submitted a review, later dismissed

2021-07-05 19:19 UTC, martis-git commented
@AlexandrHoroshih давай по новой))

2021-07-05 19:19 UTC, martis-git commented
хотфиксы конфликты тут порождают..

2021-07-06 06:57 UTC, martis-git commented
@feature-sliced/core гляньте пож

2021-07-06 07:13 UTC, AlexandrHoroshih approved these changes

2021-07-07 10:28 UTC, karina-jovian approved these changes

2021-07-07 11:09 UTC, merged