Добавил больше информации по слоям (+ виджеты) и добавил визуализации
feature-sliced/documentation pull request #140
Opened 2021-07-10 19:57 UTC by martis-git

## CHANGELOG

- Добавил(а) ...
- Поправил(а) ...

## Чеклист

- [ ] Если при работе с документацией потребовалось использовать **github-дискуссии, то стоит их прикрепить как see-also источники**
- [ ] Если PR связан с задачей, то необходимо проверить, что **все требования по задаче выполнены**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно провести self-review своих изменений**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дождаться CI-проверок**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дать краткое описание изменений**

2021-07-10 20:42 UTC, martis-git reviewed
self-reviewed

2021-07-10 20:42 UTC, martis-git commented on docs/reference/layers/shared.md
> +
Можно не ревьювить - взял из бывшего `/docs/reference/layers`, добавил только хедеров в структуру

2021-07-10 20:42 UTC, martis-git commented on docs/reference/layers/processes.md
> +---
Тут тож добавил только хедеры, лейбл (OPTIONAL) и примеры

2021-07-10 20:42 UTC, martis-git commented on docs/reference/layers/pages.md
> +---
Здесь тоже как было раньше и добавил только хедеров

2021-07-10 20:42 UTC, martis-git commented on docs/reference/layers/overview.md
> +| shared    |                                 -                                 | `entities`, `features`, `widgets`, `pages`, `processes`, `app` |
Здесь в layers тоже упомянул widgets, но по всей доке не проходился, т.к. это как никак "экспериментальный слой"

И будет нужен скорее эдвенсед разрабам

2021-07-10 20:42 UTC, martis-git commented on docs/reference/layers/overview.md
> +:::
Решил добавить все ж

2021-07-11 11:18 UTC, martis-git commented
@feature-sliced/core гляньте пож

2021-07-12 07:42 UTC, AlexandrHoroshih requested changes

2021-07-12 07:42 UTC, AlexandrHoroshih commented on docs/reference/layers/entities.md
> +    > *Например: `user`, `order`, `post`, `journal`, `i18n`, `navigation`, ...*
i18n же у нас уже в shared/config 🤔

2021-07-12 07:42 UTC, AlexandrHoroshih commented on docs/reference/layers/widgets.md
> +:::danger EXPERIMENTAL
Это красненькая карточка будет же? 
(я бы желтенькую поставил)

2021-07-12 07:42 UTC, AlexandrHoroshih commented on docs/reference/layers/widgets.md
> +> Пока что для этого слоя не выработано лучших практик (помимо тех, что действуют для других слоев), поэтому используйте его только при необходимости и на свой страх и риск
Чет кажется, что пугать "на свой страх и риск" скорее лишнее

2021-07-12 08:54 UTC, martis-git commented on docs/reference/layers/entities.md
> +    > *Например: `user`, `order`, `post`, `journal`, `i18n`, `navigation`, ...*
А-ой, похоже старое))

2021-07-12 08:54 UTC, martis-git commented on docs/reference/layers/widgets.md
> +> Пока что для этого слоя не выработано лучших практик (помимо тех, что действуют для других слоев), поэтому используйте его только при необходимости и на свой страх и риск
Оке, заменим)

2021-07-12 08:55 UTC, martis-git commented on docs/reference/layers/widgets.md
> +> Пока что для этого слоя не выработано лучших практик (помимо тех, что действуют для других слоев), поэтому используйте его только при необходимости и на свой страх и риск
Повторяется история с WIP-баннером 😄

2021-07-12 09:03 UTC, martis-git commented on docs/reference/layers/widgets.md
> +:::danger EXPERIMENTAL
Эххх лан, будем менее агрессивно-предупреждающими))

Особенно учитывая, что ты уже начал преисполняться виджетами 😏

![image](https://user-images.githubusercontent.com/42924400/125260529-14e9a780-e309-11eb-8b54-6febbbee3481.png)

![image](https://user-images.githubusercontent.com/42924400/125260508-0d2a0300-e309-11eb-8108-41a2647df872.png)

2021-07-12 09:09 UTC, AlexandrHoroshih approved these changes

2021-07-12 14:08 UTC, azin-ilya approved these changes
test-approve

2021-07-12 15:56 UTC, merged