docs: align intro and readme translations
feature-sliced/documentation pull request #330
Opened 2021-11-01 19:01 UTC by michalenr

## CHANGELOG

- Поправил перевод в Intro Readme
- Сделал перевод доки одинаковым с readme

## Чеклист

- [ ] Если при работе с документацией потребовалось использовать **github-дискуссии, то стоит их прикрепить как see-also источники**
- [ ] Если PR связан с задачей, то необходимо проверить, что **все требования по задаче выполнены**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно ознакомиться с [CONTIBUTING-гайдлайнами](https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md)**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно провести self-review своих изменений**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дождаться CI-проверок**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дать краткое описание изменений**

2021-11-02 05:27 UTC, azinit requested changes
Кое что поправил бы, а в целом - пушка бомба 🚀

2021-11-02 05:27 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.md
> +- Based on [**experienced-checked**][refs-motivation-why] design practices and concepts
Очепятка)

Но мб тогда и здесь и в ридми заменить на `experience-tested`?

> По аналогии с `battle-tested`, так более правильно кмк

```suggestion
- Based on [**experience-tested**][refs-motivation-why] design practices and concepts
```

2021-11-02 05:27 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.md
> +An architectural design methodology for *frontend projects*. It aims to [**divide an application according to business logic and scopes of responsibility.**][refs-splitting]
Думаю, можно взять прям полностью из ридмихи тогда да, прям начиная с "FeatureSliced is..."

2021-11-02 13:05 UTC, michalenr commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.md
> +- Based on [**experienced-checked**][refs-motivation-why] design practices and concepts
Вообще, мне больше нравится time-tested. Experience-tested/checked звучит как калька с русского. Что скажешь?

2021-11-02 14:43 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.md
> +- Based on [**experienced-checked**][refs-motivation-why] design practices and concepts
Щас призову кого надо))

2021-11-02 14:45 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.md
> +- Based on [**experienced-checked**][refs-motivation-why] design practices and concepts
> Но чисто имхо - да, можно и "time-tested", но @KaraJovian получше подскажет

2021-11-03 18:11 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.md
> +- Based on [**experienced-checked**][refs-motivation-why] design practices and concepts
@feature-sliced/core ping

2021-11-04 12:23 UTC, azinit commented
@michalenr Рекомендую поскорей добить PR, т.к. там крупная реструктуризация на подходе)

#339

2021-11-04 12:24 UTC, azinit commented
Можем остановиться на нашем промежуточном варианте пока с "time-tested"

2021-11-04 13:12 UTC, michalenr commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.md
> +An architectural design methodology for *frontend projects*. It aims to [**divide an application according to business logic and scopes of responsibility.**][refs-splitting]
@azinit А FetureSliced может лучше писать через дефис? Feature-sliced

2021-11-04 14:03 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.md
> +An architectural design methodology for *frontend projects*. It aims to [**divide an application according to business logic and scopes of responsibility.**][refs-splitting]
@michalenr

2021-11-04 14:08 UTC, azinit commented
@feature-sliced/core гляньте пож

2021-11-04 14:49 UTC, michalenr commented
Закинул фиксы по комментам

2021-11-04 14:54 UTC, azinit submitted a review, later dismissed
Пушка бомба, заходи еще 😎

2021-11-04 14:54 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.md
> +- Based on [**time-tesed**][refs-motivation-why] design practices and concepts
```suggestion
- Based on [**time-tested**][refs-motivation-why] design practices and concepts
```

2021-11-04 14:55 UTC, merged