DISCOVERY-332: Restructure of docs - 🔎 Intro
feature-sliced/documentation pull request #339
Opened 2021-11-04 11:52 UTC by azinit

## CHANGELOG

- Добавил(а) ...
- Поправил(а) ...

## Чеклист

- [ ] Если при работе с документацией потребовалось использовать **github-дискуссии, то стоит их прикрепить как see-also источники**
- [ ] Если PR связан с задачей, то необходимо проверить, что **все требования по задаче выполнены**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно ознакомиться с [CONTIBUTING-гайдлайнами](https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md)**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно провести self-review своих изменений**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дождаться CI-проверок**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дать краткое описание изменений**

2021-11-04 12:18 UTC, azinit reviewed
self-reviewed

2021-11-04 12:18 UTC, azinit commented on website/docusaurus.config.js
> +        },
Позже это будет отдельный раздел для помощи, как у других док

<img width="1271" alt="132316858-0f788dc5-0a85-4ea9-9ab5-416c334ec918" src="https://user-images.githubusercontent.com/42924400/140310339-cb6d1ed5-12b5-443f-a234-687225ea5cc6.png">

2021-11-04 12:18 UTC, azinit commented on website/docusaurus.config.js
> +                .concat(LEGACY_ROUTES.map(({ from, to }) => ({ from, to }))),
Приходится явно избавляться от лишних полей, иначе плагин редиректов "ругается"

2021-11-04 12:18 UTC, azinit commented on website/docusaurus.config.js
> +    legacyRoutes: LEGACY_ROUTES,
Прокидываем кастомными филдами для доступа в коде

> Relay также делал, да и в доке описана такая возможность
> https://docusaurus.io/docs/api/docusaurus-config#customfields

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/about/index.mdx
> +<span class="badge badge--violet margin-bottom--md">BACKGROUND-ORIENTED</span>
Для комьюнити, внезапно, будет отдельная секция, поэтому актуализируем)

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/get-started/overview.md
> -sidebar_position: 1
По сути перенес из get-started, т.к. там этой статье незачем быть (Overview как никак)

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.md
> -sidebar_position: 1
А это гит не смог в переименование (`intro.md` => `intro.mdx`)

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +:::
То, что было уже в интро

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +> More details: ["Concepts, Abstractions, Structure"][refs-basics]
Наш любимый торт с лендинга

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +*But for the frontend [it is highly difficult to find][refs-motivation] well-established and specific approaches*
Секция из README

> Да, у нас README по факту дублируется в доке, но это осознанная мера

https://github.com/feature-sliced/documentation/#motivation

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +Thanks to this, *a balance is maintained between compliance with the `DRY` principle and the ability to customize the module logic without overhead overrides*
А тут то, что было в [`/get-started/overview`](https://feature-sliced.design/en/docs/get-started/overview/)

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +/>
А это навигация уже не курильщика, а нормального человека

> По сравнению с тем, что было
> ![image](https://user-images.githubusercontent.com/42924400/140310958-3eac1dec-cdc9-4769-b281-7b78ceb55883.png)

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +/>
И вот на самом деле - я просидел больше всего именно над ней)))

Т.к. хотелось за раз отобразить кучу всего разного в помощь человеку, но и чтоб не нагрузить излишне

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +/>
<details>
<summary>Как минимум были такие концепты</summary>

![image](https://user-images.githubusercontent.com/42924400/140311102-7cc2e56c-afcc-4f88-ade9-37d7a770c358.png)

![image](https://user-images.githubusercontent.com/42924400/140311172-ce34a0c5-0d48-4870-908a-88b2f9ee632b.png)

![image](https://user-images.githubusercontent.com/42924400/140311115-42fc6b04-e110-4cd0-9d5d-3c2d890dcfb3.png)

![image](https://user-images.githubusercontent.com/42924400/140311141-740bf9df-df03-4d7c-939d-cc8e870bbd98.png)

</details>

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +/>
И вот на самом деле хз где отобразить `"XXX-oriented"` лейблы, чтобы было не в нагрузку читателю

При этом базовые статьи тоже отображать имеет смысл, т.к. раньше это компенсировалось разделом "See also" в Overview

![image](https://user-images.githubusercontent.com/42924400/140311339-b8c19bbf-4a31-49bf-97a2-1c35287b103a.png)

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +/>
Хз в общем - если есть идеи как сделать лучше можно, буду только рад услышать предложения

2021-11-04 12:18 UTC, azinit commented on website/i18n/ru/code.json
> +    "description": "NavPage section=legacy details"
Фух, ну теперь тож самое только на русском)

2021-11-04 12:18 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Методология для проектирования *frontend проектов*, нацеленная [**на разделение приложения согласно бизнес-логике и областям ответственности.**][refs-splitting]
По сути все тож самое, тольк на русском (даж формулировки достал из гит истории самые актуальные, а не тупо переводом)

2021-11-04 12:18 UTC, azinit commented on website/i18n/ru/docusaurus-theme-classic/navbar.json
> +    "description": "Navbar item with label Help"
Локализация для навбара собсна

2021-11-04 12:18 UTC, azinit commented on website/src/app/index.css
> +
А тут "весело" т.к. логика инвертирования схемы теперь не только на главной странице нужна

Поэтому временно захардкодил глобально, ~~пока не изобретем feature-sliced нейросеть для этого~~

Ну собсна стили с другой страницы со схемой тоже унифицировал, чтобы не размазывалось

![image](https://user-images.githubusercontent.com/42924400/140311575-a6364ec1-bd33-46fc-a48a-478b67a4d4e9.png)

2021-11-04 12:18 UTC, azinit commented on website/src/features/feedback/doc/styles.module.css
> +    line-height: var(--height);
**Почему так?**

Потому что нужен нормальный UX, при "отправке формы" - чтобы лейаут не съезжал

И самый простой и надежный метод по итогу оказался - статичное задание высоты (но здесь нюансы с адаптивностью и вылезли)

![image](https://user-images.githubusercontent.com/42924400/140311858-8cc1a389-04a3-4ca7-867d-9d5621c08c5b.png)

![image](https://user-images.githubusercontent.com/42924400/140311867-6abd508a-7062-4514-8b79-36823a46d77a.png)

2021-11-04 12:18 UTC, azinit commented on website/src/features/feedback/doc/styles.module.css
> +    }
Ну и здесь собсна "адаптивим"

2021-11-04 12:18 UTC, azinit commented on website/src/pages/_home/index.jsx
> +                        alt="feature-sliced-scheme,themed--scheme"
"унифицируем логику"

2021-11-04 12:18 UTC, azinit commented on website/src/pages/_home/styles.module.css
> -html[data-theme='dark'] .schemeImg {
"унифицируем логику" [2]

2021-11-04 12:18 UTC, azinit commented on website/src/pages/nav/index.jsx
> +const NavPage = () => {
Собсна, страница навигации со старыми роутами

_(Скорее всего что-нибудь еще со временем сюда добавим для облегчения)_

2021-11-04 12:18 UTC, azinit commented on website/src/shared/ui/row/index.jsx
> +                {tags && <div className={styles.detailsTags}>{tags.join(" • ")}</div>}
Апгрейдим наш компонент карточки, чтобы мог отображать эмодзи-иконки и теги

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +# 🔎 Intro
Позже кста надо бы добавить какое-нить версионирование страниц, чтобы когда люди оставляли фидбек было понятно - по какой версии (чтоб динамику тож отследить)

2021-11-04 12:18 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +# 🔎 Intro
Но out-of-scope пока (хотя себе записал)

2021-11-04 12:21 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +/>
Думал даж над таким вариантом, но тож громоздко выглядело

(да и карточка у нас уже кликабельная, ссылок туда добавлять - прям смерть)

![image](https://user-images.githubusercontent.com/42924400/140312519-ab233d9b-007f-418a-b0b7-05717d69f6d5.png)

2021-11-04 12:22 UTC, azinit commented
Ну и кста да, пожалуй так много изменений и проработки этой страницы - потому что это второе лицо документации сразу после лендинга)

2021-11-04 12:27 UTC, azinit commented on website/i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +/>
И что-то вроде такого риббона хотел, и даже пробовал -  но уже было слишком громоздко по UX

(да и времени прилично потратилось)

![image](https://user-images.githubusercontent.com/42924400/140313231-57506f5d-9c38-4384-8f64-5afa75e11af1.png)

2021-11-04 13:47 UTC, AlexandrHoroshih approved these changes
🤘

2021-11-05 13:17 UTC, AlexandrHoroshih approved these changes

2021-11-06 09:00 UTC, azinit commented
@feature-sliced/core @feature-sliced/contributors Гляньте пож 👀

2021-11-06 17:32 UTC, GhostMayor commented on website/src/app/index.css
> +
ну вообще теперь приложение знает о некоторой themed--scheme

может в самой бы компненте который соединит и svg и стили для него будет отпрагиывать от глабольного определние html[data-theme='dark']

2021-11-06 17:33 UTC, GhostMayor commented on website/src/features/feedback/doc/styles.module.css
> +    line-height: var(--height);
теперь это место не явно привзано идти за .root

2021-11-06 17:36 UTC, GhostMayor requested changes

2021-11-06 17:36 UTC, GhostMayor commented on website/src/shared/ui/row/styles.module.css
> +    /* margin-top: 0.5rem; */
нужен ли тут коммент ?

2021-11-06 17:36 UTC, GhostMayor commented on website/src/shared/ui/row/index.jsx
> +        return <span className={styles.icon}>{Icon}</span>;
icon как строка имеется ввиду символы ? которые вы в шрифт свой подвяжите или как ?

2021-11-06 17:38 UTC, azinit commented on website/src/app/index.css
> +
**Кажется оверкильно для простой схемки - по крайней мере "пока что")**

Говорюж- тут скорее мы оверрайдим глобальную логику под конкретный случай
Не сказать что это "по зоне ответственности" как-то мешает страницам 🤔 
_(у нас же для этого и есть эти attrs-selectors - чтобы конкретную пикчу закомпозить нужным кол-вом атрибутов)_

2021-11-06 17:43 UTC, spotsccc approved these changes

2021-11-06 17:50 UTC, azinit commented on website/src/shared/ui/row/index.jsx
> +        return <span className={styles.icon}>{Icon}</span>;
Нет, обычный эмодзи. Добавлю коммент, спс

![image](https://user-images.githubusercontent.com/42924400/140619029-2e0b6ef3-0ccd-4a3c-8590-25457e61ef68.png)

2021-11-06 17:51 UTC, azinit commented on website/src/shared/ui/row/styles.module.css
> +    /* margin-top: 0.5rem; */
Прав, поправлю)

2021-11-06 17:52 UTC, azinit commented on website/src/features/feedback/doc/styles.module.css
> +    line-height: var(--height);
Я ж объяснил выше почему так))

И не "неявно", а прям рядом с местом использования

2021-11-06 17:59 UTC, merged