feat: migrated project from css to scss
feature-sliced/documentation pull request #355
Opened 2021-11-13 17:30 UTC by tednaaa

## CHANGELOG

- Добавил scss и поменял все обычные css файлы на scss
- Поправил package.json, т.к когда пытался запустить тесты, у меня на windows 10, eslint  ругался на кавычки

## Чеклист

- [ ] Если при работе с документацией потребовалось использовать **github-дискуссии, то стоит их прикрепить как see-also источники**
- [ ] Если PR связан с задачей, то необходимо проверить, что **все требования по задаче выполнены**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно ознакомиться с [CONTIBUTING-гайдлайнами](https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md)**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно провести self-review своих изменений**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дождаться CI-проверок**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дать краткое описание изменений**

2021-11-13 17:38 UTC, tednaaa commented on website/package.json
> +        "test:lint": "eslint ./**/*.{ts,tsx,js,jsx} && stylelint ./**/*.scss",
убрал кавычки, т.к eslint падал с ошибкой что не найдено файлов по данному регексу

2021-11-13 17:38 UTC, tednaaa commented on website/src/app/index.scss
> +    &::-webkit-scrollbar {
псевдоэлементы либо псевдо селекторы я пишу через знак `&`, если из за этого становится не читабельно, могу поменять, но в целом думаю норм

2021-11-13 17:38 UTC, tednaaa commented on website/src/app/index.scss
> +// }
убрал один из :hover, проверил на сайте, opacity менялся у иконок гитхаба и телеграма, также перенес внутри самого класса

2021-11-13 17:38 UTC, tednaaa commented
#142

2021-11-13 17:44 UTC, tednaaa commented
@azinit сделай код ревью плиз

2021-11-13 19:59 UTC, azinit requested changes
Есть пару критов, а в целом - 🔥

2021-11-13 19:59 UTC, azinit commented on website/package.json
>          "test:lint:fix": "eslint --fix './**/*.{ts,tsx,js,jsx}' && stylelint **/*.css --fix",
[`nitpick(critical):`](https://conventionalcomments.org/#labels) Здесь бы тож поправить на `scss`)

2021-11-13 19:59 UTC, azinit commented on website/package.json
> +        "sass": "^1.43.4",
[`question:`](https://conventionalcomments.org/#labels) А там с плагином разве требуется отдельно sass ставить? Он не идет "в комплекте"?

2021-11-13 19:59 UTC, azinit commented on website/src/features/feedback/doc/index.jsx
> +import styles from "./styles.module.scss";
[`nitpick:`](https://conventionalcomments.org/#labels) Здесь и далее в стилях лучше бы тоже адаптировать под scss)

(тобишь nested-селекторы добавить, как ты это выше делал)

2021-11-13 19:59 UTC, azinit commented on website/src/pages/_home/styles.module.scss
>  .companiesItemImg {
[`nitpick:`](https://conventionalcomments.org/#labels) Аналогично, добавить бы нестинга)

2021-11-13 19:59 UTC, azinit commented on website/src/shared/ui/row/styles.module.scss
> +    }
[`praise:`](https://conventionalcomments.org/#labels) Во, здесь добавил нестинг - круть 🚀

2021-11-13 19:59 UTC, azinit commented on website/package.json
> +        "test:lint": "eslint ./**/*.{ts,tsx,js,jsx} && stylelint ./**/*.scss",
[`thoughts:`](https://conventionalcomments.org/#labels)
А у меня наоборот, падает без ковычек))

Да и CI не прогонялся раньше без ковычек

![image](https://user-images.githubusercontent.com/42924400/141657264-cab5011f-33ed-434e-9f35-589f36ec8f5b.png)

2021-11-13 19:59 UTC, azinit commented on website/package.json
> +        "test:lint": "eslint ./**/*.{ts,tsx,js,jsx} && stylelint ./**/*.scss",
[`suggestion:`](https://conventionalcomments.org/#labels) Го обратно вернем?)

2021-11-13 19:59 UTC, azinit commented on website/src/app/index.scss
> -/* FIXME: temp hack for adaptive-layout! */
[`question:`](https://conventionalcomments.org/#labels) Так хак остался хаком, чего убрал коммент то 😄

2021-11-13 19:59 UTC, azinit commented on website/src/app/index.scss
> +// }
[`praise:`](https://conventionalcomments.org/#labels) Да, давай уберем тогда вместе с комментом)
Круть что заметил!

2021-11-14 03:51 UTC, tednaaa commented on website/package.json
> +        "test:lint": "eslint ./**/*.{ts,tsx,js,jsx} && stylelint ./**/*.scss",
Окей, верну обратно, возможно из за повершела было такое

2021-11-14 03:54 UTC, tednaaa commented on website/package.json
> +        "sass": "^1.43.4",
В доке было написано что нужно 2 этих пакета скачать

2021-11-14 03:55 UTC, tednaaa commented on website/src/app/index.scss
> -/* FIXME: temp hack for adaptive-layout! */
Упс, это я случайно 😅

2021-11-14 10:23 UTC, azinit commented
@tednaaa Пингани тогда еще раз, как поправишь)

2021-11-14 17:29 UTC, tednaaa commented on website/package.json
> +        "test:lint": "eslint ./**/*.{ts,tsx,js,jsx} && stylelint ./**/*.scss",
![image](https://user-images.githubusercontent.com/79831859/141691649-af6c3fcb-ad7a-4082-ae93-76d2cd3130b8.png)

у меня вот так сработало, может и у тебя сработает?

2021-11-14 17:35 UTC, tednaaa commented on website/src/pages/_home/styles.module.scss
>  .companiesItemImg {
не совсем понял этот момент😅 тут вроде нету селекторов чтобы добавить нестинг, или речь про медиа запросы?

2021-11-14 22:06 UTC, azinit commented on website/src/pages/_home/styles.module.scss
>  .companiesItemImg {
Ну типа))

![image](https://user-images.githubusercontent.com/42924400/141700466-638e0cd2-0064-46ba-900c-1d0ab38bffe6.png)

2021-11-14 22:18 UTC, azinit commented on website/package.json
> +        "test:lint": "eslint ./**/*.{ts,tsx,js,jsx} && stylelint ./**/*.scss",
Выписал ишью, предлагаю щас на это время не тратить)
https://github.com/feature-sliced/documentation/issues/357

2021-11-15 05:22 UTC, tednaaa commented
@azinit вроде переделал все на nested селекторы

2021-11-15 08:10 UTC, azinit requested changes
Крит)

А так бы влили уже

2021-11-15 08:10 UTC, azinit commented on website/package.json
> +=======
Чет не везде зарезолвил конфликты))

_(хотя я это за тебя уже делал, тебе спуллить оставалось)_

2021-11-15 08:10 UTC, azinit commented on website/package.json
> +=======
@tednaaa

2021-11-15 08:53 UTC, tednaaa commented on website/package.json
> +=======
я немного затупил видимо, но при пулле у меня это возникло и не получалось с самой главной репы получить изменены (из за этого форс пуш сделал), сейчас поправлю

2021-11-15 08:59 UTC, tednaaa commented on website/package.json
> +=======
готово)

2021-11-15 09:45 UTC, azinit commented
@tednaaa Как можно будет ревьювить - дай знать)

![image](https://user-images.githubusercontent.com/42924400/141759373-9e919995-dd8b-41b6-b032-18e987990d5f.png)

2021-11-15 16:38 UTC, Postamentovich approved these changes

2021-11-15 20:36 UTC, azinit approved these changes

2021-11-15 20:36 UTC, merged