OpenGraph dynamic image plugin prototype.
feature-sliced/documentation pull request #368
Opened 2021-11-20 15:24 UTC by Krakazybik

## CHANGELOG

Добавлено: Прототип плагина динамической генерации og картиночек.
Как работает:  на этапе postBuild выковыривает данные Doc плагина, и на основе их по шаблону генерирует картиночки, и сохраняет в assets/og с именем файла sha1(doc.id+doc.locale).jpg

2021-11-27 20:02 UTC, azinit commented
@Krakazybik 
1. Верни пож ченджлог, который был в [темплейте PR](https://github.com/feature-sliced/documentation/blob/master/.github/pull_request_template.md))
2. Добавь пож комменты к диффу своему, чтобы было проще ревьювить и предлагать изменения
(оч хочется втянуть, но многие вещи не оч интуитивно понятны - лучше бы дополнить их комментарием, например [как тут](https://github.com/feature-sliced/documentation/pull/354))

> Как все сделаешь - пингани еще раз как можно будет ревьювить))
>
> Думаю втянем сразу же, только с небольшими правками, чтобы прод не развалить

2021-11-27 20:03 UTC, azinit requested changes
@Krakazybik 
1. Верни пож ченджлог, который был в [темплейте PR](https://github.com/feature-sliced/documentation/blob/master/.github/pull_request_template.md))
2. Добавь пож комменты к диффу своему, чтобы было проще ревьювить и предлагать изменения
(оч хочется втянуть, но многие вещи не оч интуитивно понятны - лучше бы дополнить их комментарием, например [как тут](https://github.com/feature-sliced/documentation/pull/354))

> Как все сделаешь - пингани еще раз как можно будет ревьювить))
>
> Думаю втянем сразу же, только с небольшими правками, чтобы прод не развалить

2021-11-27 22:08 UTC, Krakazybik commented on website/open-graph-templates/basic/template.json
> +{
!Required! Обязательный. Базовый шаблон нашей превьюшки, описываем собственно слой картинки, шрифт, и расположение (в layout) наших динамических слоёв. 

- type - задел на будущее, планируется: картинка, постэффект и тд.
- name - поле берётся из docusaurus.doc ( TODO: описать возможные варианты в Readme)
- fontSize - понятно.
- fill -  цвет заливки
- stroke - цвет контура
- top / left - позиционирование относительно начала изображения.

2021-11-27 22:14 UTC, Krakazybik commented on website/open-graph-templates/config.json
> +{
Наш основной конфиг плагина.

- outputDir - в какую папку билда кладём картиночки
- textWidthLimit - пока как хак максимальный размер текста.
- quality - JPEG Quality наших картинок на выходе.
- rules - (применение шаблона по пути документа) здесь мы описываем имя шаблона (из папки templates), который будет применён к пути, приоритет, и собственно RegExp шаблон пути. Соответственно более высокий приоритет перекрывает более низкий.

2021-11-27 22:15 UTC, Krakazybik commented on website/open-graph-templates/config.json
> +{
Наш основной конфиг плагина.

- outputDir - в какую папку билда кладём картиночки
- textWidthLimit - пока как хак максимальный размер текста.
- quality - JPEG Quality наших картинок на выходе.
- rules - (применение шаблона по пути документа) здесь мы описываем имя шаблона (из папки templates), который будет применён к пути, приоритет, и собственно RegExp шаблон пути. Соответственно более высокий приоритет перекрывает более низкий.

2021-11-27 22:18 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/Readme.md
> +# Docusaurus OpenGraph image generator plugin
Документатьён. Котики радуются когда есть хорошая документация! Пока здесь ничего не понятно, но очень интересно. Дополню.

2021-11-27 22:21 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/config.js
> +    return config;
Чтение и валидация нашего основного конфига плагина.

2021-11-27 22:24 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
> +    return fonts;
Создаём мапу уникальных шрифтов(проверяется по имени), соответственно если в нашей коллекции нет такого шрифта, подгружаем и добавляем.

2021-11-27 22:28 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
> +    return font.getSVG(text, options);
Превращаем наш текст в SVG, если текст выходит за границы widthLimit, уменьшаем размер шрифта, до ~90% от widthLimit.

2021-11-27 22:29 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/image.js
> +    return sharp(file);
Задел на будущее. Пока ничего не делает полезного не делает, кроме как создание sharp объекта.

2021-11-27 22:31 UTC, azinit reviewed
Отписал комментарии по PR (test)

2021-11-27 22:31 UTC, azinit commented on website/docusaurus.config.js
> +const path = require("path");
111

2021-11-27 22:31 UTC, azinit commented on website/docusaurus.config.js
> +    [
222

2021-11-28 11:00 UTC, Krakazybik reviewed
Добавил комментарии по PR.

2021-11-28 13:00 UTC, azinit commented on website/src/theme/DocItem/index.js
> +            <OpenGraphPreview imgUrl={`http://dev.evgeraskin.ru/assets/og/${hashFileName}.jpg`} />
ага, поправить бы)

2021-11-28 13:00 UTC, azinit commented on website/src/theme/DocItem/index.js
> +import { OpenGraphPreview } from "../../shared/lib/open-graph-preview";
ага, поправить бы) [2]

2021-12-04 12:37 UTC, Krakazybik commented on website/src/theme/DocItem/index.js
> +
Приходит!

2021-12-04 12:38 UTC, azinit reviewed
Таки посмотрел... Выглядит прям монструозно, крутецкую работу проделал!

Вопросы такие:
1) **Можно ли как-то  оставить в плагине только критичный функционал, чтоб без проблем затащить что есть?**
_(а то по многим модулям там есть вопросы, и кажется, что расширять функционал надо бы позднее, а не прям щас - сложно пока даже умом объять. И кажется именно из-за сильно огромного функционала влитие PR может затянуться. Если можно оставить только базис - я бы оставил действительно только его на данный момент .А остальное след. итерациями)_

2) **Можно ли локально при билде - получить OG изображения файлов?**
_(как я понимаю - изображения сгенерятся при билде, и потом по хешу, что будет в `head.meta.og:image`  можно будет перейти по ссылке и получить статическое превью - верно?)_

2021-12-04 12:38 UTC, azinit commented on website/open-graph-templates/config.json
> +}
Немного  все же неясно - что за правила, и зачем там приоритеты? 🤔

2021-12-04 12:38 UTC, azinit commented on website/open-graph-templates/config.json
> +}
Или тип у нас есть базовый шаблон для всех страниц (не только DocItem), но есть шаблоны для конкретных секций статей?

2021-12-04 12:38 UTC, azinit commented on website/plugins/docusaurus-plugin-open-graph-image/Readme.md
> +# Docusaurus OpenGraph image generator plugin
Топ дока, многое встало на свои места после прочтения 👍

2021-12-04 12:38 UTC, azinit commented on website/plugins/docusaurus-plugin-open-graph-image/layout.js
> +            console.error(`Wrong template config? Doc property ${item.name} not found.`);
[`nitpick:`](https://conventionalcomments.org/#labels) Мб так?
```suggestion
        if (!doc[item.name]) {
            console.error(`Wrong template config? Doc property ${item.name} not found.`);
```

2021-12-04 12:38 UTC, azinit commented on website/plugins/docusaurus-plugin-open-graph-image/layout.js
> +            return undefined;
[`nitpick:`](https://conventionalcomments.org/#labels) Можно и проще, как ниже делал)

```suggestion
            return;
```

2021-12-04 12:38 UTC, azinit commented on website/plugins/docusaurus-plugin-open-graph-image/layout.js
> +}
[`question:`](https://conventionalcomments.org/#labels) А для понимания еще раз - что все таки собой эти слои представляют?)

2021-12-04 12:38 UTC, azinit commented on website/src/theme/DocItem/index.js
> +
[`nitpick:`](https://conventionalcomments.org/#labels) Чет кажется, что должен быть отдельный геттер `getHashname`, учитывая что эта логика уже есть в плагине)

2021-12-04 12:38 UTC, azinit commented on website/src/theme/DocItem/index.js
> +import { OpenGraphPreview } from "../../shared/lib/open-graph-preview";
`@site/src/shared` если что имел в виду)

2021-12-04 12:57 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/layout.js
> +}
Представь работу с изображением в ФШ, примерно тоже самое, есть базовое изображение и мы слоями накладываем сверху наш текст и etc

2021-12-04 12:59 UTC, Krakazybik commented on website/src/theme/DocItem/index.js
> +
На самом деле хотелось бы остаться без пересечения логики плагина и сайта, т.к. в дальнейшем может быть плагин уйдёт в пакет. Но я могу ошибаться =)

2021-12-04 13:15 UTC, Krakazybik commented
> Таки посмотрел... Выглядит прям монструозно, крутецкую работу проделал!
> 
> Вопросы такие:
> 
> 1. **Можно ли как-то  оставить в плагине только критичный функционал, чтоб без проблем затащить что есть?**
>    _(а то по многим модулям там есть вопросы, и кажется, что расширять функционал надо бы позднее, а не прям щас - сложно пока даже умом объять. И кажется именно из-за сильно огромного функционала влитие PR может затянуться. Если можно оставить только базис - я бы оставил действительно только его на данный момент .А остальное след. итерациями)_
> 2. **Можно ли локально при билде - получить OG изображения файлов?**
>    _(как я понимаю - изображения сгенерятся при билде, и потом по хешу, что будет в `head.meta.og:image`  можно будет перейти по ссылке и получить статическое превью - верно?)_

1. На самом деле старался максимально изолированно делать всё, потому и делал через плагин, даже если что-то в процессе билда пойдёт не так, сайт сбилдится(точнее оно уже будет собрано т.к. делаем на postBuild) и ни как на функционал сайта это влиять не должно. И по сути ни каких breaking changes тут не должно быть.
2. Да, на этапе postBuild, когда уже всё собрано (и по сути meta пути для OG уже прописаны, которые берутся из id документа и его локали), мы генерим наши превьюшки, получаем обычные jpg изображение сложенные в папку assert для базовой локали и ${locale}/assert для остальных.

2021-12-04 14:01 UTC, Krakazybik commented on website/open-graph-templates/config.json
> +}
Все манипуляции пока только с Doc статьями, но для каждого айди статьи (который выглядит примерно как путь и я использую везде понятие "путь", чтоб не путать людей с числовым айди) или какой-то маски статей (/about/* например) мы можем сделать свой шаблон, со своей картинкой фона, своим расположением и настройками текста или вообще допустим сделать для каких-то статей только title, а для каких-то title и description будет в слоях.

2021-12-04 14:02 UTC, Krakazybik commented on website/open-graph-templates/config.json
> +}
> 

Все манипуляции пока только с Doc статьями, но для каждого айди статьи (который выглядит примерно как путь и я использую везде понятие "путь", чтоб не путать людей с числовым айди) или какой-то маски статей (/about/* например) мы можем сделать свой шаблон, со своей картинкой фона, своим расположением и настройками текста или вообще допустим сделать для каких-то статей только title, а для каких-то title и description будет в слоях.

2021-12-04 15:26 UTC, azinit commented on website/docusaurus.config.js
>  const DOMAIN = "https://feature-sliced.design/";
@Krakazybik можешь кста пока так написать:

```js
const DOMAIN = process.env.DOMAIN || "https://feature-sliced.design/";
```

А там позже адаптируем

2021-12-04 15:26 UTC, azinit commented on website/docusaurus.config.js
>  const DOMAIN = "https://feature-sliced.design/";
Чисто, чтоб локально можно было отдебажиться

2021-12-04 15:38 UTC, azinit commented on website/src/shared/lib/open-graph-preview/index.js
> +}
Почему-то кста с помощью head не переопределяется уже существующий параметр
Возможно проблемы потом от этого будут 🤔 

![image](https://user-images.githubusercontent.com/42924400/144715364-66c0dacd-a00c-4563-80de-c965676f4693.png)

2021-12-04 15:41 UTC, azinit commented on website/open-graph-templates/config.json
> +}
Тогда для примера в ридмихе можно оставить
Но в самом конфиге - только basic-template, чтоб не путало)

2021-12-04 15:45 UTC, azinit commented
> 2\. Да, на этапе postBuild, когда уже всё собрано (meta пути для OG уже прописаны, которые берутся из id документа и его локали), мы генерим наши превьюшки, получаем обычные jpg изображение сложенные в папку assert для базовой локали и ${locale}/assert для остальных.

Да, удалось отдежабиться - круто)



> 1. На самом деле старался максимально изолированно делать всё, потому и делал через плагин, даже если что-то в процессе билда пойдёт не так, сайт сбилдится(точнее оно уже будет собрано т.к. делаем на postBuild) и ни как на функционал сайта это влиять не должно. И по сути ни каких breaking changes тут не должно быть.

Да, если локально глянуть - то так и выглядит, спасибо)
Просто внешне это не особо заметно 🤔 
![image](https://user-images.githubusercontent.com/42924400/144715653-cd73ed2a-fa97-4538-bce4-520db2557ae2.png)

2021-12-04 15:48 UTC, azinit commented
@Krakazybik пока надо лично мне еще минимум час-два убить, чтобы доревьювить по мелочам + подправить темплейт и стили
Так что до след выходных постараюсь что-то подготовить

> Но если оч хочешь влить, предлагаю разбить опять же этот PR на несколько частей
>
> Как минимум:
> - docusaurus-плагин, неподключенный (да, это основа диффа, зато точно ничего не поломает, и можно влить до того, как превьюшку добьем)
> - подключение плагина + настройка конфига и превью

2021-12-04 16:06 UTC, Krakazybik commented on website/src/shared/lib/open-graph-preview/index.js
> +}
Ага, я вроде тестил, и подцепляются только последние ссылки у всех. Но с этим всё-таки что-то лучше потом придумать.

2021-12-09 22:29 UTC, azinit approved these changes
Выглядет рабочеспособно)
Как вольем - приступим к некст этапу 🚀

2021-12-10 17:21 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/index.js
> +
В принципе можно и вынести, но у docusaurus всё суётся в одно место =)
(Пример)[https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-plugin-content-docs/src/index.ts]

2021-12-10 18:01 UTC, Krakazybik commented on website/package.json
> +        "text-to-svg": "^3.1.5",
"sharp" "superstruct" "text-to-svg": нужно в dev кинуть =)

2021-12-10 18:14 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/image.js
> +function createImagePipeline(file) {
Комменты в коде, или здесь? =)

2021-12-10 18:17 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/utils.js
> +}
Разумно =)

2021-12-10 18:43 UTC, Krakazybik commented on website/package.json
> +        "text-to-svg": "^3.1.5",
либо монорепу (лул), либо "sharp" "superstruct" "text-to-svg": можно в dev кинуть =) и отучить линтер матюгаться по  import/no-extraneous-dependencies для папки плагина =)

2021-12-10 18:45 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/image.js
> +            images.set(`${item.name}_${item.params.image}`, createImageFromTemplate(item));
Будет сделано =)

2021-12-10 20:04 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/index.js
> +
Ну можно такой вариант, например. Но немного не как в docusaurus :D

```
const fs = require("fs");
const sha1 = require("sha1");
const { getTemplates } = require("./template");
const { createLayoutLayers } = require("./layout");
const { createFontsMapFromTemplates } = require("./font");
const { createImagesMapFromTemplates, getTemplateImageId } = require("./image");
const { getConfig } = require("./config");
const { getTemplateNameByRules } = require("./rules");

module.exports = function ({ templatesDir }) {
    const initData = bootstrap();
    if (!initData) console.error("OpenGraph plugin exit with error.");

    const { config } = initData;

    return {
        name: "docusaurus-plugin-open-graph-image",
        async postBuild({ plugins, outDir, i18n }) {
            const docsPlugin = plugins.find(
                (plugin) => plugin.name === "docusaurus-plugin-content-docs",
            );

            if (!docsPlugin) throw new Error("Docusaurus Doc plugin not found.");

            const previewOutputDir = `${outDir}\\${config.outputDir}`;
            fs.mkdir(previewOutputDir, { recursive: true }, (error) => {
                if (error) throw error;
            });

            const docsContent = docsPlugin.content;
            const docsVersions = docsContent.loadedVersions;
            docsVersions.forEach((version) => {
                const { docs } = version;

                docs.forEach((item) => {
                    generateImageFromDoc(initData, item, i18n.currentLocale, previewOutputDir);
                });
            });
        },
    };
};

function bootstrap(templatesDir) {
    const isProd = process.env.NODE_ENV === "production";
    if (!isProd) return;

    if (!templatesDir) {
        console.error("Wrong templatesDir option.");
        return;
    }

    const templates = getTemplates(templatesDir);
    if (!templates) return;

    const config = getConfig(templatesDir);
    if (!config) return;

    // TODO: File not found exception?
    const fonts = createFontsMapFromTemplates(templates);
    const images = createImagesMapFromTemplates(templates);

    return { templates, config, fonts, images };
}

async function generateImageFromDoc({ templates, config, images, fonts }, doc, locale, outputDir) {
    const { id, title } = doc;

    const hashFileName = sha1(id + locale);

    const templateName = getTemplateNameByRules(id, config.rules);

    const template = templates.find((item) => item.name === templateName);

    const previewImage = await images.get(getTemplateImageId(template)).clone();

    const previewFont = fonts.get(template.params.font);

    const textLayers = createLayoutLayers(
        doc,
        template.params.layout,
        previewFont,
        config.textWidthLimit,
    );

    try {
        await previewImage.composite(textLayers);
        await previewImage
            .jpeg({
                quality: config.quality,
                chromaSubsampling: "4:4:4",
            })
            .toFile(`${outputDir}\\${hashFileName}.jpg`);
    } catch (error) {
        console.error(error, id, title, hashFileName);
    }
}
```

2021-12-10 20:33 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
> +}
Такой? =)

2021-12-10 20:34 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
> +}
Так? =)

2021-12-10 20:37 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/template.js
> +
Читаем наши шаблоны, согласно полученным папкам. И возвращаем массив объектов с прочитанными данными, названием шаблона и путем до него.

2021-12-10 20:48 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/layout.js
> +            return undefined;
Вернул, т.к. снова наткнулся на то что матюгальник проснулся =))
![image_2021-12-10_23-42-02](https://user-images.githubusercontent.com/1334019/145639452-f7b3ce13-d97b-4df6-853a-92865169d840.png)

2021-12-10 21:07 UTC, Krakazybik commented
Кот починиль! 
[Это](https://github.com/feature-sliced/documentation/pull/368#discussion_r766199692) => [тут](https://github.com/feature-sliced/documentation/pull/368/commits/e26094c021128af4cb6a4f119055107456c94c5a).
Зарезолвил. [вот это](https://github.com/feature-sliced/documentation/pull/368/commits/f34a49c7ee1291d22b7362a19a9c44de2b7f8fb5)

Ну и так немного навёл марафета =)

Это чтобы не потерялось, а то комментарии пропали =)

2021-12-10 21:31 UTC, azinit commented on website/plugins/docusaurus-plugin-open-graph-image/image.js
> +function createImagePipeline(file) {
в коде

2021-12-10 21:32 UTC, azinit commented on website/package.json
> +        "text-to-svg": "^3.1.5",
Ну пока так оставим, мб @Postamentovich @GhostMayor что-то подскажут

(для контекста опять же - это docusaurus-plugin, который чисто во время сборки нужен)

2021-12-10 21:35 UTC, azinit commented on website/plugins/docusaurus-plugin-open-graph-image/template.js
> +
Тогда мб лучше в сам код занести)

2021-12-10 21:42 UTC, azinit commented on website/plugins/docusaurus-plugin-open-graph-image/index.js
> +
Да вродь оч даже)

Я тем более лишь про generateImageFromDoc просил

Но и так оч классно выглядит 👍

2021-12-11 09:39 UTC, azinit commented on website/plugins/docusaurus-plugin-open-graph-image/layout.js
> +    if (!layout.every((layer) => doc[layer.name])) {
[`thoughts:`](https://conventionalcomments.org/) Можно заменить на .some, но некрит вообще)

```diff
- if (!layout.every((layer) => doc[layer.name])) {
+ if (layout.some((layer) => !doc[layer.name])) {
```

2021-12-11 10:48 UTC, azinit commented
@feature-sliced/core @feature-sliced/contributors Гляньте пож)

2021-12-11 13:56 UTC, azinit commented
@all-contributors please add @Krakazybik for code,plugin,tool

2021-12-11 13:57 UTC, azinit commented
@all-contributors please add @Krakazybik for code, plugin, tool

2021-12-12 15:46 UTC, Postamentovich approved these changes
Все ок, я только обратил бы внимание на работу с файловой системой.
Путь до конфига и ассетов лучше собирать через `path`
И лучше не использовать синхронные методы чтения.
Но так как это выполняется в постбилде, возможно это не очень актуально.

2021-12-12 15:55 UTC, merged