feat: added new example showing logic
feature-sliced/documentation pull request #369
Opened 2021-11-20 19:37 UTC by tednaaa

## CHANGELOG

- Добавил фичу чтобы выделялись примеры которые были добавлены недавно
- Поправил(а) ...

## Чеклист

- [ ] Если при работе с документацией потребовалось использовать **github-дискуссии, то стоит их прикрепить как see-also источники**
- [ ] Если PR связан с задачей, то необходимо проверить, что **все требования по задаче выполнены**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно ознакомиться с [CONTIBUTING-гайдлайнами](https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md)**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно провести self-review своих изменений**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дождаться CI-проверок**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дать краткое описание изменений**

2021-11-20 19:39 UTC, tednaaa commented on website/src/pages/examples/_config.js
> +        updatedAt: null,
не знал какую дату поставить, решил оставить null в 5 примерах

2021-11-20 19:40 UTC, tednaaa commented
#365

2021-11-21 09:25 UTC, azinit requested changes
@tednaaa Все круто, только с датой крит есть)

2021-11-21 09:25 UTC, azinit commented on website/src/entities/example/styles.module.scss
> +}
Тут нужно было самому "поиграться", т.к. идея с бордером - была только драфтом и имела минусы:
- Слабо выделяла новые работы (и скорее путала с hover-стилями)
- Не давала контекст, что это именно НОВЫЙ пример из списка, который можно глянуть
- С бордерами в целом [оч много проблем](https://user-images.githubusercontent.com/42924400/142756000-a9920542-22ec-46c2-b1a7-478ed15c8ee7.png) из-за смещения контента внутреннего

2021-11-21 09:25 UTC, azinit commented on website/src/entities/example/styles.module.scss
> +}
Пробовал разные варианты:

1. border (как было)
![image](https://user-images.githubusercontent.com/42924400/142756018-7489c1f3-490f-43e0-b731-cc6dad8ea929.png)

2. border + label (слишком громоздко кмк)
![image](https://user-images.githubusercontent.com/42924400/142756017-db3f44a7-06a1-4f30-8387-1494af1da1b9.png)

3. label
![image](https://user-images.githubusercontent.com/42924400/142756022-d283c4b3-9894-4c4b-80a6-48af23f93b8b.png)

> Был еще вариант с окраской текста , но выглядело уж совсем дичево

2021-11-21 09:25 UTC, azinit commented on website/src/entities/example/styles.module.scss
> +}
В итоге остановился на третьем варике)

Сразу запушил, чтоб не мисматчится по ожиданиям лишний раз

![image](https://user-images.githubusercontent.com/42924400/142756042-832ff2b4-b97b-498e-ac42-58256ba0bc41.png)

2021-11-21 09:25 UTC, azinit commented on website/src/entities/example/styles.module.scss
> +}
*Ну и да, на картинке специально **NEW:** помечены разные карточки, чисто для проверки стиля. По факту из новых - там только loripsum-generator

2021-11-21 09:25 UTC, azinit commented on website/src/pages/examples/_config.js
> +        updatedAt: "11/17/2021",
[`nitpick:`](https://conventionalcomments.org/#labels) Я бы всеж ISO-формат заиспользовал)

```diff
# Bad: Специфичный формат, не так распространен
- 11/17/2021
# Ok: Более распространенный формат, хоть и не полностью ISO
+ 2021-11-17
# Good: Вообще топ, просто время не надо указывать
+ 2021-11-17T00:00:00

2021-11-21 09:25 UTC, azinit commented on website/src/entities/example/index.jsx
> +    const isNew = new Date(data.updatedAt).getDate() >= new Date(Date.now()).getDate() - 14;
[`issue(critical):`](https://conventionalcomments.org/#labels) Увы, эта логика будет работать только в рамках одного месяца)

![image](https://user-images.githubusercontent.com/42924400/142756256-934c330d-71fc-40a6-96f3-4f24e0ef1465.png)

2021-11-21 09:25 UTC, azinit commented on website/src/entities/example/index.jsx
> +    const isNew = new Date(data.updatedAt).getDate() >= new Date(Date.now()).getDate() - 14;
[`suggestion:`](https://conventionalcomments.org/#labels) Я бы предложил сравнивать полноценно по timestamp (через тот же getTime)

И считать прям количество дней между updatedAt и текущей датой

2021-11-21 09:25 UTC, azinit commented on website/src/entities/example/index.jsx
> +    const isNew = new Date(data.updatedAt).getDate() >= new Date(Date.now()).getDate() - 14;
[`praise:`](https://conventionalcomments.org/#labels) Но да, втягивать отдельно либу для работы с датами для этого не имеет смысла, тут нативно прям разрулить можно)

[`thoughts:`](https://conventionalcomments.org/#labels) Думаю, можно будет эту логику положить прям в `shared/lib/date`

[`thoughts:`](https://conventionalcomments.org/#labels) Можно причем не шаманить с датами, 
А просто реализовать функцию `getDiffDays(date1: Date, date2: Date): number`, 
А там уже "на месте" в компоненте сранивать с нужным числом (в нашем случае "14")

2021-11-21 09:25 UTC, azinit commented on website/src/pages/examples/_config.js
> +        updatedAt: null,
В целом прав, но я там актуализировал даты, чтоб потом вопросов не было)

![image](https://user-images.githubusercontent.com/42924400/142756600-86978b5e-6c04-4db0-90f7-61a39ba72142.png)

2021-11-21 09:25 UTC, azinit commented on website/src/pages/examples/_config.js
> +        updatedAt: "2021-11-12",
Актуализировал даты и версии, вместо `updatedAt: null`

https://github.com/feature-sliced/documentation/pull/369/commits/93ed9faee062b46d6de19737f8f3ed1d574d12c2

2021-11-21 09:29 UTC, azinit commented on website/src/entities/example/index.jsx
> +                {isNew && <span className={styles.labelNew}>NEW: </span>}
[`suggestion:`](https://conventionalcomments.org/#labels) @tednaaa Хотя учитывая, что лейбл выглядит как интерактивный элемент, предлагаю добавить к спану еще `title="Was updated less than 2 weeks ago"`

2021-11-21 09:29 UTC, azinit commented on website/src/pages/examples/_config.js
> +        updatedAt: "11/17/2021",
В итоге и заиспользовал)

2021-11-21 12:12 UTC, azinit commented on website/src/entities/example/styles.module.scss
> +}
@tednaaa Если есть предложения получше - feel free поправить)

Мне просто вариант с бордером прям не нравился, решил налету поиграться с вариантами

2021-11-21 16:33 UTC, tednaaa commented on website/src/entities/example/index.jsx
> +    const isNew = getDiffDays(new Date(data.updatedAt), new Date(Date.now())) <= 14;
тут наверно можно было вынести 14 в переменную, но у меня не получилось придумать нормальное название 😅

2021-11-21 20:19 UTC, azinit approved these changes
Некритично, но есть что улучшить)

Спс за контрибьютинг!

2021-11-21 20:19 UTC, azinit commented on website/src/entities/example/index.jsx
> +import { getDiffDays } from "@site/src/shared/lib/date/getDiffDays";
@tednaaa Ай-ай))

![image](https://user-images.githubusercontent.com/42924400/142777445-2474425e-d6e0-4119-8f32-ce08275322b6.png)

2021-11-21 20:19 UTC, azinit commented on website/src/entities/example/index.jsx
> +                    <span title="Was updated less than 2 weeks ago" className={styles.labelNew}>
Спс что добавил тайтл

2021-11-21 20:19 UTC, azinit commented on website/src/shared/lib/date/getDiffDays.js
> +    return Math.floor(Math.abs(firstDate.getTime() - secondDate.getTime()) / 1000 / 60 / 60 / 24);
1. А зачем модуль разницы?)
2. Некрит, но вынес бы в константу шаманство с ms

2021-11-21 20:19 UTC, azinit commented on website/src/entities/example/index.jsx
> +    const isNew = getDiffDays(new Date(data.updatedAt), new Date(Date.now())) <= 14;
`nitpick:` Так он кста и так создаст текущую дату, не обязательно же `Date.now()` еще прокидывать внутрь)

2021-11-22 04:32 UTC, tednaaa commented on website/src/shared/lib/date/getDiffDays.js
> +    return Math.floor(Math.abs(firstDate.getTime() - secondDate.getTime()) / 1000 / 60 / 60 / 24);
перенести в `entities/example/lib` ?

2021-11-22 05:20 UTC, azinit commented on website/src/shared/lib/date/getDiffDays.js
> +    return Math.floor(Math.abs(firstDate.getTime() - secondDate.getTime()) / 1000 / 60 / 60 / 24);
Не-не, тут именно вопрос в реализации был

2021-11-22 05:22 UTC, azinit commented on website/src/shared/lib/date/getDiffDays.js
> +    return Math.floor(Math.abs(firstDate.getTime() - secondDate.getTime()) / 1000 / 60 / 60 / 24);
@tednaaa Спс что внес правки! И все же не пойму - зачем тут модуль брать)
В нашем случай офк оно все еще будет работать
Но кажется, что "на будущее" знак результата тоже может пригодится в обработке

2021-11-22 17:08 UTC, Postamentovich approved these changes

2021-11-22 17:19 UTC, azinit commented
@all-contributors please add @tednaaa  for code

2021-11-22 17:19 UTC, merged