FEAT(split-368): Connect OpenGraph plugin to Docusaurus.
feature-sliced/documentation pull request #375
Opened 2021-12-08 18:17 UTC by Krakazybik

## CHANGELOG
Split from: #368 

Добавлено:
 - Файл конфигурации плагина OpenGraph.
 - Базовый шаблон плагина.
 - Meta OG ссылки на изображения для Doc страниц.
 - Подключение плагина в Docusaurus.

## Чеклист
- [ ] Если при работе с документацией потребовалось использовать **github-дискуссии, то стоит их прикрепить как see-also источники**
- [x] Если PR связан с задачей, то необходимо проверить, что **все требования по задаче выполнены**
- [x] Перед тем, как отправлять изменения на ревью, **нужно ознакомиться с [CONTIBUTING-гайдлайнами](https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md)**
- [x] Перед тем, как отправлять изменения на ревью, **нужно провести self-review своих изменений**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дождаться CI-проверок**
- [x] Перед тем, как отправлять изменения на ревью, **нужно дать краткое описание изменений**

2021-12-09 05:42 UTC, tednaaa commented on website/src/theme/DocItem/index.js
> +function DocItem(props) {
кстати тут наверно можно сэкономить 1 строку :D `DocItem({ content })`

2021-12-11 18:59 UTC, Krakazybik commented on website/src/theme/DocItem/index.js
> +function DocItem(props) {
Там чуть ниже мы просто прокидываем просы в OriginalDocItem =)

2021-12-12 15:56 UTC, azinit commented
Не забыть поправить работу с файлами)
https://github.com/feature-sliced/documentation/pull/368#pullrequestreview-829641938

2021-12-28 20:08 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
> +            // Center text using spaces.
Авто-центрирование текса

2021-12-30 11:12 UTC, azinit requested changes
Все в целом топчик, и понятно что многое будем лечить следующими итерациями

Но если сконцентрироваться на "Just подключить OG-плагин к докузавру", то несколько мест поправить бы и рассмотреть повнимательней)

(т.к. потом точно забудем)

2021-12-30 11:12 UTC, azinit commented on website/open-graph-templates/basic/template.json
> +  "image": "preview.png",
[`nitpick:`](https://conventionalcomments.org/) Тут тоже бы тогда пока ссылаться на существующую превьюшку из static, чтоб не дублировать

2021-12-30 11:12 UTC, azinit commented on website/open-graph-templates/basic/template.json
> +  "image": "preview.png",
Либо сразу [заглушку загрузить](https://user-images.githubusercontent.com/42924400/147746241-aece6c04-7579-4315-ba55-f4c10463b5cf.png) +- актуальную)

Референсы тоже прикладываю ([ru](https://user-images.githubusercontent.com/42924400/147746346-fc3e80de-ab4e-4b3c-820a-ff7b1e93d9ca.png), [en](https://user-images.githubusercontent.com/42924400/147746348-1bdaa274-6792-48bc-ac40-9aa29265a097.png))

2021-12-30 11:12 UTC, azinit commented on website/src/theme/DocItem/index.js
> +            />
[`nitpick(debug):`](https://conventionalcomments.org/) Ну и тут тоже бы подвязаться на флаг, чтобы не перезатирало лишний раз

[`thoughts:`](https://conventionalcomments.org/) + Можно прям по-хорошему это прям в `shared/config` объявить, как и другие переменные окружения

А оттуда импортить потом (чтоб по канону :D )

```suggestion
            {process.env.OG_EXP && <OpenGraphPreview meta={content.metadata} />
```

2021-12-30 11:21 UTC, azinit commented on website/.eslintrc.js
> +        ],
+ Связано во многом с #254

2021-12-30 11:22 UTC, azinit commented on website/src/theme/DocItem/index.js
> +                }/assets/og/${hashFileName}.jpg`}
Либо чисто на айдишник завязываться, что тоже путь своего рода

2021-12-30 11:23 UTC, azinit commented on website/src/theme/DocItem/index.js
> +                }/assets/og/${hashFileName}.jpg`}
```suggestion
                met={content.metadata}
```

2021-12-30 11:27 UTC, Krakazybik commented on website/open-graph-templates/basic/template.json
> +  ]
Например убрать их? Т.к. они у нас не обязательные и будут использоваться значения по умолчанию.
```
      "fontSize": 80,
      "fill": "white",
      "stroke": "white",
```
P.S. Я бы конечно поспорил про громоздкость, т.к. это всё-таки плагин =)

2021-12-30 11:29 UTC, Krakazybik commented on website/open-graph-templates/config.json
> +  "outputDir": "assets/og",
не понив немного. :thinking: 
Это же и так указывается outputDir в папке build. Объясни пожалуйста.

2021-12-30 11:29 UTC, azinit commented on website/open-graph-templates/basic/template.json
> +  ]
Как вариант да

Мы же для себя плагин настраиваем пока все еще)

Тем более еще конечного видения нет, и апишку использования фигачить можно как угодно

2021-12-30 11:30 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
> +    );
Готов выслушать более красивые и правильные идеи =)

2021-12-30 11:30 UTC, azinit commented on website/open-graph-templates/config.json
> +  "outputDir": "assets/og",
> Это же и так указывается outputDir в папке build. Объясни пожалуйста.

А вот со стороны это неявно)

Самое главное, чтобы эти ассеты не абы где лежали, а в директории `build`

А в идеале - `build/assets/og-img` по аналогии с остальными

2021-12-30 11:31 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
> +            // Center text using spaces.
Не точно

2021-12-30 11:39 UTC, Krakazybik commented on website/src/theme/DocItem/index.js
> +                }/assets/og/${hashFileName}.jpg`}
> [`question:`](https://conventionalcomments.org/) Вот тут кста прям вопрос - а нужно ли нам так хеширование?

Ну если мы не хотим иметь путь длинною в километры, то нужно, т.к. у нас есть вложенность.


> А с регулярными апдейтами доки - будут и хеши меняться - т.е. и кеширование поисковиков будет сбоить - что не то что нам нужно

Можешь пояснить? Просто я не совсем понимаю. У нас хэш же может поменяться только в момент изменения пути документа. Т.к. мы используем sha1(id + locale) для формирования хэша. А id у нас по сути это путь. Или я чего-то не понимаю?

2021-12-30 11:45 UTC, Krakazybik commented on website/src/theme/DocItem/index.js
> +                }/assets/og/${hashFileName}.jpg`}
Ну это же шэред штука, которая устанавливает мету (в частности url для og), и что-то мне кажется не очень верно, чтоб она сама определяла и формировала пути. А лепить над ней абстракцию тоже такое себе. Но это не точно. Разъясни если я не понимаю.

2021-12-30 11:46 UTC, Krakazybik commented on website/open-graph-templates/basic/template.json
> +  "image": "preview.png",
Сделяем!

2021-12-30 11:49 UTC, Krakazybik commented on website/open-graph-templates/config.json
> +  "outputDir": "assets/og",
> А вот со стороны это неявно)

согласен.

Получается
"outputDir": "assets/og",

у нас создаёт в папках build/assets/og и build/en/assets/og 
Ну и для остальных локалей свои папки. по аналогии с en

2021-12-30 11:50 UTC, azinit commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
> +            // Center text using spaces.
Ну вот убрать бы тогда мб)

По коммитам если что найдем, если надо будет

2021-12-30 11:51 UTC, azinit commented on website/open-graph-templates/config.json
> +  "outputDir": "assets/og",
[`nitpick(подушню):`](https://conventionalcomments.org/) А для ru мб тоже локаль создавать?

чтоб более явно было, как и с докой

2021-12-30 11:51 UTC, Krakazybik commented on website/open-graph-templates/config.json
> +  "outputDir": "assets/og",
просто buildOutputDir тоже не явно получается, и я не смог придумать названия. :sorry:

2021-12-30 11:52 UTC, azinit commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
> +    );
На следующем раунде кортиму призовем, посмотрим)

Пока некрит, просто есть ощущение, что нестабильно может работать временами

2021-12-30 11:55 UTC, azinit commented on website/src/theme/DocItem/index.js
> +                }/assets/og/${hashFileName}.jpg`}
> Ну если мы не хотим иметь путь длинною в километры, то нужно, т.к. у нас есть вложенность.

Я бы не стал сильно переживать из-за вложенности)

Тем более если обратное - может SEO повредить

https://deephaven.io/core/docs/tutorials/overview/og-image.png
https://deephaven.io/core/docs/conceptual/choose-select-view-update/og-image.png

2021-12-30 11:57 UTC, azinit commented on website/src/theme/DocItem/index.js
> +                }/assets/og/${hashFileName}.jpg`}
> У нас хэш же может поменяться только в момент изменения пути документа.

Хм, тоже верно по идее... Но я бы на всякий прям проверил - что при 2-3 разных билдах для одного и того же документа не меняется хеш

Иначе капзда SEO)

2021-12-30 11:58 UTC, Krakazybik commented on website/open-graph-templates/config.json
> +  "outputDir": "assets/og",
> [`nitpick(подушню):`](https://conventionalcomments.org/) А для ru мб тоже локаль создавать?

у нас в доке не создаётся же для основной локали

2021-12-30 11:59 UTC, Krakazybik commented on website/open-graph-templates/config.json
> +  "outputDir": "assets/og",
Пруфы
![image](https://user-images.githubusercontent.com/1334019/147750082-fbf68d17-0a7d-4adf-a5d7-0509305665c7.png)

2021-12-30 12:00 UTC, azinit commented on website/src/shared/lib/open-graph-preview/index.js
> +export function OpenGraphPreview({ imgUrl }) {
[`praise:`](https://conventionalcomments.org/) Забыл кста отметить - здорово что к либе отнес!

2021-12-30 12:01 UTC, azinit commented on website/src/theme/DocItem/index.js
> +                }/assets/og/${hashFileName}.jpg`}
**Размышления дельные)**

Но тут такая штука, что нам где-то надо при этом хранить логику генерации imgUrl + логику генерации хеша

> Помнишь, писал про это уже на предыдущих итерациях?

И да, лепить еще одну абстракцию поверх `shared/lib/og` - тоже не дело. Поэтому кажется вполне легально расширить зону ответственности этого модуля, тем более что это напрямую к либе относится

> Либо же на крайний - эту логику в хук обернуть и в ту же либу положить, но уже оверинжинирингом немног попахивает

2021-12-30 12:03 UTC, azinit commented on website/open-graph-templates/config.json
> +  "outputDir": "assets/og",
> у нас в доке не создаётся же для основной локали

Печально если так)

Но я к тому, чтобы не было путанницы хотя бы для `og-img`

Чтобы было точно понятно к какой локали они относятся

Если прям сложно такое сделать то пофиг, забьем тогда

2021-12-30 12:04 UTC, azinit commented on website/open-graph-templates/config.json
> +  "outputDir": "assets/og",
> просто buildOutputDir тоже не явно получается, и я не смог придумать названия. :sorry:

Оке, давай тогда просто `"outputDir": "assets/og-img",` оставим

И на этом можно завершить этот тред)

2021-12-30 12:13 UTC, Krakazybik commented on website/open-graph-templates/config.json
> +  "outputDir": "assets/og",
> Если прям сложно такое сделать то пофиг, забьем тогда

Это не сложно, но, путь билда выдаёт нам сам докузаурус. я могу для основной локали определить кастомный, но оно тогда не будет вписываться в общуюю картину. Т.к. у докузауруса assets будет для основной локали в корне билда, а у нас появится дополнительный ru/assets/og.

Если нужно, то это совсем не сложно. Но я думаю нарушит, как вы там называете, "консистентность" :rofl:

2021-12-30 12:16 UTC, azinit commented on website/open-graph-templates/config.json
> +  "outputDir": "assets/og",
> Если нужно, то это совсем не сложно. Но я думаю нарушит, как вы там называете, "консистентность" 🤣

Оки, забьем тогда)

Если еще не сделал, то можем и `assets/og` оставить даже, чтоб было понятно к какой либе относится

2021-12-30 12:18 UTC, Krakazybik commented on website/src/theme/DocItem/index.js
> +                }/assets/og/${hashFileName}.jpg`}
> Хм, тоже верно по идее... Но я бы на всякий прям проверил - что при 2-3 разных билдах для одного и того же документа не меняется хеш
> 
> Иначе капзда SEO)

Конечно проверю. Я бы предложил написать интеграционные тесты, но боюсь тогда мы зарелизися в 2025 =))

2021-12-30 12:32 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
> +            // Center text using spaces.
> Ну вот убрать бы тогда мб)
> 
> По коммитам если что найдем, если надо будет

Я бы конечно как опшенс к текстовым слоям бы сделал, но давай уберём =))

2021-12-30 12:35 UTC, Krakazybik commented on website/src/shared/lib/open-graph-preview/index.js
> +export function OpenGraphPreview({ imgUrl }) {
OGHelmet не нравится, где Sword, shield и chest? вообще не понятно кто он такой и о чем речь. OGMeta гуд!

2021-12-30 12:36 UTC, Krakazybik commented on website/src/shared/lib/open-graph-preview/index.js
> +            <meta name="twitter:image" content={imgUrl} />
Думаю стоит в отдельный ишью вынести.

2021-12-30 13:00 UTC, azinit commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
> +            // Center text using spaces.
Ну из реализации можешь не убирать

Но конфиг точно бы попроще держать

2021-12-30 13:02 UTC, azinit commented on website/src/shared/lib/open-graph-preview/index.js
> +export function OpenGraphPreview({ imgUrl }) {
> OGHelmet не нравится, где Sword, shield и chest? вообще не понятно кто он такой и о чем речь.

Это по аналогии с этим)
https://www.npmjs.com/package/react-helmet

2021-12-30 13:02 UTC, azinit commented on website/src/shared/lib/open-graph-preview/index.js
> +            <meta name="twitter:image" content={imgUrl} />
Угу)

2021-12-31 19:46 UTC, Krakazybik commented on website/plugins/docusaurus-plugin-open-graph-image/font.js
>              options.fontSize = Math.trunc((fontSize * 0.9) / (width / widthLimit));
planned in #402

2022-01-08 11:06 UTC, azinit approved these changes
Спасибо что зарезолвил все комментарии, стало однозначно лучше ! 🚀

2022-01-08 11:06 UTC, azinit commented on website/plugins/docusaurus-plugin-og/index.js
> +        name: "docusaurus-plugin-og",
[`praise:`](https://conventionalcomments.org/) Стало лучше! 🚀

2022-01-08 11:06 UTC, azinit commented on website/docusaurus.config.js
> +    process.env.OG_EXP && DOCUSAURUS_PLUGIN_OG,
[`praise:`](https://conventionalcomments.org/) Красиво оформил!

2022-01-08 11:06 UTC, azinit commented on website/src/theme/DocItem/index.js
> +            process.env.OG_EXP && <OGMeta imgUrl={ogUrl} />
[`praise:`](https://conventionalcomments.org/) Стало сразу чище!

2022-01-08 11:06 UTC, azinit commented on website/src/theme/DocItem/index.js
> +import { OGMeta } from "@site/src/shared/lib/og-meta";
[`issue(non-blocking):`](https://conventionalcomments.org/) А потом тебе понадобится что-то помимо меты сложить связанное с OG, и придется переименовать либу)

2022-01-08 11:06 UTC, azinit commented on website/src/theme/DocItem/lib/index.js
> +}
[`thoughts:`](https://conventionalcomments.org/) В целом некрит, хотя я бы положил это в саму либу `og`

Но рядом с DocItem тоже пока неплохо смотриться

Лишь бы в других местах потом не пригодилось)

2022-01-08 11:06 UTC, azinit commented on website/src/theme/DocItem/index.js
> +            {isOGExperimental && <OGMeta imgUrl={ogUrl} />}
[`praise:`](https://conventionalcomments.org/) Йеее, стало лучше!

2022-01-08 15:58 UTC, Krakazybik commented on website/src/theme/DocItem/index.js
> +import { OGMeta } from "@site/src/shared/lib/og-meta";
@azinit Если не сложно, то хотелось бы пример, что может быть связано с OG плагином и быть не метой ? =) Я просто прикидывал в голове и ничего не смог придумать. Можно переименовать в `og` но оно будет размыто и не явно, я в принципе наверное даже соглашусь, что `og` лучше, но реально других кейсов кроме меты в плане взаимодействия с плагином я не вижу =)

2022-01-08 16:08 UTC, Krakazybik commented on website/src/theme/DocItem/lib/index.js
> +}
@azinit Как я думал, перед тем как сюда её засунуть. 
- _Может ли оно нам понадобиться в каком-либо другом месте?_ 
 **Нет. Оно жестко завязано через пропс метадата  у `DocItem`, который ни где в другом месте мы получить не сможем.**
- _Возможна ли вообще работа без плагина doc?_
**Нет. Опять же т.к. мы завязаны на `id` из `doc` плагина, не было бы у нас такой связи, `DocItem` бы у нас вообще не существовал.**

P.S. И да, я подозревал, что кто-то обратит внимание на расположение и кому-то оно не понравится =)

2022-01-09 09:45 UTC, azinit commented on website/src/theme/DocItem/index.js
> +import { OGMeta } from "@site/src/shared/lib/og-meta";
**Тут два момента кмк:**

1) Ты не можешь предсказать будущее и вряд ли знаешь, как будет дальше развиваться и использоваться твоя библиотека

2) По такой логике, тогда и плагин надо в "og-meta" переименовывать, но это кмк излишне переусложненный нейминг

2022-01-09 09:45 UTC, azinit commented on website/src/theme/DocItem/index.js
> +import { OGMeta } from "@site/src/shared/lib/og-meta";
Но в целом некрит, опять же)

2022-01-09 09:47 UTC, azinit commented on website/src/theme/DocItem/lib/index.js
> +}
Да, я понимаю примерно ход рассуждений)

Поэтому и чисто "мысли" и самому показалось, что так тоже ничего так смотрится

2022-01-09 10:10 UTC, Krakazybik commented on website/src/theme/DocItem/index.js
> +import { OGMeta } from "@site/src/shared/lib/og-meta";
> Но в целом некрит, опять же)

Я переименую, не вижу в этом проблемы.  Просто, как мне кажется, мы из понятного open-graph-preview, мы пришли в og, который лежит рядом с  ga в папке либ, и у меня остаётся чувство, что это, ну такое себе.

2022-01-09 10:13 UTC, azinit commented on website/src/theme/DocItem/index.js
> +import { OGMeta } from "@site/src/shared/lib/og-meta";
> мы пришли в og, который лежит рядом с ga в папке либ, и у меня остаётся чувство, что это, ну такое себе.

Тоже не вижу в этом проблемы, если это общепризнанные сокращения 🤔 

Мб "зал" что подскжет

@feature-sliced/core @feature-sliced/contributors

2022-01-09 11:01 UTC, Krakazybik commented on website/src/theme/DocItem/index.js
> +import { OGMeta } from "@site/src/shared/lib/og-meta";
> Тоже не вижу в этом проблемы, если это общепризнанные сокращения thinking

окай!) значит будет og =)

2022-01-11 13:19 UTC, azinit commented
@feature-sliced/core @feature-sliced/contributors гляньте пож
Уже старый PR достаточно

2022-01-11 16:35 UTC, Postamentovich approved these changes

2022-01-11 18:36 UTC, merged