docs(examples): add angular todo app example
feature-sliced/documentation pull request #406
Opened 2022-01-09 13:07 UTC by Affiction

## CHANGELOG

- Добавил пример Todo app реализовано с помощью Angular фреймворка (стек: Angular v13, nx, ngrx, Angular Material)

## Чеклист

- [ ] Если при работе с документацией потребовалось использовать **github-дискуссии, то стоит их прикрепить как see-also источники**
- [ ] Если PR связан с задачей, то необходимо проверить, что **все требования по задаче выполнены**
- [x] Перед тем, как отправлять изменения на ревью, **нужно ознакомиться с [CONTIBUTING-гайдлайнами](https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md)**
- [x] Перед тем, как отправлять изменения на ревью, **нужно провести self-review своих изменений**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дождаться CI-проверок**
- [ ] Перед тем, как отправлять изменения на ревью, **нужно дать краткое описание изменений**

2022-01-09 13:18 UTC, azinit commented
Выглядит мощно, спасибо!
Давай сегодня-завтра гляну само применение методологии в проекте, и если не будет критов - то вольем, хорошо?

2022-01-09 13:21 UTC, azinit commented
@all-contributors please add @Affiction for example

2022-01-09 13:23 UTC, Affiction commented
> Выглядит мощно, спасибо! Давай сегодня-завтра гляну само применение методологии в проекте, и если не будет критов - то вольем, хорошо?

Да, без проблем👍 
Вдруг чего, внесу правки. Возможно не до конца понял куда правильно выносить абстракции ангуляра (services, pipes etc.)

2022-01-17 22:21 UTC, azinit commented
@Affiction **Про пример помню - долго руки доходили, сорян)**
Проревьювил сам проект на выхах, выписал ключевые моменты - осталось в ревью оформить
(можно [тут ](https://github.com/feature-sliced/examples/discussions/17) следить за прогрессом)

2022-01-25 06:18 UTC, azinit requested changes
@Affiction Таки дошли руки доревьювить)
Вот тут в дискашне все описал, поправить криты хотя бы
(ну и если по остальному тоже отпишешься - то получится лучше передать в доке специфику ангуляра)

https://github.com/feature-sliced/examples/discussions/17#discussioncomment-2040483

2022-01-25 09:07 UTC, Affiction commented
@azinit Отлично) В течении недели подфиксаю и параллельно буду отписывать про специфичные вещи ангуляра

2022-01-27 01:43 UTC, azinit commented
> @azinit Отлично) В течении недели подфиксаю и параллельно буду отписывать про специфичные вещи ангуляра

Как подфиксишь то, что считаешь нужным - пингани/перезапроси ревью тут)

2022-01-28 01:09 UTC, Affiction commented
Подфиксал большую часть. [PR с фиксами. ](https://github.com/Affiction/angular-feature-sliced/pull/1)

2022-01-31 17:50 UTC, azinit commented
@Affiction стало значительно лучше, спасибо!)

2022-01-31 18:01 UTC, azinit approved these changes

2022-01-31 18:04 UTC, merged

2022-01-31 18:12 UTC, azinit commented
@Affiction красотень, спасибище, приходи еще 🔥 

![image](https://user-images.githubusercontent.com/42924400/151849426-bd91c142-87b4-4d1f-a695-57d7968825f5.png)