fix(intro): rewrite anglicisms in the Russian version
feature-sliced/documentation pull request #424
Opened 2022-01-25 09:27 UTC by illright

## CHANGELOG

- Rewrote uncommon anglicisms in the Introduction section to improve readability.

## Checklist

- [x] I reviewed **[CONTRIBUTING guidelines](https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md)**
- [x] I did a **[self-review of the changes](https://blog.beanbaginc.com/2014/12/01/practicing-effective-self-review/)**
- [x] I gave a **brief description of the changes**
- [x] I awaited for **CI checks**
- [x] I specified **related materials** if needed (discussion/issue/pull-request...)
- [x] **All requirements for the related issue are resolved** if issue exists

Closes #421

2022-01-25 13:32 UTC, RinAkaia requested changes

2022-01-25 13:32 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +- Предлагает разделять проект согласно [**единицам бизнеса**][ext-ubiq-lang]
Стало ещё непонятнее, то за единицы бизнеса такие 🤔

2022-01-25 13:32 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *можно переписать его с нуля без нежелательных последствий в других частях проекта*
Я бы сюда тогда ещё втиснула "слабопредсказуемых", раз мы выкинули значение неожиданности

2022-01-25 13:32 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *сохраняется баланс между соблюдением принципа `DRY` и возможности адаптировать модуль под разные цели*. При этом адаптация не влечет за собой засорение кода и замедление приложения и
>между соблюдениЕМ и возможностьЮ

Кто-то забыл просклонять при написании статьи, стоит поправить

>засорение кода

Стоит заменить чем-то более конкретным и однозначным

>не влечёт за собой замедление приложения

А вот это очень спорно, я бы не стала добавлять, ибо такие сильные заявления должны быть подкреплены хотя бы бэнчмарками, а у нас их пока нет

2022-01-25 14:41 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +- Предлагает разделять проект согласно [**единицам бизнеса**][ext-ubiq-lang]
Ну, откровенно говоря, мне и раньше не было особо понятно, что это за зверь. Однозначно стоит это переписать, но, возможно, в рамках новой задачи по прояснению тех. жаргона

2022-01-25 14:46 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *сохраняется баланс между соблюдением принципа `DRY` и возможности адаптировать модуль под разные цели*. При этом адаптация не влечет за собой засорение кода и замедление приложения и
Насчет замедления приложения – мне самому не нравится эта фраза, но это то, как лично я интерпретировал "оверхедные переопределения". Я бы вообще предложил это убрать.

Насчёт замены засорению кода – не очень понял, что именно ты хочешь видеть. Есть предложения?

2022-01-25 14:47 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *можно переписать его с нуля без нежелательных последствий в других частях проекта*
А стоит ли? Я боюсь сильно перегружать предложение, мне кажется, это слово не особо меняет его значение

2022-01-25 16:16 UTC, Krakazybik commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *сохраняется баланс между соблюдением принципа `DRY` и возможности адаптировать модуль под разные цели*. При этом адаптация не влечет за собой засорение кода и замедление приложения и
> как лично я интерпретировал "оверхедные переопределения"
Оверхедный - воспринимай примерно как с отрицательным КПД. На самом деле не знаю насколько стоит заменять такие слова, я лично не знаю к ним нормальных синонимов и они вроде как дают однозначное понятие.

2022-01-25 16:24 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *сохраняется баланс между соблюдением принципа `DRY` и возможности адаптировать модуль под разные цели*. При этом адаптация не влечет за собой засорение кода и замедление приложения и
Мне кажется, ситуация с этой вот цепочкой комментариев – прямой аргумент тому, чтоб исключить это слово из текста. Англицизмы тем и плохи, что люди имеют обыкновение понимать их по-разному. Так что я бы не согласился с тем, что слово "оверхедный" дает однозначное понятие.

Тут еще вот в чем вопрос – что изначально послужило мотивацией включить это словосочетание в текст? Есть ли примеры из других архитектур или каких-либо проектов, в которых существуют эти самые оверхедные переопределения? Это помогло бы четче сформулировать эту мысль.

2022-01-26 03:51 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +- Предлагает разделять проект согласно [**единицам бизнеса**][ext-ubiq-lang]
Давай тогда оставим "согласно доменной области"

Или "предметной", не суть важно

2022-01-26 03:52 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *можно переписать его с нуля без нежелательных последствий в других частях проекта*
Тут, боюсь, больше акцент был на "отсутствии предсказуемости", чем "нежелательности"

> "непредсказуемость" порой гораздо хуже, чем "нежелательность"

2022-01-26 03:56 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *сохраняется баланс между соблюдением принципа `DRY` и возможности адаптировать модуль под разные цели*. При этом адаптация не влечет за собой засорение кода и замедление приложения и
> Насчёт замены засорению кода – не очень понял, что именно ты хочешь видеть. Есть предложения?

Мб что-то типа "При этом адаптация не влечет за собой деунифицированности кода/логики" ? 🤔 

Хотя честно говоря я бы второе предложение тоже убрал, и просто вместо "оверхедности", упомянул "деунифицированность"

_Сам раздел еще будет возможность переписать к лучшему, а щас бы с англицизмами хотя бы разобраться_

2022-01-26 03:59 UTC, azinit approved these changes
В целом гуд, но правки от @RinAkaia внести бы

2022-01-26 03:59 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Ресурсы и дополнительные материалы, предоставленные сообществом"
[`praise:`](https://conventionalcomments.org/#labels) Стало лучше!

2022-01-26 11:45 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *сохраняется баланс между соблюдением принципа `DRY` и возможности адаптировать модуль под разные цели*. При этом адаптация не влечет за собой засорение кода и замедление приложения и
Тоже не очень понял, что подразумевается под _деунифицированностью_. Ну и не хочется использовать именно это слово, потому что это тоже англицизм.

Пока убрал это предложение вообще, если поможете понять (лучше на примере), что это предложение пыталось сказать, можем попробовать его перефразировать и вернуть.

2022-01-26 11:48 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +- Предлагает разделять проект согласно [**единицам бизнеса**][ext-ubiq-lang]
Поправил на "предметной области"

2022-01-26 11:49 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *можно переписать его с нуля без нежелательных последствий в других частях проекта*
В предложении выше (буквально на пару строчек выше :) ) увидел слово "непредвиденных", взял его оттуда и поставил сюда. Подойдет?

2022-01-26 12:06 UTC, Krakazybik commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *сохраняется баланс между соблюдением принципа `DRY` и возможности адаптировать модуль под разные цели*. При этом адаптация не влечет за собой засорение кода и замедление приложения и
Унифицированный - ну тут уже придирки, как мне кажется, номральное слово. Особо частво встречающееся слово в тех. документации. Даже времён СССР. Унифицированная деталь, например, деталь применяемая во многих местах. Допустим двигатель ВАЗ-2103 xD

2022-01-27 01:40 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Благодаря этому *можно переписать его с нуля без нежелательных последствий в других частях проекта*
Вполне кмк)

2022-01-27 05:09 UTC, RinAkaia approved these changes

2022-01-27 05:51 UTC, illright commented
@azinit @RinAkaia @Krakazybik готово к мерджу?

2022-01-27 07:25 UTC, merged

2022-01-27 07:26 UTC, azinit commented
@illright Спасибо тебе большое! 🚀