fix(intro): remove excessive text formatting, reorganize the text
feature-sliced/documentation pull request #428
Opened 2022-01-27 08:05 UTC by illright

## CHANGELOG

- Removed the formatting from the intro section that wasn't improving readability.
- Reorganized the benefits into a bullet list instead of two-line sections
- Renamed the "Обзор" heading to "Преимущества"

## Checklist

- [x] I reviewed **[CONTRIBUTING guidelines](https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md)**
- [x] I did a **[self-review of the changes](https://blog.beanbaginc.com/2014/12/01/practicing-effective-self-review/)**
- [x] I gave a **brief description of the changes**
- [x] I awaited for **CI checks**
- [x] I specified **related materials** if needed (discussion/issue/pull-request...)
- [x] **All requirements for the related issue are resolved** if issue exists

Closes #422

2022-01-27 08:25 UTC, Krakazybik commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** — это архитектурная методология для проектирования frontend-проектов. Она нацелена на разделение приложения согласно бизнес-логике и областям ответственности. Методология не
> проектирования frontend-проектов.

Как-то режет слух. Может подобрать какой-то синоним?  Например "построения"?

> и применима к любым frontend-проектам.

Кажется излешеством в текущем контексте.

2022-01-27 08:37 UTC, Krakazybik commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
Что-то по пунктуации.  И кажется, что "И поэтому, вместо того," звучит лучше и правильнее, чем "Поэтому вместо того".

2022-01-27 08:40 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** — это архитектурная методология для проектирования frontend-проектов. Она нацелена на разделение приложения согласно бизнес-логике и областям ответственности. Методология не
Согласен с этими замечаниями, но они немного не по теме данного ПРа. Мы с @azinit обсудили, что лучше всего работать над Введением маленькими сфокусированными изменениями. В перспективе планируется работать над формулировками, лучше будет перенести обсуждение этих моментов в тот ПР (который когда-нибудь будет :p)

2022-01-27 08:47 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
Уточни, пожалуйста, что именно по пунктуации? Главред, LanguageTool и Google Docs никаких замечаний не выделили.

Насчет "И поэтому, вместо того," – не соглашусь, мне больше нравится текущий вариант.

2022-01-27 08:59 UTC, Krakazybik commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** — это архитектурная методология для проектирования frontend-проектов. Она нацелена на разделение приложения согласно бизнес-логике и областям ответственности. Методология не
Ну я затрагивал только изменения, но да "проектирования frontend-проектов." действительно out-of-scope.

2022-01-27 09:10 UTC, Krakazybik commented
Если не сложно cкинь, пожалуйста, скрин =) Хоть посмотреть, чего на выходе получилось =)

2022-01-27 09:17 UTC, illright commented
Если честно, сложно :) я попытался поднять доку, когда делал прошлый ПР, но делал через [pnpm](pnpm.io) (у меня не установлен Yarn, не особо люблю его). Билд упал с ошибкой, рискну предположить, что где-то есть незадекларированная зависимость. 

Надо, наверное, CI настроить, чтоб билдил доку с ПРов. Могу этим тоже когда-нибудь заняться. А ещё с удовольствием переведу проект на pnpm, но это можно позже обсудить.

2022-01-27 09:41 UTC, Krakazybik commented
![Screenshot_20220127_124033](https://user-images.githubusercontent.com/1334019/151332887-4c142c51-9445-484c-bdc0-56040ffc50f8.png)


![Screenshot_20220127_124105](https://user-images.githubusercontent.com/1334019/151332956-6ed967f9-acd6-4e7c-a2dd-8e6a8d7c087c.png)

2022-01-27 10:12 UTC, illright commented
А что с английской версией страницы делать? Она, конечно, не входит в скоуп #422, но проблемы у нее идентичные, может быть, стоит захватить и ее?

2022-01-27 11:14 UTC, azinit commented
> А что с английской версией страницы делать? Она, конечно, не входит в скоуп #422, но проблемы у нее идентичные, может быть, стоит захватить и ее?

Думаю, следующими итерациями

Щас хотя бы что-то сносное на одном языке получить)

2022-01-27 12:11 UTC, RinAkaia commented
> Но, субъективно, Javascript + React выбиваются из общего стиля. Может их _JavaScript_ + _React_ ?

Думаю их вообще не нужно как-то выделять форматированием

2022-01-27 12:16 UTC, RinAkaia approved these changes

2022-01-27 12:16 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** — это архитектурная методология для проектирования frontend-проектов. Она нацелена на разделение приложения согласно бизнес-логике и областям ответственности. Методология не
> Feature Sliced

@azinit я потом ещё докопаюсь не раз к отсутствию дефиса 👿👿👿

2022-01-27 12:16 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
Пока вроде норм смотрится

2022-01-27 14:22 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** — это архитектурная методология для проектирования frontend-проектов. Она нацелена на разделение приложения согласно бизнес-логике и областям ответственности. Методология не
@RinAkaia вот как будет тема на барабане в кортиме, так и докопайся 😈😈😈

2022-01-27 14:31 UTC, azinit requested changes
Есть пару критов/сомнительных мест - но в целом оч даже гуд! 🔥

2022-01-27 14:31 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** — это архитектурная методология для проектирования frontend-проектов. Она нацелена на разделение приложения согласно бизнес-логике и областям ответственности. Методология не
[`nitpick(non-blocking)`](https://conventionalcomments.org/#labels)

Кмк, тут все же `Design` немного лишнее слово 🤔 
Т.е. оно неплохо дополняет, но *Feature Sliced* и так сам по себе полноценный

> Хотя зато так мб лучше будет считываться `FSD` сокращение, любимое @RinAkaia

2022-01-27 14:31 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  _SOLID, GRASP, DDD, Separation of Concerns, Vertical Slices, Public API, Isolation._
[`praise:`](https://conventionalcomments.org/#labels) Стало лучше!

2022-01-27 14:31 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Текущая версия документации приводит примеры на базе связки JavaScript + React.
[`praise:`](https://conventionalcomments.org/#labels) Огонь)

2022-01-27 14:31 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Термины, обозначенные на схеме, подробно описаны в разделе ["Концепции, Абстракции, Структура"][refs-basics].
[`praise:`](https://conventionalcomments.org/#labels) Хоть это даже и промежуточный вариант почти наверняка - оч здравая по компромиссу формулировка 👍

2022-01-27 14:31 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
[`praise`](https://conventionalcomments.org/#labels) Стало однозначно лучше!

2022-01-27 14:31 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +* **Явная бизнес-логика**
[`nitpick(critical)`](https://conventionalcomments.org/#labels) Ход интересный, но точно ли не сливается в доке по факту? 🤔 

<img width="760" alt="image" src="https://user-images.githubusercontent.com/42924400/151378411-203d6256-486d-486a-b655-aee56624baf1.png">

2022-01-27 14:31 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +* **Явная бизнес-логика**
[`nitpick:`](https://conventionalcomments.org/#labels) Ну и чтобы не путались bold-символы с li-символами - я бы все же оставил пункты списка с помощью тире 🤔

2022-01-27 14:31 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -*Но для фронтенда [крайне трудно найти][refs-motivation] устоявшиеся и конкретные подходы*
[`thoughts:`](https://conventionalcomments.org/#labels) Параллельно с чисткой формата, начинаем инквизицию текста 😏

2022-01-27 14:31 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -*Но для фронтенда [крайне трудно найти][refs-motivation] устоявшиеся и конкретные подходы*
[`suggestion:`](https://conventionalcomments.org/#labels) 

Я бы все же где-нибудь упомянул пункт с motivation в любой форме, чтобы было понятно где искать  нужную информацию
(да обилие ссылок - тоже плохо, как обсуждали - но если получится это сделать органично как в предложениях выше - я бы все же сохранил этот момент)

2022-01-27 14:34 UTC, azinit commented
@all-contributors please add @illright  for doc, content

2022-01-27 14:44 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +* **Явная бизнес-логика**
Про списки не очень понял. Ты хочешь, чтоб список был написан так?

* — **Фича**  
  Описание

2022-01-27 14:44 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +* **Явная бизнес-логика**
Так это GH так отображает 🤔 

Но оке, пока не сделали стендов под PR - поверю на слово))

2022-01-27 14:48 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -*Но для фронтенда [крайне трудно найти][refs-motivation] устоявшиеся и конкретные подходы*
`refs-motivation` осталась в тексте, так что если я правильно тебя понял, то это не проблема

2022-01-27 14:51 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** — это архитектурная методология для проектирования frontend-проектов. Она нацелена на разделение приложения согласно бизнес-логике и областям ответственности. Методология не
Мне кажется, тут вопрос брендинга. Если мы будем непостоянными в том, как мы называем методологию, бренд перестанет считываться, и все будут говорить, как им вздумается. Так что я бы оставил, раз мы хотим в конце прийти к FSD.

2022-01-27 14:53 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +* **Явная бизнес-логика**
А, сори, это я вторым коммитом убил эти переводы строк. Верну.

2022-01-27 16:01 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +* **Явная бизнес-логика**
> Про списки не очень понял. Ты хочешь, чтоб список был написан так?

Вот так:
```diff
- **Фича**
   Описание
```

2022-01-27 16:01 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -*Но для фронтенда [крайне трудно найти][refs-motivation] устоявшиеся и конкретные подходы*
А, точно)

2022-01-27 16:02 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** — это архитектурная методология для проектирования frontend-проектов. Она нацелена на разделение приложения согласно бизнес-логике и областям ответственности. Методология не
Ага, @RinAkaia оценит 🌚

2022-01-28 09:36 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +* **Явная бизнес-логика**
Вернул переводы строк и сделал список дефисами

2022-01-28 09:38 UTC, illright commented
Обратите, пожалуйста, внимание, я добавил в репо файл `.vscode/settings.json`. Не знаю, почему он был добавлен в игнор, такие файлы как раз и нужны для того, чтоб ставить принятые в проекте настройки, так что убрал из игнора. Скажите, ок ли это

2022-01-28 12:47 UTC, illright commented
\*sigh\* посквошите, пожалуйста, когда будете мерджить

2022-01-29 11:43 UTC, illright commented
@azinit посмотри еще раз, пожалуйста

2022-01-30 13:12 UTC, azinit commented
> Обратите, пожалуйста, внимание, я добавил в репо файл `.vscode/settings.json`. Не знаю, почему он был добавлен в игнор, такие файлы как раз и нужны для того, чтоб ставить принятые в проекте настройки, так что убрал из игнора. Скажите, ок ли это

По-моему до этого отреджектили подобный коммит от @RinAkaia по каким-то причинам 

Давай пробнем оставить, но если будут проблемы - возможно выпилим 🤔

2022-01-30 13:13 UTC, azinit commented
> *sigh* посквошите, пожалуйста, когда будете мерджить

Да ладно, нечего стесняться)

2022-01-30 13:15 UTC, azinit approved these changes

2022-01-30 13:15 UTC, merged

2022-01-30 16:14 UTC, RinAkaia commented
Так никаких проблем возникнуть и не может, это ж конфиги воркспэйса