EDITING-423: Purge redundant links and reorder the content
feature-sliced/documentation pull request #432
Opened 2022-02-01 09:19 UTC by illright

Много чего тут поменялось:
1. Убрал ссылки из первого параграфа.
   Причина в двух словах: _эти ссылки вели в никуда_. Для ссылки важно не только то, куда она ведет, но еще и откуда, чтоб при переходе по ней было понятно, какой информационный гэп заполняет эта ссылка.
2. Уточнил, куда ведет ссылка под диаграммой
3. Объединил разделы "Обзор" и "Преимущества", потому что ранее в разделе "Преимущества" была фраза "подобная структура", которая ни к чему не была присоединена.
4. Убрал большую часть карточек
   Они просто дублировали навигационный хедер, и не давали никаких советов о том, кому стоит переходить именно по этой карточке. Я считаю, что главным образом нужны только две карточки – на логическое продолжение страницы и на примеры.

Еще одна проблема: Docusaurus сам предоставляет переход на следующую страницу, поэтому эти карточки немного дублируют этот функционал, что не очень хорошо. Плюс там между ними есть виджет лайков-дизлайков документации, в ценности которого я тоже немного сомневаюсь.
<details>
<summary>Скриншот, где видно дублирование функционала</summary>
<img width="639" alt="дублирование функционала" src="https://user-images.githubusercontent.com/15035286/151941631-6ecb9027-fd82-49a1-966b-cae752898639.png">
</details>

<details>
<summary>Полностраничный скриншот результата</summary>

![полностраничный скриншот результата](https://user-images.githubusercontent.com/15035286/151941985-3e4e0640-ac5f-45d2-afcc-09994b019067.png)

</details>

Closes #423

2022-02-01 09:57 UTC, azinit commented
Лучше в след раз темплейт не убирай пож)

2022-02-01 10:07 UTC, azinit requested changes
Остальное позже гляну
Видно, что стало ссылок поменьше, и в целом Intro стал почище

Но по NavCards прям подискутировать надо))

2022-02-01 10:07 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
Стартанем тут тред)

> Еще одна проблема: Docusaurus сам предоставляет переход на следующую страницу, поэтому эти карточки немного дублируют этот функционал, что не очень хорошо

Там много раз обсуждали (@unordinarity @AlexandrHoroshih не дадут соврать), что хочется, чтобы человек, кому хочется перейти сразу "из места в карьер" (сразу к концепциям, или сразу к гайдам) - чтобы у такого человека была возможность снавигироваться из +- любого места доки
(т.к. сам по себе GetStarted и Intro достаточно общо описывают ситуацию для начального уровня погружения)

Поэтому переход-переходом дефолтный от Docusaurus - но там суть именно в том, чтобы человек еще в Intro понял, к какому разделу перейти при возникновении соответствующих вопросов

<img width="875" alt="image" src="https://user-images.githubusercontent.com/42924400/151948176-656d1c9b-5258-465c-9135-6bd564ae4341.png">

2022-02-01 10:07 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
>  Плюс там между ними есть виджет лайков-дизлайков документации, в ценности которого я тоже немного сомневаюсь.

Мы открыты к новым предложениям, но по состоянию доки, запросов от людей и общему фидбеку с метрик - пока не готовы такое удалять
(и в целом не считаем нужным)

2022-02-01 10:07 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -    tags={['Awesome','Команда', 'Участие в проекте']}
> Они просто дублировали навигационный хедер, и не давали никаких советов о том, кому стоит переходить именно по этой карточке. Я считаю, что главным образом нужны только две карточки – на логическое продолжение страницы и на примеры.

Опять же, не соглашусь что "дублирует docusaurus и надо оставить только ближайшие разделы"

Суть этой "карты навигации по разделам", как раз, чтобы человек сразу в Intro понимал - куда дальше идти по соответствующим запросам, как в том же Gatsby:

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/42924400/151948894-5e0f25d3-2d86-46c7-b2b3-241134cb58f7.png">

Офк можно забить на это и рассчитывать, что человек "методом тыка" найдет нужный раздел
Но это такой себе UX, лучше чтоб документация всячески способствовала удобной навигации пользователя кмк 🤔

2022-02-01 10:07 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -    tags={['Awesome','Команда', 'Участие в проекте']}
Возможно не стоит называть это "Что дальше", а заменить на что-то похожее к "Карта сайта" (+ мб сделать отдельной страницей даже)

На такое, кмк, еще готовы пойти - но тоже надо это сделать аккуратно, чтобы человек еще в Intro стало понятно куда перейти, если возникнут вопросы

2022-02-01 10:07 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -    tags={['Awesome','Команда', 'Участие в проекте']}
@RinAkaia @unordinarity @AlexandrHoroshih что скажете? 🤔

2022-02-01 10:16 UTC, illright commented
> Лучше в след раз темплейт не убирай пож)

Почему?

2022-02-01 10:22 UTC, azinit commented
> > Лучше в след раз темплейт не убирай пож)
> 
> Почему?

В темплейте подробно описано почему :)

<img width="996" alt="image" src="https://user-images.githubusercontent.com/42924400/151951551-c40e0880-c306-4b4a-9155-04db65902502.png">

2022-02-01 11:02 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
> пока не готовы такое удалять

Ок, без проблем

2022-02-01 11:18 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
> суть именно в том, чтобы человек еще в Intro понял, к какому разделу перейти при возникновении соответствующих вопросов

По своему опыту с этими карточками могу сказать, что по карточке не очень понятно, куда она меня приведет, и **смогу ли я решить свою задачу, если кликну на нее**. В доке Гетсби помимо заголовка (например, Reference) есть еще первые Х пунктов, благодаря чему можно понять общую направленность раздела, и может ли он помочь. Хочется иметь что-то похожее, но мне кажется, что карточками мы такое не вытянем

2022-02-01 11:21 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -    tags={['Awesome','Команда', 'Участие в проекте']}
> Возможно не стоит называть это "Что дальше", а заменить на что-то похожее к "Карта сайта" (+ мб сделать отдельной страницей даже)
>
> На такое, кмк, еще готовы пойти - но тоже надо это сделать аккуратно, чтобы человек еще в Intro стало понятно куда перейти, если возникнут вопросы

Не, мне кажется, название норм, и нет особой необходимости в отдельной странице. Что касается аккуратной реализации – мне кажется, прежде чем мы сможем делать качественные ссылки с интро, нам стоит причесать контент, на который мы ссылаемся. То есть, какие-то ссылки можно будет вернуть, но предпочел бы сделать это позже. Пока что с задачей навигации может вполне себе справиться навигационный хедер, как мне кажется.

2022-02-01 12:11 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
> В доке Гетсби помимо заголовка (например, Reference) есть еще первые Х пунктов, благодаря чему можно понять общую направленность раздела, и может ли он помочь. Хочется иметь что-то похожее, но мне кажется, что карточками мы такое не вытянем

Хех, а это что тогда?)

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/42924400/151966265-b006580e-ac7f-456c-a636-c75669902f35.png">

2022-02-01 12:16 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -    tags={['Awesome','Команда', 'Участие в проекте']}
Хмм, хз даже еще что дополнить к этому помимо написанного)

Кажется, что **даже при хорошем контенте но фиговой навигации (на какой фидбек на раз натыкались) - UX будет страдать**

Мб ребята из @feature-sliced/core что еще скажут 🤔

2022-02-01 12:32 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
> Хех, а это что тогда?)

Да, это я видел, просто у Гетсби это очень конкретные предметные штуки, на основании которых можно экстраполировать назначение всего раздела. Здесь это довольно абстрактные вещи, выглядят как тэги, я даже не сразу понял, с чем они соотносятся.

2022-02-01 12:35 UTC, azinit requested changes
Ознакомился внимательней
В целом оч даже гуд, но есть что улучшить
(пока прям "блокер" - это удаленные карточки в конце)

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
Вот тут кмк как раз тот случай, когда ссылки "заполняют гэп" где нужно

Особенно учитывая, что секцию с мотивацией в конец переносишь

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Термины, обозначенные на схеме, подробно описаны в разделе ["Концепции, Абстракции, Структура"][refs-basics].
Учитывая, что мы потом "расширим" раздел Overview - я бы всеж предложил ссылаться не на параграф страницы, а на всю статью - как это было до этого

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Термины, обозначенные на схеме, подробно описаны в разделе ["Концепции, Абстракции, Структура"][refs-basics].
Если смущает, то можно формулировку поменять - что по ссылке не только термины, но и в целом базовые основы методологии 🤔

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Предлагает разделять проект согласно [**предметной области**][ext-ubiq-lang]
Эххх, корежит конечно от того, что тут без ссылок сухой текст остается, но в целом понимаю ради чего)
Так что норм

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Основана на [**проверенных временем**][refs-motivation-why] практиках проектирования и концепциях
[`question:`](https://conventionalcomments.org/#labels) А чем фраза не понравилась?

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Основана на [**проверенных временем**][refs-motivation-why] практиках проектирования и концепциях
[`thoughts:`](https://conventionalcomments.org/#labels) Просто тут и по всей доке акцент именно на том - что в методологию отобраны только самые проверенные временем практики, а не просто "широкоизвестное что-попало"

_Т.к. `популярное` !== `хорошее`_

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  Код распределяется согласно области влияния (слой), предметной области (слайс) и техническому назначению (сегмент).
[`issue`](https://conventionalcomments.org/#labels) Звучит малясь упадочно)

[`suggestion`](https://conventionalcomments.org/#labels) Мб `Единообразие`? Или `Стандартизированность`? 🤔

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  Один слайс не может использовать другой слайс, расположенный на том же слое или на слоях выше.
[`issue`](https://conventionalcomments.org/#labels) Вот сам топил против того, чтобы использовать "жаргон" раньше времени, и тут на тебе))

[`suggestion`](https://conventionalcomments.org/#labels) Я бы все же тут более общо обозначал, что практики методологии склоняют к изолированности *компонентов архитектуры*

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  Один слайс не может использовать другой слайс, расположенный на том же слое или на слоях выше.
"Каждый компонент архитектуры имеет свое назначение и предсказуемый список зависимостей." - вот тут хорошо прям)

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    tags={['Базис', 'Быстрый старт', 'Мотивация']}
[`question`](https://conventionalcomments.org/#labels) А почему тут решил англицизм заюзать? 😏

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
[`praise`](https://conventionalcomments.org/#labels) Понимаю, к чему исправлял дескрипшн - местами стало действительно лучше

[`issue`](https://conventionalcomments.org/#labels) Но есть проблема, что теперь от GetStarted создается впечатление как "долго раздела", и вообще без намеков на "быстрое погружение"

[`suggestion:`](https://conventionalcomments.org/#labels) Я бы все же предложил попытаться как-то помержить старую и новую формулировку - чтобы  человек читая описание понимал  "О, да! Этот раздел поможет мне быстро пройтись по основам методологии и начать ее применять без лишнего вычитывания"

2022-02-01 12:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -[ext-ubiq-lang]: https://thedomaindrivendesign.io/developing-the-ubiquitous-language
[`praise:`](https://conventionalcomments.org/#labels) Круто, что удалось поудалять лишние ссылки!

2022-02-01 12:39 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -    tags={['Awesome','Команда', 'Участие в проекте']}
> даже при хорошем контенте но фиговой навигации (на какой фидбек на раз натыкались) - UX будет страдать

Это правда. Но я предлагаю не это, а сначала проработать структуру и контент, а потом, в обязательном порядке, навигацию.

Мне кажется, что если мы сделаем хорошую навигацию по образу хорошего контента, но при этом у нас все еще не будет хорошего контента, ущерб для пользователя будет больше. Навигация создаст ожидания, которые не поддержатся контентом. Напротив, если мы сначала переработаем контент и пока оставим просто хедерную навигацию, люди все равно найдут этот контент. Потом, имея хороший контент, мы проработаем навигацию и сделаем документацию конфеткой)

2022-02-01 12:56 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -    tags={['Awesome','Команда', 'Участие в проекте']}
Увы, не соглашусь)
Но боюсь тут обсуждение уже дело отдельного созвона 😏 

Подождем, что остальная кортима скажет

2022-02-01 12:57 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Предлагает разделять проект согласно [**предметной области**][ext-ubiq-lang]
А можешь попробовать описать, чего именно тебе не хватает в текущей версии? Возможно, те ссылки выполняли какую-то функцию, которая была тебе важна, но были просто не самым лучшим инструментом для этого? Если доберемся до этой самой функции, то может быть, сможем и понять, как ее по-другому выполнить

2022-02-01 13:28 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Предлагает разделять проект согласно [**предметной области**][ext-ubiq-lang]
Ты уже описывал как-то)

(не дословно) "Хочется, чтобы заявленные громкие фразы хоть чем-то подкреплялись - и ссылки вероятно этим и занимались"

но с другой стороны понятно - что они в самом начале могут сбить и свести не туда 🤔

2022-02-02 03:24 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
Ну и как минимум тот факт, что хоть где-то должна в Intro оставаться ссылка, ведущая на общую статью с мотивацией 🤔

2022-02-02 07:11 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
А зачем ссылка на статью с мотивацией? Я вижу её как большой монолог кортимы о ФСД, читать который лично мне не особо интересно, потому что у меня не возникали те вопросы, на которые эта статья дает ответы.

Также не чувствую, что в этот момент чтения текста Введения у меня возникает гэп, так что не очень понимаю, о каком гэпе говоришь именно ты. Можешь, пожалуйста, уточнить, какой именно информации не хватает этому тексту, по твоему мнению?

2022-02-02 07:13 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
> А зачем ссылка на статью с мотивацией? Я вижу её как большой монолог кортимы о ФСД, читать который лично мне не особо интересно, потому что у меня не возникали те вопросы, на которые эта статья дает ответы.

**Ну лично тебе - нет)**
А ~~"ретроградам"~~ сторонниками традиционных подходов и паттернов -  явно нужен ответ на вопрос "А методология - чтобы что?"
(и это не шутки, отдельный созвон в комьюнити чате проводили)

*И это не в обиду тебе, а просто подсвечивание факта того - что нужда в этой статье есть, и лучше дать о ней знать как можно раньше*

2022-02-02 07:16 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Термины, обозначенные на схеме, подробно описаны в разделе ["Концепции, Абстракции, Структура"][refs-basics].
Тут как раз мне бы хотелось не менять ни формулировку, ни параграф, потому что это одна из тех ссылок, которые реально контекстные. Человек увидел диаграмму с незнакомыми словами – человеку дали ссылку, где эти слова объясняются. Раньше ссылка была на страницу в целом, и нужно было скроллить через какие-то непонятные слова вроде _needs driven_ и _isolation_, чтоб получить ответ на конкретный вопрос: "да кто такой этот ваш слайс".

Опять же, хочется сделать акцент на том, что мы, кажется, по-разному воспринимаем ссылки в середине текста. Я воспринимаю такие ссылки как способ дать ответ на вопрос, а не как способ указать, что ещё нужно прочитать, потому что читатель еще не закончил читать это.

2022-02-02 07:18 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Предлагает разделять проект согласно [**предметной области**][ext-ubiq-lang]
> Хочется, чтобы заявленные громкие фразы хоть чем-то подкреплялись

А почему хочется именно здесь?) Эти фразы вполне подкрепляются остальной докой, и на мой взгляд, аргументации, как и всему, свое время

2022-02-02 07:18 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
> Можешь, пожалуйста, уточнить, какой именно информации не хватает этому тексту, по твоему мнению?

Давай по тексту пройдемся
(буду набрасывать вопросы, которые реально возникали у людей, а не выдуманные)

### "подходы переизобретаются с нуля"

*"Всмысле? Всегда были паттерны/SOLID/DRY. Есть и фреймворки, над тем же реакт*
*Может вы ими пользоваться не можете? Зачем ради этого методологию создавать?"*

### "пополняя проектные знания"

Тут скорее соглашусь, что ссылка может не нужна - но исключительно из-за того, что статья о проектных знаниях нуждается в доработке

А так вопрос скорее *"Смысл усложнять разработку - добавлением какой-то методологии? Почему не спасет стек, и как эти все знания шарить на команду?"*

### "к проблемам масштабируемости проекта и команды"

*"А как архитектура мне поможет масштабировать проект и команду? Точно ли это не история про раскладывание по папочкам? Что вообще называете хорошей архитектурой тогда?"*

--- 

И вот на каждый из этих вопросов - есть отдельная статья
Каждый из них - не имеет смысла разжевывать в введении, но как уже говорил - на них надо ссылаться, чтобы человек мог решить свой вопрос удобно навигируясь

2022-02-02 07:21 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Предлагает разделять проект согласно [**предметной области**][ext-ubiq-lang]
> А почему хочется именно здесь?) Эти фразы вполне подкрепляются остальной докой, и на мой взгляд, аргументации, как и всему, свое время

Но человек откуда знает это на старте?)
Если его заботит конкретный вопрос и у него есть способ сразу попасть на релевантную статью - это куда лучше чем "прочти доку от и до и тогда твой вопрос решится (может быть)"

Ну и тут опять тот же тезис: **"суть именно в том, чтобы человек еще в Intro понял, к какому разделу перейти при возникновении соответствующих вопросов"**

2022-02-02 07:22 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Основана на [**проверенных временем**][refs-motivation-why] практиках проектирования и концепциях
Эээээ, хз :D

Не знаю, просто как-то по-бумерски звучало. В целом, это можно и откатить, тут объективных причин нет

2022-02-02 07:23 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Термины, обозначенные на схеме, подробно описаны в разделе ["Концепции, Абстракции, Структура"][refs-basics].
Тогда я скорее поменял бы контекст - т.к. статья находится именно в том состоянии, что должна

Т.е. я бы отдельно добавил после "основ" кратко - что в методологии есть концепции обеспечивающие скейлинг/контролируемость и т.п. 

А так же вводим ряд абстракций - см. подробнее по ссылке

2022-02-02 07:23 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Термины, обозначенные на схеме, подробно описаны в разделе ["Концепции, Абстракции, Структура"][refs-basics].
@unordinarity мб будет что добавить

2022-02-02 07:24 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Основана на [**проверенных временем**][refs-motivation-why] практиках проектирования и концепциях
"От бумеров, для бумеров))"

~~Хотя еще большой вопрос, насколько много бумеров в кортиме~~

Но замысел такой формулировки объяснил
Если сможешь предложить альтернативу - готовы рассмотреть офк)

2022-02-02 07:26 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
Ну окей, я могу поверить в то, что есть большие скептики, чем я)

Просто тогда хочется оформить эту ссылку как целенаправленный "съезд с автомагистрали". Чтоб те, кто действительно задается такими вопросами, знали, что вот тут кроется ответ, а те, кто не задается, не испытывали Fear of Missing Out раньше времени.

Например, что-то в духе:

> В разделе ["Мотивация"](https://feature-sliced.design/docs/get-started/motivation) подробно описаны причины возникновения методологии, а также сравнение с другими подходами.

2022-02-02 07:30 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Предлагает разделять проект согласно [**предметной области**][ext-ubiq-lang]
Ну это правда, читатели могут не знать, что дока способна ответить на их вопрос. Здесь хочется предложить то же решение, как в треде через один выше, про мотивацию. Мы просто оставим съезд (можно даже тот же самый, что и в том треде), вместо того, чтоб встраивать ссылку в текст. 

Это дает нам возможность явно сообщить читателю, какой именно их вопрос мы предвидим, и что вот здесь есть ответ.

2022-02-02 07:31 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  Код распределяется согласно области влияния (слой), предметной области (слайс) и техническому назначению (сегмент).
Согласен, "единообразие" звучит поприятнее

2022-02-02 07:37 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  Один слайс не может использовать другой слайс, расположенный на том же слое или на слоях выше.
<details>
<summary>мем</summary>

![image](https://user-images.githubusercontent.com/15035286/152112038-fc34489d-0aef-438a-8a86-36989d256001.png)

</details>

Тут я позволил себе использовать слова "слайс" и "слой", так как на диаграмме уже понятно их пространственное отношение, даже если не до конца понятно, что именно это такое. Поэтому я не думаю, что у кого-то возникнут вопросы при чтении этого предложения (а если и возникнут, то мы оформили под диаграммой качественный съезд для того, чтоб ~раньше времени блен~ подробно ознакомиться с этими терминами.

Слово _компонент_ мне просто не понравилось своей абстрактностью. Нигде нет ответа на вопрос "а что такое компонент архитектуры?" Пусть уж лучше будет что-то знакомое, чтоб еще и постепенно погружать в терминологию, используемую по всей доке.

2022-02-02 07:40 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    tags={['Базис', 'Быстрый старт', 'Мотивация']}
А вот тут как раз пора вернуться к нашему обсуждению Гетсби)

Когда я правил англицизмы, я не очень понял, что это за `tags` такие на карточке, и воспринимал это просто как абстрактные слова, описывающие то, что можно найти в разделе. Когда я писал этот ПР, я понял, что это не просто рандомные слова, а заголовки в соответствующей странице, и нельзя их просто так изолированно переводить, не меняя заголовок на целевой странице. Это нужно для того, чтоб как у Гетсби, помочь пользователю ориентироваться на странице и понять, чего от нее ожидать, еще до перехода на нее.

_Тут конечно другая проблема в том, что по этим заголовкам не то, чтобы что-то понятно, но это мы еще успеем поправить_

2022-02-02 07:43 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
> вообще без намеков на "быстрое погружение"

Тут я начал потихоньку проталкивать свою идею о том, что на мой взгляд, не должно быть вообще никакого быстрого погружения) что Введение – это как раз и есть быстрое погружение.

Для того, чтоб аргументировать свою идею, предлагаю провести эксперимент, если есть возможность – дать человеку прочитать только введение и get-started, не переходя по ссылкам на концепции и гайды, и посмотреть, смогут ли они что-нибудь дельное написать на FSD. Если нет – быстрого погружения недостаточно, и надо его править (или вообще убрать, ыы). Я ставлю на то, что не смогут)

2022-02-02 07:47 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Термины, обозначенные на схеме, подробно описаны в разделе ["Концепции, Абстракции, Структура"][refs-basics].
> Тогда я скорее поменял бы контекст - т.к. статья находится именно в том состоянии, что должна
> 
> Т.е. я бы отдельно добавил после "основ" кратко - что в методологии есть концепции обеспечивающие скейлинг/контролируемость и т.п.
>
> А так же вводим ряд абстракций - см. подробнее по ссылке

Честно, не очень понял. Как бы это могло выглядеть в тексте доки?

2022-02-02 15:47 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Термины, обозначенные на схеме, подробно описаны в разделе ["Концепции, Абстракции, Структура"][refs-basics].
Тип такого

```md
### Основы

![пикча](...)

Для достижения расширяемой и контролируемой архитектуры, методология вводит ряд практик (концепций) и абстракций (см. [подробнее](ссыль-на-basics)
```

2022-02-02 15:48 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Термины, обозначенные на схеме, подробно описаны в разделе ["Концепции, Абстракции, Структура"][refs-basics].
Т.е. можно было бы оправдать тем, чтобы ссылать на конкретный раздел в basics, и "пользователь сам дочитает все остальное", но нет
И даже порядок секций в basics это не решит - там такой порядок изначально был заложен не просто так

Поэтому лучше ссылаться целиком на статью, а если смущает "недостаток контекстуальности" - то можно подправить контекст, чтобы было "достаточно контекстуально"

2022-02-02 15:50 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
Да, соглы - звучит оптимально)

Можно той же плашкой `:::info` от докузавра, либо сноской

2022-02-02 15:51 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
Только тут смущает, что только статья Мотивация упоминается, надо как-то "компактно" придумать так же для Архитектуры

2022-02-02 15:52 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Предлагает разделять проект согласно [**предметной области**][ext-ubiq-lang]
Да, здесь этот съезд даже будет лучше смотреться

Т.к. под конец статьи ближе к мотивации - ссылки куда консистентнее смотрятся, т.к. если человек перешел к этому разделу - наиболее вероятно, что основы он уже закрепил, и возможно имеет вопросы

2022-02-02 15:56 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  Один слайс не может использовать другой слайс, расположенный на том же слое или на слоях выше.
> Слово компонент мне просто не понравилось своей абстрактностью. Нигде нет ответа на вопрос "а что такое компонент архитектуры?"

**Ну камон)**

Для олдфагов - это привычный термин, при обозначении "модулей-частей системы в рамках system design" , а для ньюфагов - может максимум сложиться коллизия с UI-компонентами, но в целом ассоциация с модулями обычно тоже складывается

И "компонент" куда понятнее будет на этом этапе чем "абстрактный и непонятный слайс"
(не все люди будут достаточно рассматривать схему, чтобы читать дальше - если же дальнейший контент на странице к этому побуждает - это плохой UX. Это позволительно в get-started (и то с аккуратностью) и дальше , но не в Intro. Особенно учитывая, что большинство его будут читать по диагонали - но это не проблема людей, это просто специфика этого "ознакомительного" раздела )

2022-02-02 15:57 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  Один слайс не может использовать другой слайс, расположенный на том же слое или на слоях выше.
**И "компонент" куда понятнее будет на этом этапе чем "абстрактный и непонятный слайс"**
Не все люди будут достаточно рассматривать схему, чтобы читать дальше - если же дальнейший контент на странице к этому побуждает - это плохой UX. 

Это позволительно в get-started (и то с аккуратностью) и дальше , но не в Intro. Особенно учитывая, что большинство его будут читать по диагонали - но это не проблема людей, это просто специфика этого "ознакомительного" раздела

2022-02-02 15:59 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    tags={['Базис', 'Быстрый старт', 'Мотивация']}
Давай тогда уж лучше в самой странице "Базис" тайтл поменяем)
Проблемно чуть для метрик будет правда, но не так критично

"Основы" кмк тут как раз лучше суть передают, чем "Базис"
Они как бы подталкивают к тому, что "TLDR" тут
А "Базис" в русскоязычном варианте - может все что угодно значить

Если есть предложения получше - дай знать)

2022-02-02 16:00 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
> Для того, чтоб аргументировать свою идею, предлагаю провести эксперимент,

Было бы интересно, но даже при всех метриках что есть - у нас просто недостаточно инфровых и человеческих ресурсах, чтобы грамотно это отследить)

Причем тут еще много других факторов, которые чистоту экспа могут подпортить

2022-02-02 16:10 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
## Ну, были оч разные варианты)

Если есть предложения получше - feel free поделиться)
(но это не повод их удалять сами карточки прям щас)

2022-02-02 16:10 UTC, azinit commented
@RinAkaia @unordinarity @AlexandrHoroshih вы там где?)

2022-02-02 17:12 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
Хорошо, карточки можно вернуть. Я все ещё ими не особо доволен, но текущему разделению страниц они, видимо, все-таки идут на пользу. Вернемся к вопросу карточек, когда раскопаем остальные страницы)

2022-02-02 17:15 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
## Да, все же стоит учитывать - что за один этот PR мы intro не переделаем)

Мб даже через 2-3 PR удалим эти карточки, но надо обсудить еще отдельно этот вопрос

> Круто, что удается часть новых идей твоих пропихнуть уже здесь
>
> Но сам видишь, к чему привело "чуть больше чем удаление ссылок"))

2022-02-02 18:48 UTC, RinAkaia approved these changes

2022-02-03 11:13 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
> Но есть проблема, что теперь от GetStarted создается впечатление как "долго раздела", и вообще без намеков на "быстрое погружение"

Если просто в изоляции посмотреть на раздел Get Started, то лично мне он и не кажется сильно быстрым. Там есть три блока:
* Базис – он быстрый, его я назвал туром по основным понятиям. Имхо, идея быстроты все еще прослеживается в таком определении.
* Быстрый старт – очень большое по моим субъективным читательским меркам чтиво, еще и про Реакт. Я, по-моему, так ни разу полностью этот текст не осилил. Я назвал это "подробным разбором", потому что имхо это так и есть
* Памятка по декомпозиции – полезно и быстро, но сложно описать словами, так что опустил в описании

По сути, мне кажется, что предложенная мной формулировка чуть более честно выражает контент раздела Get Started. Она несет определенно меньше смысла "быстроты", но, на мой взгляд, оно и к лучшему, по крайней мере, пока мы не упростим "Быстрый старт".

P.S. Страница "Быстрый старт" с разделом "Быстрый старт" – немного путающее явление, но это оффтоп, просто сейчас заметил

2022-02-03 11:20 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  Один слайс не может использовать другой слайс, расположенный на том же слое или на слоях выше.
Предлагаю пока вернуть _Компонент_ и завести задачку на переработку этого параграфа в целом. Как мне кажется, одной диаграммы очень недостаточно, какой бы классной ее там в #178 не сделали

2022-02-03 11:45 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Основана на [**проверенных временем**][refs-motivation-why] практиках проектирования и концепциях
Откатил

2022-02-03 11:52 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
<details><summary>Сделал вот такие съезды</summary><img width="651" alt="preview of rollback" src="https://user-images.githubusercontent.com/15035286/152337581-c52be1ac-9004-406a-9343-47db99bd30b6.png"></details>

2022-02-03 11:53 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
Вернул карточки

2022-02-03 11:54 UTC, illright commented
@azinit порезолви, пожалуйста, треды, в которых достигнут консенсус, а то голова уже идет кругом)

2022-02-03 18:29 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
**Громоздко и отвлекающе малясь((**

Мыж вродь наоборот хотели, чтобы человек "не спотыкался при прочтении"
А тут при здравой идее - реализация уж "слишком явно бьет в читателя" 🤔 

Мб получится как-то компактнее это описать? 
(кажется даже под сноску засунуть тоже не поможет....)

2022-02-03 18:34 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
Ну, при таком подходе можно сразу закрывать доку и методологию)
До тех пор, пока "Быстрый старт" не станет действительно невероятно быстрым 😏

2022-02-03 18:34 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
**Повторюсь - это должно обсуждаться точно не в рамках этого PR**

(и куча длиннющих похожих тредов - тому подтверждение 🤷‍♂️ )

Повторюсь:

> Предлагаю отложить это до созвона с @unordinarity
>
> Надо сначала совместно обсудить, что ожидаем от каждого раздела

2022-02-03 18:36 UTC, azinit commented
> @azinit порезолви, пожалуйста, треды, в которых достигнут консенсус, а то голова уже идет кругом)

Порезолвил))

2022-02-09 03:37 UTC, azinit commented
@illright Мб добьем и вольем? Вроде по этому PR чуть чуть осталось 🤔 
(в рамках задачи и замечаний)

2022-02-09 05:21 UTC, illright commented
Прямо сейчас мне немного не до этого, горит парочка других вещей. В ближайшие дни вернусь

2022-02-13 14:27 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
Мне кажется, что то, спотыкается читатель при прочтении или нет, зависит не от размера текста, а от вопросов, которые возникают в голове по мере чтения.

Мне кажется, что такой способ съездов лучше, чем инлайн-ссылки в тексте, потому что здесь читателю явно дают понять, почему ссылка здесь находится. 

Как говорили в диатаксисе (да, теперь я буду их цитировать :D): _"a user can skim rapidly over what’s unnecessary, but if they need something and it’s not there, you risk losing them altogether"_. Главное тут — дать понять, что хочет сказать ссылка, чтоб ее можно было с уверенностью проскипать, если она не нужна.

2022-02-13 14:33 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Термины, обозначенные на схеме, подробно описаны в разделе ["Концепции, Абстракции, Структура"][refs-basics].
Я не хочу делать ссылку на всю страницу здесь, более того, я бы даже не хотел, чтоб читатели читали на линкнутой странице что-то больше, чем тот заголовок, на который я им указал. Причина тут такова — я не рассматриваю эту конкретную ссылку как полноценный переход на ту страницу. Она скорее играет роль _peek-а_ для любопытных, но большинство читателей должно дойти до этой страницы позже.

Поинт: я согласен с важностью всего контента, что находится на линкнутой странице, но ему придет его время. Надо дать пользователю дочитать одну страницу, прежде чем предлагать к прочтению целую другую.

2022-02-13 14:39 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  Один слайс не может использовать другой слайс, расположенный на том же слое или на слоях выше.
Из-за того, что я убрал один из буллет-поинтов и смерджил его смысл в другие, я не вижу тут ни чистого способа откатить изменения, ни заменить термины "слой" и "слайс". Если есть конкретные предложения, готов рассмотреть.

Но стоит сказать, что я не согласен с тем, что этот кусок доки представляет собой плохой UX

2022-02-13 14:40 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    tags={['Базис', 'Быстрый старт', 'Мотивация']}
Поправил, проверь

2022-02-13 14:41 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
По этому треду будем что-то менять?

2022-02-13 18:34 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Обычно, подходы построения архитектуры фронтенда от проекта к проекту [переизобретаются с нуля][refs-motivation], пополняя тем самым ["проектные знания"][refs-knowledge]. При этом, неверно принятые р
Именно тут - ОК, но думаю еще похоливарим потом))

2022-02-13 18:35 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    tags={['Базис', 'Быстрый старт', 'Мотивация']}
Топчик, спасибо!

2022-02-13 18:36 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -Термины, обозначенные на схеме, подробно описаны в разделе ["Концепции, Абстракции, Структура"][refs-basics].
ОК, давай так попробуем оставить)))

2022-02-13 18:40 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Предлагает разделять проект согласно [**предметной области**][ext-ubiq-lang]
@illright Оке, можешь добавить потом если считаешь нужным

Но в целом повторюсь - некрит вообще)

2022-02-13 18:46 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  Один слайс не может использовать другой слайс, расположенный на том же слое или на слоях выше.
Щас отпишу отдельно, т.к. хочется уже поскорей влить PR)

2022-02-13 18:47 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +    description="Тур по основным понятиям и структуре, а также подробный разбор проекта на React"
Оставим пока как пушишь, но теперь ты знаешь какой ценой это дается))

(лучше все же отдельными итерациями такие радикальные изменения предлагать)

2022-02-13 18:59 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +  Один модуль не может использовать другой модуль, расположенный на том же слое или на слоях выше.
Вынужденная мера, исключительно чтобы поскорей закрыть PR
(лучше до такого не доводить)

Если есть несогласие, то предлагаю на некст итерациях обсудить 🤔 

<details>
<summary>А зачем? (не для холиваров)</summary>

1. **Я/МЫ Слайс** 
     Я почти уговорил себя, чтобы поскорее закрыть PR - но так резало это "слайс" в месте, где у человека должен быть ответ на вопрос "А в чем ваше преимущество? Как ваш способ связывать модулей может улучшить ситуацию?"

    И тут мы такие "чувак, мы тут слайсеры, у нас нет слова "модуль",  онли "слайс"

    Это очень отбивает кмк
  
    ![image](https://user-images.githubusercontent.com/42924400/153770203-2028c3c9-1740-408f-bc30-a6ef71c2c18b.png)
2. **Too Confused**
    Также заметил, что при "рефакторинге и мердже" сильно сбился изначальный смысл абзацев, так что свапнул предложения "ближе к канону"
     (можем в дальнейшем, опять же, обсудить твои предложения)

      ![image](https://user-images.githubusercontent.com/42924400/153770329-e4165b38-007f-4f4b-b0ec-7ff82a51944f.png)

</details>

2022-02-13 19:00 UTC, merged

2022-02-13 19:01 UTC, azinit commented
Спасибо отдельно, что вносил правки, даже когда не до конца был согласен!

2022-02-13 19:04 UTC, azinit commented
@all-contributors please add @illright for ideas