Remove the checklist to make the PR template friendlier
feature-sliced/documentation pull request #434
Opened 2022-02-01 12:29 UTC by illright

## CHANGELOG

- Removed the checklist from the template
- Removed CAPS from the Changelog heading
- Sprinkled in some emojis and lightened up the language

## Checklist

- [x] I reviewed **[CONTRIBUTING guidelines](https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md)**
- [x] I did a **[self-review of the changes](https://blog.beanbaginc.com/2014/12/01/practicing-effective-self-review/)**
- [x] I gave a **brief description of the changes**
- [x] I awaited for **CI checks**
- [x] I specified **related materials** if needed (discussion/issue/pull-request...)
- [x] **All requirements for the related issue are resolved** if issue exists

---

## Reasoning

1. Removing CAPS from the Changelog
   Looks calmer and more consistent with the other heading (even though I removed the other one)
2. Removing the sample list that says "Added smth, fixed smth"
   It gets in the way because it has to be deleted/rewritten. The only benefit I see from it is to teach Markdown lists, but I don't think we should make effort towards that.  
   **Proposed solution**: Mention in the comment that lists work best.
3. Removing the checklist
   I moved all of the points of the checklist into other places which I believe to be more appropriate.
   
   1. Contributing guidelines
      Moved that into a P.S. comment because it is mostly useful to first-time contributors.
   2. Self-review
      Moved that into a P.S. comment too, and made it friendlier.
   3. Brief description
      This is already covered by the first comment, so I just removed it.
   4. CI checks
      The CI checks aren't started until the PR is created, this requirement simply can't be fulfilled. Removed it completely, the CI checks are hard not to notice, GitHub does a wonderful job at that.
   5. Related materials and requirements
      Moved to the description comment.

## Preview

When rendered, it's just a heading. Here's how it looks:

> ## Changelog

That's good because it gives more focus to what's actually written by the author of a PR. 

And here's what it looks like for contributors in the editor:

```
# Changelog

```

2022-02-01 12:36 UTC, azinit commented
Да можно было и на русском описать причины ))

2022-02-01 12:53 UTC, azinit requested changes
В целом основные мысли высказал
- Местами стало действительно лучше
- Где-то хочется сильно спорить, но готовы к компроимссным решениям

Мб @feature-sliced/core @feature-sliced/contributors еще что скажут 🤔

2022-02-01 12:53 UTC, azinit commented on .github/pull_request_template.md
> +# Changelog
Стало лучше, но чет h2 резко стал h1)

2022-02-01 12:53 UTC, azinit commented on .github/pull_request_template.md
> +-->
Тут стало значительно лучше, однозначно топ)

2022-02-01 12:53 UTC, azinit commented on .github/pull_request_template.md
> +-->
## Теперь мысли по "отказу" от чеклиста))

Такой комментарий оч "дружелюбен" к контрибьюторам, и в целом я понимаю почему так расставлены новые акценты

**Но со стороны кортимы при ревью уже много раз были проблемы, что люди:**
- Не заполняют описание (даже если не желали зла, а просто "забыли" или отписали потом в комментарии отдельном)
- Если берутся задачу - выполняют не все заявленные требования
   (и если ревьювить будет человек, который не захотел погружаться в задачу - получится по итогу халтура)
- Не указывают related ишью/дискашн, и приходится прикреплять самому
   (без этой орг части редко когда обходится - но хочется хотя бы минимум, если человек решает вопрос по задаче/дискашну)
- Присылают толстенные PR без каких либо комментариев к сложным частям
   (хотя тут куда практичнее делить такие PR на более мелкие)

2022-02-01 12:53 UTC, azinit commented on .github/pull_request_template.md
> +-->
## По итогу?

Предлагаю компромиссное решение, т.к. комментарий действительно написан на славу

### Мое "да"

- **Удалить пункт про CI** - да, давай, т.к. для новых контрибьюторов все равно вручную приходится чекать
(да и оно не вольется без соответствующих прав)
- **Видоизменить self-review** - да, я бы тут отдельно добавил, чтоб люди изначально не делали слишком больших PR, а лучше делали по частям (для их же блага)
    Тут еще можно подумать, насколько стоит это инфорсить среди всего комьюнити, т.к. увы разработчиков рили сложно "заставить" как либо писать подобные комменты
    
### Мое "нет" 

Чеклист хотя бы в базовом виде я бы все же оставил
Т.к. комменты люди будут тупо игнорить, при всей их "дружелюбности"
*(сам наверняка замечал, что когда тебя заставляют явно прожать пункты чеклиста - ты чувствуешь бОльшую ответственность за свой PR, чем если бы это был обычный коммент)*

И хоть ты "десятый раз будешь контрибьютить" - но проставляя "галки", ты  может местами внутри чувствуешь легкое отвращение
Но вместе с этим, как уже писал, ты явно даешь понять кортиме, что тебе не все равно на принятые порядки и ты ценишь время ревьюверов тоже, как и мы ценим время авторов
(а когда люди (не только ты) удаляют постоянно темплейт (что часто бывает, особенно в обычной разработке) - то привет разрухе и неуважению конвенций)

2022-02-01 12:55 UTC, azinit commented on .github/pull_request_template.md
> +# Changelog
А, теперь увидел, что ты чеклист полностью удалил)

Но про чеклист написал ниже 👀

2022-02-01 18:38 UTC, Krakazybik commented
Выглядит немного грустно, да, мотивируеющие комментарии это круто, но как мне кажется весь флоу будет таким =>
Создал ПР, бегло глянул что там закоменчено, удалил, и остался с Changelog и уже не помнишь о чем там и как оформлять. Про какие там гайды говорилось и чего мне теперь делать? Как мне кажется, шаблон есть для того, чтоб:
- Стандартизировать как-то входящие ПР.
- Помочь контрибьютерам и ревьюерам
Кмк, когда у тебя заполнен шаблон и есть банальные 
```
### Описание
Добавлено/Исправлено:

### Чеклист

### Ссылки

```
всё же живётся проще, и тем и другим, у тебя есть наглядное пособие по оформлению, у ревьюера есть однотипный ПР, в котором он привык ориентироваться. Про галки "добавить", "проверить", "ознакомиться" в чеклисте, я уже и не говорю. Галка наводит на мысль, что оно кому-то важно, и "наверное схожу почитаю".

2022-02-02 07:01 UTC, illright commented
Понимаю вашу точку зрения, но не очень разделяю. На мой взгляд, когда шаблон написан комментариями, это как раз плюсик в пользу того, чтоб их не удалять – все равно они не будут засорять итоговый рендер. На мой взгляд, если и иметь чеклист, то ему место в `CONTRIBUTING.md`, а не в шаблоне ПРа. Насчет того, что темплейт предлагает определенную структуру – я, если честно, не вижу, как можно предложить хорошую структуру, которая подойдет для описания любого ПРа. 

- Заголовок **Changelog** – согласен, полезно
- Заголовок **Чеклист** – я уже говорил про чеклист
- Заголовок **Ссылки** – лично я бы туда писать не стал, даже если у меня есть ссылки, а вместо этого встроил ссылку в текст, там где она контекстна. Например:  
   _Я оформил этот ПР согласно [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)_

Ниже то, что я думаю про чеклист, выраженное честными эмоциями. Я написал их насколько можно без наездов, но будьте готовы к тому, что внутри это может восприняться как атака. Я не вкладывал в этот текст атакующий смысл, мне просто хотелось донести то, что я чувствую.

<details>
<summary>Ахтунг, эмоции!</summary>

> Галка наводит на мысль, что оно кому-то важно, и "наверное схожу почитаю".

> И хоть ты "десятый раз будешь контрибьютить" - но проставляя "галки", ты может местами внутри чувствуешь легкое отвращение

Лично меня эти галки наводят на мысль "боже, да какая разница, я умею писать нормальные ПРы без напоминаний пойти сделать селф-ревью, выполнение которого они все равно не смогут проверить". И это не _легкое отвращение_, для меня это довольно сильный раздражитель, потому что в нем я читаю упрек себе, а не дружелюбие и просьбу соблюдать порядки. В нем я читаю желание контролировать меня моей же совестью, хотя это должно оставаться моим правом.

Я понимаю вашу точку зрения, когда вы голосуете за чеклист – я понимаю, насколько больно получать некачественные ПРы. И мне хочется дать кортиме понять, что мне не плевать на ваши порядки, качественным ПРом, понятным оформлением и описанием всех причин своих изменений, а не галочек для галочки (no pun intended). 

> а когда люди (не только ты) удаляют постоянно темплейт

то лично для меня это красный флаг, что темплейт не работает

</details>

2022-02-02 07:07 UTC, azinit commented
Ждем, что еще @feature-sliced/core и @feature-sliced/contributors скажут)

2022-02-02 17:41 UTC, AlexandrHoroshih commented
Предлагаю убрать чеклист в пользу развернутых дружелюбных комментариев в темплейте. 
Как минимум, в порядке эксперимента - вернуть чеклист, если комментарии не помогут, всегда успеем.

Кажется, не очень круто, когда адекватные контрибьюторы чувствуют, что это
> желание контролировать меня моей же совестью

Со стороны своего опыта скажу, что я обычно не вычищаю шаблон ишью или пр, если он там есть - так проще, собственно, описать что и зачем.
Поэтому согласен с @Krakazybik по поводу того, что хорошая структура шаблона поможет.

Да, универсальную структуру придумать сложно, но у каждого ПР есть как минимум две части:
- Причина: проблема или задача, которая в нем (частично или целиком) закрывается
- Непосредственные изменения

Эти части и предлагаю внести в шаблон - ниже мой вариант на скорую руку, не претендует на окончательную истину
```
## Scope (или Background, или Reasoning)
<!-- 
  Briefly describe what problem this PR is solving. 
  It will be awesome, if you mention related issues, discussions, etc.
  
  If there is a issue that your PR closes, just write "Closes #ISSUE_NUMBER" - e.g. "Closes #42".
  That will automatically close that issue, once PR is merged.
  Please make sure to address all parts of the issue if you write that!
-->

## Changelog
<!-- 
  Briefly describe the proposed changes below. 
  Numbered lists work best. 
  If you add 📷 screenshots or 🎞️ screencasts, you'll be our hero.

  If these changes were previously discussed in an issue or discussion,
  please, leave a reference to it 🔖.
-->


<!-- 
  Hi from the Feature Sliced Design core team! 👋

  Thank you for taking the time to contribute.
  We have a set of guidelines for contibutors that you might want to read:

    https://github.com/feature-sliced/documentation/blob/master/CONTRIBUTING.md

  We encourage self-reviewing the changes before submitting a PR ✅. 
  Here's a nice article that has some pro-tips:

    https://blog.beanbaginc.com/2014/12/01/practicing-effective-self-review/
-->
```

Что думаете?

2022-02-02 17:48 UTC, illright commented
Мне нравится :) 
Я бы использовал слово Background в первом заголовке, оно ощущается более применимым в общем случае

2022-02-02 18:45 UTC, AlexandrHoroshih commented on .github/pull_request_template.md
> +  If you add 📷 screenshots or 🎞️ screencasts, you'll be our hero.
@illright
Сможешь ли тогда (если есть время и желание), в рамках этого ПР, донести разбиение шаблона на условные"Background" и "Changelog"?

2022-02-02 19:01 UTC, illright commented on .github/pull_request_template.md
> +  If you add 📷 screenshots or 🎞️ screencasts, you'll be our hero.
Да, завтра внесу правки

2022-02-03 11:04 UTC, illright commented on .github/pull_request_template.md
> +  If you add 📷 screenshots or 🎞️ screencasts, you'll be our hero.
Готово

2022-02-03 18:03 UTC, azinit commented on .github/pull_request_template.md
> +-->
@illright @AlexandrHoroshih Кста, раз уж оставляем коммент - то мб поднять его на самый вверх?

Как будто бы его контрибьютор в первую очередь должен видеть, не? 🤔

2022-02-03 18:11 UTC, illright commented on .github/pull_request_template.md
> +-->
Не, специально убрал его вниз. Новые контрибьюторы обратят внимание благодаря эмоджикам + дружелюбной первой строчке + успеху первых двух блоков, а опытным контрибьюторам это не будет мешать

2022-02-03 18:17 UTC, azinit commented on .github/pull_request_template.md
> +-->
Не со всеми доводами согласен, но да ладно)

По смотрим как пойдет

2022-02-03 18:17 UTC, azinit commented on .github/pull_request_template.md
> +-->
Спасиб что нашел время на это все!

2022-02-03 18:17 UTC, azinit approved these changes

2022-02-03 18:17 UTC, merged