fix(intro): rewrite the summary paragraph
feature-sliced/documentation pull request #462
Opened 2022-02-14 19:27 UTC by illright

## Background

Closes #439 

## Changelog

Переписал первую секцию на странице "Введение".

На что направлены изменения:
- сделать текст проще для чтения, _приземлив_ немного язык
- устранить повторяющуюся информацию (например, в буллет-списке было частичное повторение материала из первого абзаца)
- дать введение для буллет-списка (а то он выглядел как просто набрасывание вещей, которые хочется сказать, но некуда вставить)

P.S. изменения не особо значительные, потому что хочется по итогам каждого такого ПРа получать что-то готовое. В переписывании дальнейшних секций, возможно, что-то будет убрано отсюда.

<details>
<summary>Вот как это выглядит</summary>

<img width="654" alt="image" src="https://user-images.githubusercontent.com/15035286/153932508-089a11eb-d454-4f1d-8f4d-1c241d1bf848.png">

</details>

2022-02-14 21:10 UTC, azinit approved these changes
> изменения не особо значительные, потому что хочется по итогам каждого такого ПРа получать что-то готовое. В переписывании дальнейшних секций, возможно, что-то будет убрано отсюда.

**Все идеально нарезано в PR)**
Прям ничего лишнего, буквально 🔥 
~~(даже не придерешься)~~

2022-02-14 21:10 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
[`thoughts(non-blocking:`](https://conventionalcomments.org/) Хм, а мне [прошлый](https://user-images.githubusercontent.com/42924400/153946414-55217026-d5bb-4f47-ae82-7ac9daac056f.png) вариант "по организации кода" из твоего драфта больше зашел)

Как будто больше серьезности чтоль в этой фразе)

А то многие FSD, увы, и воспринимают как "раскладывание по папочкам" - но все же это чуть бОльшее)

2022-02-14 21:10 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
[`suggestion(to-improve):`](https://conventionalcomments.org/) Ну и еще бы предложил добавить что-нибудь про "нарезку/дробление сложной логики", т.к. FSD тоже на это нацелен, а не только на организацию кода

(либо же мб это будет в других параграфах, но кажется и в хедере вполне себе смотрится 🤔 )

2022-02-14 21:10 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Обеспечивает **понятность, контролируемость и адаптивность** архитектуры
[`thoughts:`](https://conventionalcomments.org/) Надеюсь тема "понятности/контролируемости/адаптивности" кодобазы будет раскрыта в других параграфах))

2022-02-14 21:10 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Методология не привязана к конкретному стеку технологий и применима к любым frontend-проектам. Здесь есть примеры на JavaScript + React, но FSD успешно применяется и с другими стеками (см. [примеры п
[`praise:`](https://conventionalcomments.org/) Огонь!

2022-02-15 01:37 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Методология не привязана к конкретному стеку технологий и применима к любым frontend-проектам. Здесь есть примеры на JavaScript + React, но FSD успешно применяется и с другими стеками (см. [примеры п
~~здесь есть примеры на~~

документация содержит примеры реализации на

2022-02-15 01:40 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Методология не привязана к конкретному стеку технологий и применима к любым frontend-проектам. Здесь есть примеры на JavaScript + React, но FSD успешно применяется и с другими стеками (см. [примеры п
~~применяется и с другими стеками~~

применяется и к другим комбинациям

2022-02-15 01:43 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
~~о том, куда класть код~~

о том, как структурировать код

2022-02-15 02:13 UTC, RinAkaia requested changes

2022-02-15 02:13 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Методология не привязана к конкретному стеку технологий и применима к любым frontend-проектам. Здесь есть примеры на JavaScript + React, но FSD успешно применяется и с другими стеками (см. [примеры п
```suggestion
Методология не привязана к конкретному стеку технологий и применима к большинству frontend-проектов. Документация содержит примеры реализации на JavaScript + React, но FSD успешно адаптируется и к другим комбинациям инструментов (см. [примеры проектов][refs-examples]).
```

2022-02-15 05:23 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
> Added to draft

Не очень понял, что ты имеешь в виду

2022-02-15 05:29 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
Последнее предложение здесь я бы добавлять не стал, так как оно дублирует буллет-лист, который идет дальше.

<details><summary>Офф-топ</summary>
Чувствую небольшое отторжение к этим комментариям, так как они предписывают какие-то изменения, но не пытаются объяснить, почему эти изменения делают доку лучше, и не пытаются узнать, почему я написал именно так. Всё-таки, conventional comments в таких случаях очень помогают комментариям выглядеть дружелюбнее.
</details>

2022-02-15 05:31 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Методология не привязана к конкретному стеку технологий и применима к любым frontend-проектам. Здесь есть примеры на JavaScript + React, но FSD успешно применяется и с другими стеками (см. [примеры п
Почему "большинству"? Разве есть прецеденты, когда FSD применить не получилось?

2022-02-15 05:34 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> -- Обеспечивает **понятность, контролируемость и адаптивность** архитектуры
Я убрал это, потому что мне показалось, что я уже раскрыл эту тему в абзаце ранее:
- **понятность** — предложение выше, "Главная цель — чтоб проект оставался _понятным_ и структурированным и не причинял боли, когда нужно вносить изменения"
- **контролируемость** и **адаптивность** — то же предложение, "Главная цель — чтоб проект оставался понятным и структурированным и _не причинял боли, когда нужно вносить изменения_"

2022-02-15 05:37 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
> А то многие FSD, увы, и воспринимают как "раскладывание по папочкам" - но все же это чуть бОльшее)

thoughts: При всем уважении к методологии — а что это, помимо раскладывания по папочкам?) Для того, чтоб разложить по папочкам, нужно предварительно грамотно декомпозировать всё, а в этом же, вроде, и суть методологии?

2022-02-15 05:41 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
> Ну и еще бы предложил добавить что-нибудь про "нарезку/дробление сложной логики", т.к. FSD тоже на это нацелен, а не только на организацию кода

Я думал внести этот пункт в буллет-лист, но потом понял, что это ощущается немного лишним. Я согласен с тем, что FSD поощряет дробление сложной логики, и делает этот процесс на порядок проще, но я бы не сказал, что это — основополагающий принцип FSD. Как пример — мы поощряем скопление логики на слое widgets при миграции, и всё ещё считаем, что это будет проект по FSD, и что он будет улучшаться в перспективе.

Поинт: мне кажется, момент про дробление логики не подходит в ряд "основополагающих вещей", а помимо этого является всего лишь приятным следствием следования методологии. Мне кажется, не стоит об этом упоминать

2022-02-15 06:34 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
> thoughts: При всем уважении к методологии — а что это, помимо раскладывания по папочкам?) 

~~/ban~~

2022-02-15 06:37 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
> Для того, чтоб разложить по папочкам, нужно предварительно грамотно декомпозировать всё, а в этом же, вроде, и суть методологии?

**Как минимум это)**
https://github.com/feature-sliced/documentation/pull/462#discussion_r806240268
https://feature-sliced.design/docs/get-started/motivation
https://feature-sliced.design/docs/concepts/architecture

И из-за этого особенно не хотелось бы оставлять вариант с "раскладыванием по папочкам"

2022-02-16 06:33 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Методология не привязана к конкретному стеку технологий и применима к любым frontend-проектам. Здесь есть примеры на JavaScript + React, но FSD успешно применяется и с другими стеками (см. [примеры п
Слишком мало ещё кейсов применения к разным непохожим друг на друга стэкам, чтобы говорить что FSD в её нынешнем состоянии **вот прям всё покроет**
Для такого уверенного охвата нужно как минимум дождаться актуализации всей доки

2022-02-16 06:35 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
> > Added to draft
> 
> Не очень понял, что ты имеешь в виду

Я добавила упоминание декомпозиции в описание цели методологии

2022-02-16 06:47 UTC, RinAkaia commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
@azinit а ты что думаешь по поводу последнего предложения?

2022-02-16 07:53 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
Остальные изменения в целом приветствую, но вот по последнему предложению действительно соглашусь с @illright - оно будет дублировать то, что уже будет в буллет-листе дальше (а SummaryHeader должен быть емким как ни крути)

2022-02-16 07:58 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
> мы поощряем скопление логики на слое widgets при миграции, и всё ещё считаем, что это будет проект по FSD, и что он будет улучшаться в перспективе.

[`thoughts:`](https://conventionalcomments.org/#labels) Так это первый этап дробления логики 🤔 
Причем уже здесь обычно есть разделение на "shared"-компоненты (UIKit) и "widget"-компоненты (business-oriented)
Это уже помогает решить большую часть нетривиальных кейсов - организованным способом (и чтобы это можно было все еще дальше разрабатывать без боли)

[`suggestion`](https://conventionalcomments.org/#labels) Но энивей, тут больше цепляется глаз именно к "куда класть код", т.к. в случае FSD это действительно следствие скорее
И вариант с "организацией кода" - куда солиднее и правдивее в случае FSD

[`suggestion(non-blocking)`](https://conventionalcomments.org/#labels) Ну и если получится - то уже засунуть куда-нибудь про *дробление/декомпозицию сложной логики конвенционально*
(будь то буллет лист или SummaryHeader)

2022-02-16 08:40 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
Добавил все кроме последнего предложения

2022-02-16 08:40 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +Методология не привязана к конкретному стеку технологий и применима к любым frontend-проектам. Здесь есть примеры на JavaScript + React, но FSD успешно применяется и с другими стеками (см. [примеры п
Окей, поправил

2022-02-16 08:41 UTC, illright commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
Да, "куда класть код" поправил в рамках другого треда. Про дробление логики — все еще хочется не добавлять это

2022-02-16 09:05 UTC, azinit commented on website/i18n/ru/docusaurus-plugin-content-docs/current/intro.mdx
> +**Feature Sliced Design** (FSD) — это архитектурная методология для проектирования frontend-проектов. Проще говоря, это свод правил и соглашений о том, куда класть код. Главная цель — чтоб проект ост
> Про дробление логики — все еще хочется не добавлять это

Оке, давай на потом оставим тогда, там виднее будет)

2022-02-16 09:06 UTC, azinit approved these changes

2022-02-16 09:10 UTC, RinAkaia approved these changes

2022-02-16 09:13 UTC, merged