improve: blog translations
feature-sliced/documentation pull request #510
Opened 2022-07-26 16:54 UTC by unordinarity

## Changelog

Translated blog posts to both eng and ru locales

2022-07-26 19:39 UTC, azinit requested changes

2022-07-26 19:39 UTC, azinit commented on blog/2022-06-04-rebranding.md
> +Долгое время у FSD была [неконсистентная устаревшая айдентика](https://drive.google.com/drive/folders/11Y-3qZ_C9jOFoW2UbSp11YasOhw4yBdl?usp=sharing). Старый дизайн не передавал ключевые идеи методоло
Ну слуш, идея благая, но учитывая что у нас позже будет больше двух локалей - мы заебемся так переводить

Мб оставим на англ как единый вариант? А то читается оч громоздко, и сильной смысловой нагрузки не вижу в этом (кому надо - и так на англ прочтут из русскоговорящих)

2022-07-26 19:39 UTC, azinit commented on blog/2022-06-04-rebranding.md
> +Долгое время у FSD была [неконсистентная устаревшая айдентика](https://drive.google.com/drive/folders/11Y-3qZ_C9jOFoW2UbSp11YasOhw4yBdl?usp=sharing). Старый дизайн не передавал ключевые идеи методоло
@Rin-Akaia-eth что думаешь?

2022-07-26 19:39 UTC, azinit commented on blog/2022-07-25-international-community.md
> +The new Discord server will give everyone the opportunity to speak out, regardless of their experience with FSD, opinions about the software architecture, preferred method of communication and langua
Кста, упустил в прошлый раз - раз анонсим дискорд пространство, то надо бы это указать в футере и хедере
(а телеграм чат из хедера вообще бы убрать, шоб не пугал иностранцев, раз english-first)

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/42924400/181097320-3093da24-7911-480b-8a02-5e73adcc60e3.png">

<img width="595" alt="image" src="https://user-images.githubusercontent.com/42924400/181097397-5fd5400d-359e-48f2-8914-939cba9d36a7.png">

2022-07-26 19:39 UTC, azinit commented on blog/2022-07-25-international-community.md
> +The new Discord server will give everyone the opportunity to speak out, regardless of their experience with FSD, opinions about the software architecture, preferred method of communication and langua
@Rin-Akaia-eth думаю тоже одобрит, чтоб убрали тгшку из навбара

2022-07-26 20:11 UTC, unordinarity commented on blog/2022-06-04-rebranding.md
> +Долгое время у FSD была [неконсистентная устаревшая айдентика](https://drive.google.com/drive/folders/11Y-3qZ_C9jOFoW2UbSp11YasOhw4yBdl?usp=sharing). Старый дизайн не передавал ключевые идеи методоло
Планирую перенять подход реакта и переводить основную локаль на все остальные силами комьюнити по роллинг-релиз модели. Записей в блоге это тоже касается.

2022-07-27 05:10 UTC, azinit commented on blog/2022-06-04-rebranding.md
> +Долгое время у FSD была [неконсистентная устаревшая айдентика](https://drive.google.com/drive/folders/11Y-3qZ_C9jOFoW2UbSp11YasOhw4yBdl?usp=sharing). Старый дизайн не передавал ключевые идеи методоло
Думаю нам это нафиг не надо)
Только места занимает

2022-07-27 05:11 UTC, azinit commented on docusaurus.config.js
> +    favicon: "img/favicon/classic.png",
А чтобы что?)
Зачем несколько разных фавиконок?

2022-07-27 05:11 UTC, azinit approved these changes

2022-07-27 14:35 UTC, merged