Update resource links and all-contributors graph
feature-sliced/documentation pull request #519
Opened 2022-08-11 08:43 UTC by Rin-Akaia-eth

2022-08-11 18:02 UTC, azinit requested changes

2022-08-11 18:02 UTC, azinit commented on README.md
> +[![tg](static/img/social/tg.png)](https://t.me/feature_sliced "Telegram chat")
suggestion: Мб дискордик еще добавить?

2022-08-11 18:02 UTC, azinit commented on README.md
> +    <td align="center"><a href="https://github.com/Rin-Akaia-eth"><img src="https://avatars.githubusercontent.com/u/8805308?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Rin 🦊🪐😈 Akaia</b></sub></a>
issue(critical): Надо поправить логин в https://github.com/feature-sliced/documentation/blob/master/.all-contributorsrc, а потом перегенерировать через package-script `contributors:add`

А то потом собъется при новой генерации

2022-08-11 18:05 UTC, Rin-Akaia-eth commented on README.md
> +    <td align="center"><a href="https://github.com/Rin-Akaia-eth"><img src="https://avatars.githubusercontent.com/u/8805308?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Rin 🦊🪐😈 Akaia</b></sub></a>
Oops, okay

2022-08-19 20:10 UTC, Rin-Akaia-eth commented on README.md
> +    <td align="center"><a href="https://github.com/Rin-Akaia-eth"><img src="https://avatars.githubusercontent.com/u/8805308?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Rin 🦊🪐😈 Akaia</b></sub></a>
\* `contributors:generate`

2022-08-19 20:30 UTC, unordinarity approved these changes

2022-08-20 15:43 UTC, azinit approved these changes

2022-08-20 15:43 UTC, azinit commented on .all-contributorsrc
> +		{
thoughts: Немног неясно чтобы что отступы менять, но лан)

2022-08-20 15:43 UTC, merged