Add React/Effector example
feature-sliced/documentation pull request #591
Opened 2023-06-08 10:14 UTC by Shiyan7

## Background

Add a great fsd/effector example.

- Repo: [https://github.com/Shiyan7/kinomore-v2](https://github.com/Shiyan7/kinomore-v2)
- Demo: [https://kinomore.netlify.app/](https://kinomore.netlify.app/)

I will be glad to get project review

2023-06-20 11:51 UTC, azinit requested changes
Не все успел тотально глянуть - но базово чекнул, все шикарно)

Осталось только замечания некоторые поправить и можем вливать 🚀

2023-06-20 11:51 UTC, azinit commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
Ну, начнем ревью)

2023-06-20 11:51 UTC, azinit commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
nitpick(non-crit): Не обязательно выделять папку `hooks` в шейред либ
Семантичнее лучше чтоб ты выделил отдельную либу, и положил туда хелперы/хуки необходимые

Т.е. группировка по смыслу, а не по типу (но это некрит на уровне шейреда)
<img width="237" alt="image" src="https://github.com/feature-sliced/documentation/assets/42924400/6493ef03-206c-420c-a5fb-b33ab8ccdc17">

2023-06-20 11:51 UTC, azinit commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
nitpick: В целом бы подумал насчет того чтобы сгруппировать некоторые утилзы в одну либу

например
```diff
+ shared/lib/date/get-year
+ shared/lib/date/minutes-to-hour
// и т.п.
```
<img width="311" alt="image" src="https://github.com/feature-sliced/documentation/assets/42924400/5eaee99e-4b6b-4de5-9b6e-ae231074d7a8">

2023-06-20 11:51 UTC, azinit commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
suggestion: А такие манипуляции с сущностями опять же лучше в entities хранить а не рядом с апихой в шейреде (-> entities/rating/lib)
<img width="608" alt="image" src="https://github.com/feature-sliced/documentation/assets/42924400/5d5f0299-8161-4127-b7e8-9bff3efabd77">

2023-06-20 11:51 UTC, azinit commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
nitpick(non-crit): Не бывает сущности `MovieItem`

Может быть сущность `Movie` и компоненты `MoviesList`, `MovieItem`, `MovieCard` и т.п.)

thoughts: Т.е. лучше такой нейминг именно в компонентах держать а не в названиях сущности
А то у теб появится `MoviePlate` и придется либо новую сущность создавать либо ренейминг делать который сильно структуру перетрясет)

<img width="229" alt="image" src="https://github.com/feature-sliced/documentation/assets/42924400/dec37a86-57a3-4770-85af-9fcb983b4cec">

2023-06-20 11:51 UTC, azinit commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
nitpick(non-crit): Было бы прикольно в фичи добавить и ui отображение, чтоб унифицированно в одном месте было

<img width="187" alt="image" src="https://github.com/feature-sliced/documentation/assets/42924400/cc435df4-8b6d-4ebb-9f3e-0342e7649983">

2023-06-20 11:51 UTC, azinit commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
praise: Из того что понравилось:
🔥 Классно что проект масштабный огромный и много кейсов учтено
🔥  Корректно выделены фичи
🔥 Хорошо в целом распределен шейред
🔥 Хорошо распределены провайдеры
🔥  Хорошо декомпозированы пейджи

2023-06-20 11:56 UTC, Shiyan7 commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
Ок, скоро исправлю)

2023-06-21 06:44 UTC, azinit commented
@Shiyan7 подлей мастер еще -  а то конфликт )

2023-06-22 11:09 UTC, azinit commented
@Shiyan7 ping)

2023-06-22 12:20 UTC, azinit commented
@Shiyan7 пингани как можно будет ревьювить проект еще раз
(но думаю уже вольем после второго раунда ревью)

2023-06-27 08:03 UTC, azinit commented
@Shiyan7 ping)

2023-07-09 18:14 UTC, Shiyan7 commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
> nitpick: Кастомного сегмента `form` нет На каждый чих свой сегмент лучше не создавать а выбирать из существующих
> 
> В данном случае, поскольку это непростая форма- можно в тот же shared/lib положить как полноценную либу
> 
> Но поскольку это больше за ui отвечает (хоть и с хелперами) - то лучше в shared/ui положить (кросс импорты внутри shared/ui разрешены)
> 
> <img alt="image" width="1098" src="https://user-images.githubusercontent.com/42924400/247103941-d8639cf3-7856-4826-8c85-fdee587a666d.png">

Я обновил либу с формой, и оставил прям там в shared/form её настройки

2023-07-09 18:15 UTC, Shiyan7 commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
> nitpick(non-crit): Было бы прикольно в фичи добавить и ui отображение, чтоб унифицированно в одном месте было
> 
> <img alt="image" width="187" src="https://user-images.githubusercontent.com/42924400/247105327-cc435df4-8b6d-4ebb-9f3e-0342e7649983.png">

Пока хз какой будет дизайн у избранного, думаю над этим.

2023-07-09 18:16 UTC, Shiyan7 commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
> suggestion: А такие манипуляции с сущностями опять же лучше в entities хранить а не рядом с апихой в шейреде (-> entities/rating/lib) <img alt="image" width="608" src="https://user-images.githubusercontent.com/42924400/247104545-5d5f0299-8161-4127-b7e8-9bff3efabd77.png">

Этот lib нужен во многих местах, если поместить его в entites то еслинт будет ругатся на то что правила fsd нарушены :(

2023-07-09 18:17 UTC, Shiyan7 commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
> nitpick: Кмк это должно лежать в `entities/genre` <img alt="image" width="408" src="https://user-images.githubusercontent.com/42924400/247103475-1b911aae-7c7b-4d2f-824f-d74f3da00f5a.png">

Тут также, этот GenresEnum нужен во многих местах, например в shared

2023-07-10 10:40 UTC, azinit commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
> Этот lib нужен во многих местах, если поместить его в entites то еслинт будет ругатся на то что правила fsd нарушены :(

Значит проблема в декомпозиции, т.к. сущность не должна знать про другую "в идеале")

Но опять же линтер FSDшный еще не в стейбл состоянии - а значит некритично если одна сущность про другую будет знать

Но тут это non-crit так что можем подзабить

2023-07-10 10:44 UTC, azinit approved these changes

2023-07-10 10:44 UTC, azinit commented on src/pages/examples/_config.ts
> +        source: "https://github.com/Shiyan7/kinomore-v2",
Спасиб что внес правки! 🚀

2023-07-10 10:44 UTC, azinit commented on src/pages/examples/_config.ts
> +        updatedAt: "2023-06-08",
```suggestion
        updatedAt: "2023-07-10",
```

2023-07-10 10:49 UTC, merged

2023-07-10 10:50 UTC, azinit commented
Спасибо за проработанный пример ! :heart: