Add conduit example app
feature-sliced/documentation pull request #592
Opened 2023-06-14 07:31 UTC by sldk-yuri

## Background
This example is my implementation of Conduit [(RealWorld example apps)](https://github.com/gothinkster/realworld) write on Feature-Sliced Design architectural methodology. It's already added to RealWorld showcases, and I think it would be fit in FSD examples as well. Could you take a look at the project and do a review, please?

- source: https://github.com/sldk-yuri/realworld-react-fsd
- website: https://realworld-fsd.netlify.app/

Thank you.

2023-06-20 11:57 UTC, azinit requested changes
I review project basically, but it looks great already! I suppose one change and after it we could merge your example in our FSD list

Thank you for contribution! 🔥

2023-06-20 13:06 UTC, sldk-yuri commented on src/pages/examples/_config.ts
> +        source: "https://github.com/sldk-yuri/realworld-react-fsd",
@azinit sldk-yuri/realworld-react-fsd@e3675a48fb3656c0c681651b2b897f852b0081c1 page folders structure is updated. Thank you for the review. 🙏

2023-06-20 13:11 UTC, sldk-yuri commented
@azinit Could you update `updatedAt` date in `_config.ts` before merge, please? Thank you.

2023-06-21 06:37 UTC, azinit commented on src/pages/examples/_config.ts
> +        updatedAt: "2023-06-15",
```suggestion
        updatedAt: "2023-06-21",
```

2023-06-21 06:37 UTC, azinit approved these changes

2023-06-21 06:43 UTC, merged

2023-06-21 06:43 UTC, azinit commented
@sldk-yuri Thanks for your contribution! ❤️