enhancement/translate to uzbek language
feature-sliced/documentation pull request #597
Opened 2023-07-10 09:54 UTC by Zukhrik

## Background

Created uzbek language and begun translate pages

2023-07-10 10:57 UTC, azinit requested changes
Круто что начал прорабатывать новую локаль
Но если только начал проработку (т.е. что-то на англе еще) - то предлагаю еще на лендосе добить перевод и можем влить для старта)

<img width="2160" alt="image" src="https://github.com/feature-sliced/documentation/assets/42924400/444d9ecf-50b7-4468-8611-57349cd9bceb">

2023-07-10 11:04 UTC, Zukhrik commented
согласен. я наверное тогда закрою PR. Как закончу с переводом открою новый PR

2023-07-10 12:03 UTC, azinit commented
> согласен. я наверное тогда закрою PR. Как закончу с переводом открою новый PR

Можно так, но необязательно)
Можно просто эти json адаптировать для uz локали и мы вольем то что уже есть

А остальное позже доработаем

Тут смущает именно то, что лендинг и другие страницы основные поломанно выглядят, т.к. для них json словарика не заведено

Но в любом случае спасибо за инициативу!
<img width="616" alt="image" src="https://github.com/feature-sliced/documentation/assets/42924400/f7131022-0d8d-48f5-8123-647977fe7025">

2023-07-12 18:36 UTC, Zukhrik commented
@azinit перевел. Вроде все гуд. будут проблемы с переводом думаю уз/Камюнити поможет исправить

2023-07-13 11:19 UTC, azinit approved these changes
Выглядит супер, где-то есть мелкие шероховатости - но думаю сообщество уже поможет поправить)
спасибо за проделанный огромный труд!  ❤️

2023-07-13 11:27 UTC, merged