Add cryptolight example
feature-sliced/documentation pull request #610
Opened 2023-08-04 09:35 UTC by Yar56

## Background

В примере реализуется простое приложение с просмотром криптомонет. Есть пару страниц. Есть фича с добавлением монеты в избранное. Авторизация, регистрация. Есть два api хоста, первый это CoinGecko api, второй свой прокси бэкэнд для firebase (вынес его чтобы фронт приложение не знало про firebase и было удобнее работать)

исходники: https://github.com/Yar56/cryptolight
сайт: http://crypto-light.space/

Прошу сделать ревью. Спасибо!)

2023-08-04 09:36 UTC, Yar56 commented
@azinit fyi

2023-08-04 11:53 UTC, azinit commented
@feature-sliced/core

2023-08-15 09:14 UTC, PUndef commented
- нейминг советуем использовать kebab-case, но не настаиваем. просто он местами немного отличается, например: features/auth/by-email, features/registration/by-email (kebab) остальное в camelCase

2023-08-15 09:14 UTC, PUndef commented
- повсеместно не раскрыта тема публичного апи.
пример плохого использования (видно внутреннюю структуру):
`import { Coin } from '~/shared/api/coingecko/models';`
`import { getCoinPageUrl } from '~/shared/lib/navigate/getCoinPageUrl'; (тут кстати отдельный разговор, Я бы вынес его в отдельную связанную сущность, эта часть явна привязана только к энтити coin и нигде больше не используется)`
для понимания можно ещё раз почитать доку: https://feature-sliced.design/docs/reference/public-api#requirements-for-the-public-api, либо перейти в обсуждение https://github.com/feature-sliced/documentation/discussions/41#discussioncomment-455800

2023-08-15 09:28 UTC, PUndef commented
- по поводу композиции внутри компонента, Я обычно явно выделяю связанные куски логики в хуки (Single responsibility) и потом уже использую внутри компонента
примеры:
src\features\auth\by-email\ui\authModalByEmail\AuthModalByEmail.tsx (логика открытия окна и формы смешаны внутри компонента)
src\features\priceChart\ui\PriceChart.tsx (логика тултипа перемешана с логикой отображения чарта)
но это лично моё мнение, FSD это касается косвенно, т.к. эти части возможно было бы внести в сегмент model, но и объявление в рамках файла с таким размером проекта приемлемо для начала

2023-08-15 09:33 UTC, PUndef commented
смущает немного этот участок кода:
`    const fetchData = useCallback(async () => {
        return await Promise.all([
            coinModel.coinSubModel.getCoinByIdFx({ coinId }),
            coinModel.coinSubModel.getCoinMarketChartByIdFx({ coinId })
        ]);
    }, []);

    useEffect(() => {
        fetchData();
    }, []);
`
не пользователь effector'а но насколько знаю один из его плюсов в возможности не завязываться на жизненный цикл компонента react'а, best practice для получения данных вроде в том, чтобы подписаться на маунт страницы
**это замечание тоже опиональное**

2023-08-15 09:40 UTC, PUndef commented
писал выше об этом компоненте: `src\shared\lib\navigate\getCoinPageUrl.ts`
Я бы подумал действительно ли это shared, так как явно привязано к энтити coin и используется только в нём

к тому же почему-то присутствует импорт из `pages` в `shared`
`import { RouteName } from '~/pages/models';`

2023-08-15 09:41 UTC, PUndef commented
`src\shared\lib\storage\localStorage.ts`
над этим файлом тоже бы подумал, по названию выглядит, как просто удобный интерфейс для работы с LS
по факту же тут явная работа с сущностью User
поэтому перенёс бы эту часть в сущность User

2023-08-15 09:46 UTC, PUndef commented
`src\widgets\header\Header.tsx`
`import { RouteName } from '~/pages/models';`
также импорт с верхнего слоя `pages`
подумай о переносе `RouteName` в `shared/config/routes`, чтобы не нарушать правила
**и нужно разобраться почему линтер тебе не подсвечивает эти места, глазами самому найти такие нарушения по всему проекту достаточно проблематично**

2023-08-15 09:49 UTC, PUndef commented
`src\widgets\layouts\SuspenseLayout.tsx`
почему не просто в `shared/ui`?
виджет обычно для композиции нижележащих слоёв
тут же только обёртка над лоадером
так что подумай о том, почему бы не спустить его в `shared`

2023-09-04 19:48 UTC, illright commented
@Yar56 что думаешь насчет фидбека? Я не смотрел проект сам, поэтому за апдейтами по проекту не следил, хочу понять, в каком состоянии этот ПР

2023-09-05 10:59 UTC, Yar56 commented
@illright @PUndef привет. большинство пунктов обработаны, особенно те которые касаются fsd

2023-09-22 20:55 UTC, illright commented
Так, посмотрел проект сам, во многом все супер, мне нравится, есть несколько моментиков, которые хотелось бы поправить:
1. Внутри слайсов на слоях Pages и Widgets нет деления на сегменты. Да, там по сути только один сегмент, `ui`, и тем не менее. Хочется, чтоб в индексах были ре-экспорты, а код был в сегментах.
2. В некоторых сегментах слоя Shared нет индексов, например, `ui`, `lib` и `config`.
3. На слое Pages есть вне-слайсовый файл, `pages/index.tsx`, который содержит роутинговую логику. По методологии на слоях не может быть кода вне слайсов, роутинг лучше разместить на слое App.

2023-10-12 21:23 UTC, illright requested changes
Помечу пока что как "requested changes"

2023-10-16 07:10 UTC, Yar56 commented
> Так, посмотрел проект сам, во многом все супер, мне нравится, есть несколько моментиков, которые хотелось бы поправить:
> 
> 1. Внутри слайсов на слоях Pages и Widgets нет деления на сегменты. Да, там по сути только один сегмент, `ui`, и тем не менее. Хочется, чтоб в индексах были ре-экспорты, а код был в сегментах.
> 2. В некоторых сегментах слоя Shared нет индексов, например, `ui`, `lib` и `config`.
> 3. На слое Pages есть вне-слайсовый файл, `pages/index.tsx`, который содержит роутинговую логику. По методологии на слоях не может быть кода вне слайсов, роутинг лучше разместить на слое App.

2023-10-18 12:05 UTC, Yar56 commented
@illright добавил везде реэкспорты и убрал indexсы в слоях.

2023-10-19 21:13 UTC, illright approved these changes
Посмотрел правки, спасибо, теперь все хорошо. Вдогонку пара неблокирующих комментов, скорее, общий адвайс:
1. Не рекомендуется реэкспортировать через `export * from`, т.к. это мешает три-шейкингу, и теряется аспект явной декларации публичного API. Суть в том, чтоб внутри слайса могло происходить и экспортироваться что угодно, а снаружи было видно только то, что явно помечено как "публичное"
2. По правилам FSD внутри слайса можно кросс-импортировать между сегментами, и для небольшого визуального разделения рекомендуется использовать относительные импорты `from "../ui/Component.tsx"` вместо абсолютных `from "~/features/smth/ui/Component`. 

Можешь исправить, а можешь оставить, как есть. В любом случае, ПР готов к мерджу

2023-10-19 21:14 UTC, merged