Добавление примера с Nuxt 3, Pinia, Composition api
feature-sliced/documentation pull request #620
Opened 2023-09-06 12:04 UTC by Denis-Str

Добрый день - пример с использованием nuxt3,  pinia, composition api

2023-10-15 09:06 UTC, illright requested changes
Привет, спасибо за пример!

Немного фидбека по коду:
1. У тебя слои лежат вместе с остальными папками, например, `assets`, `layouts`, `server`. Из-за этого немного сложно исследовать проект. Есть ли возможность в Nuxt выделить FSD в отдельную папку?
2. Фичи в твоем проекте сгруппированы по сущности (лежат в `task/`), так делать не рекомендуется, потому что в дальнейшем такую группировку будет сложнее поддерживать. Иногда (довольно часто) фичи используют сразу несколько сущностей, поэтому такая группировка будет сбивать с толку. В целом, в этом приложении всего одна сущность и две фичи, я бы предложил их не группировать вообще
3. Кажется, Nuxt требует, чтоб файлы в `pages` были сразу компонентами. Это конфликтует со структурой страниц в FSD. Как насчет хранить непосредственно компоненты страниц где-то в другом месте по FSD, а в `/pages/` просто импортировать их в файлах-роутах? Здесь хорошо впишется совет 1 про разделение папок Накста от папок FSD

Скажи, что думаешь насчет этого фидбека. Олсо я заметил, что ты не загрузил скриншот приложения, почему?

2023-10-17 07:57 UTC, Denis-Str commented
Думаю, что можно и нужно исправить - займусь этим )
На счет скриншота, забыл ( - сделаю

2023-11-06 10:17 UTC, Denis-Str commented
привет, добавил скриншот, так же внес изменения с учетом рекомендаций

2023-11-11 10:57 UTC, illright commented
Посмотрел изменения. Ты точно правильную картинку загрузил? Там сейчас просто логотип Nuxt, а по-хорошему должен быть скриншот приложения.

Насчет структуры в `fsd/pages` — там сейчас, кажется, структура соответствует структуре роутов. По правилам FSD в слоях лежат слайсы, в слайсах — сегменты. В таких рамках слой Pages должен быть "плоским" — на одном уровне слайс страницы IndexPage и TaskPage. Можешь, пожалуйста, этот момент тоже поправить?

2023-11-23 11:34 UTC, Denis-Str commented
картинку подправил
на поводу "на одном уровне слайс страницы IndexPage и TaskPage", но внес изменения

2023-11-24 18:36 UTC, illright commented
Запустил проект на [StackBlitz](https://stackblitz.com/~/github.com/Denis-Str/nuxt3-fs), вижу вот это:
<img width="762" alt="image" src="https://github.com/feature-sliced/documentation/assets/15035286/76f38bf4-0b41-4620-887b-bd645db718ac">
А скриншот был взят с другого проекта. Я делаю что-то не так, или скриншот не соответствует действительности?

2023-11-30 09:50 UTC, Denis-Str commented
не подтянулись стили
вот скрин локальной сборки
![изображение](https://github.com/feature-sliced/documentation/assets/39305243/dc46f9a4-6953-4c5f-9736-8a4f4d3cf265)

2023-12-02 15:04 UTC, illright commented
Окей. Насчет файловой структуры — все-таки все еще не полностью соответствует структуре FSD (слои -> слайсы -> сегменты), например, в `fsd/pages/index/` (слой pages, слайс index) должен быть сегмент `ui/`, в котором уже лежит компонент страницы, плюс файл `pages/index/index.ts` — декларация публичного API. Кстати, из-за того, что файл публичного API называется index.ts, название слайса index может быть немного путающим. Я бы предложил назвать этот слайс `home`. 

Аналогично про `fsd/features`, там тоже не везде прослеживаются сегменты. В качестве хорошего примера деления на сегменты могу выделить папку `fsd/entities/task`.

На другой ноте, недавно общался с другим контрибьютором в репозитории awesome насчет шаблона проекта на Nuxt 3, возможно, тебе будет интересно почитать: https://github.com/feature-sliced/awesome/pull/3

2024-02-06 06:19 UTC, closed without merging