docs: usage with NextJS article updated
feature-sliced/documentation pull request #644
Opened 2023-11-26 13:23 UTC by midas-png

## Background

I've faced a problem when starting developing a project using NextJS with FSD. Many time spent to get it right to combine NextJS and FSD to make it work together. There was no detailed article in the documentation of how it should work. So I decided to research the best practices of me and colleagues and describe in the article about using with NextJS

## Changelog

1.  **Usage with NextJS** article was updated in russian and english
2.  `sidebar_class_name: sidebar-item--wip` was removed from `.mdx` files about usage with NextJS _(in russian and english)_

The WIP notification was left in the article as I think it should be updated by adding more useful links in the **See also** section

### before:
![image](https://github.com/feature-sliced/documentation/assets/78198187/ea02edd4-a634-4ac8-b2a1-966b13b0c88d)
![image](https://github.com/feature-sliced/documentation/assets/78198187/fd4e73d3-6f71-4c83-93fd-0df7f3940703)

### after:
![image](https://github.com/feature-sliced/documentation/assets/78198187/d06ca60b-eb2e-4271-b93e-ffcc66cfd0f2)
![image](https://github.com/feature-sliced/documentation/assets/78198187/1d02056c-a086-4317-a33c-9986d061d81f)

2023-11-27 09:55 UTC, illright commented
Hi! This is great, I'm really glad someone actually took the time to write this up. As for the WIP status of this page, I personally think it's okay to mark this page as ready. The only thing I'd like to see are links to [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/) where a small version of Next is deployed along with the proposed structure, just to have something practical to look at. Could you add that please? Other than that, everything else is good

2023-11-27 13:49 UTC, midas-png commented
Thanks! Sure, I'll take care of it

2023-11-28 07:50 UTC, NazariiShvets commented
Thanks for your contrubition ❤️‍🔥 I believe you have done a great job 👍 

I only have one problem with the `pages-flat' naming
I feel that this naming has 2 problems:

1) It encourages you to structure your pages into a **flat** list. I would be happy if there was a mention of `grouping` somewhere so that users know how to structure pages if there are many of them

2) The name itself is quite ugly. Alternatives could be `views` or `screens`, but I have no experience with a nextjs project.
It would be great if you could organize a poll within the community (like in the Telegram chat), collect their feedback on their choices and what names they use, and based on that response choose an appropriate name.
If the community chooses `pages-flat`, it can be used

2023-12-05 15:30 UTC, NazariiShvets approved these changes

2023-12-06 22:42 UTC, midas-png commented
I made a poll in the Telegram chat, but since many people use the App Router, I did not get a definite opinion on this issue. I left the option with `views`. Also, unfortunately, due to the high workload at work, I can't do the links to CodeSandbox now. I'm ready to deal with it later

2023-12-08 21:30 UTC, illright requested changes
Не переживай насчет примеров, если загружен по работе — добавить всегда успеем, это не блокер для этого ПРа. Вчитался сейчас в текст, оставил несколько комментариев и предложений. Еще было бы клево пройтись по тексту через Главред (русский) и LanguageTool (английский), чтоб местами улучшить читаемость и отловить грамматические ошибки, если они имеются

2023-12-08 21:30 UTC, illright commented on i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx
> +Этот механизм маршрутизации **не соответствует** концепции FSD, поскольку это может привести к смешиванию функциональности различных модулей в одном файле.
> поскольку это может привести к смешиванию функциональности различных модулей в одном файле.

Думаю, дело не столько в этом, сколько в таком механизме роутинга не представляется возможным соблюсти плоскую структуру слайсов, предписываемую FSD

2023-12-08 21:30 UTC, illright commented on i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx
> +### Перемещение директории `pages` NextJS в корневую директорию проекта (рекомендуется)
nitpick (non-blocking): не крит, но хотелось бы в доке называть директории папками. Термин "директория" мне кажется излишне техническим, все операционные системы сейчас называют их именно папками

2023-12-08 21:30 UTC, illright commented on i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx
> +__Оба подхода к разрешению конфликтов также предполагают использование [группирования маршрутов](https://nextjs.org/docs/app/building-your-application/routing/route-groups) при наличии большого колич
question: а разве понятие "группа маршрутов" уместно вне контекста некстовской папки App или Pages? У меня это предложение создает впечатление, что речь идет про группы слайсов

2023-12-08 21:30 UTC, illright commented on i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx
> +В NextJS ниже версии 13 нет явного слоя `app`, вместо этого NextJS предоставляет файл `_app.tsx`,
issue: мне кажется, в контексте Некста неприменимо понятие "слой", либо я не так понял эту фразу

2023-12-08 21:30 UTC, illright commented on i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx
> +Чтобы решить проблему, вам следует создать компонент внутри слоя `app` и импортировать его в `pages/_app.tsx`, чтобы NextJS мог с ним работать.
issue: тут немного непонятно, о какой проблеме идет речь, и какой компонент нужно создать

2023-12-08 21:30 UTC, illright commented on i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx
> +// app/index.tsx
issue: этот файлик будет вне сегмента, а на слое App, по-хорошему, все файлы должны быть сгруппированы по сегментам

suggestion: можно назвать этот файл `app/providers/index.tsx`

2023-12-08 21:30 UTC, illright commented on i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx
> +Необходимо импортировать созданный компонент `App` и глобальные стили проекта в `pages/_app.tsx` следующим образом:
issue (non-blocking): немного смущает, что в этой статье часто что-то очень неоднозначно предписывается, например, в данном случае, фразой:

> Необходимо импортировать

suggestion: 

```suggestion
Затем вы можете импортировать созданный компонент `App` и глобальные стили проекта в `pages/_app.tsx` следующим образом:
```

2023-12-13 18:48 UTC, midas-png commented on i18n/ru/docusaurus-plugin-content-docs/current/guides/tech/with-nextjs.mdx
> +__Оба подхода к разрешению конфликтов также предполагают использование [группирования маршрутов](https://nextjs.org/docs/app/building-your-application/routing/route-groups) при наличии большого колич
нет. Это было добавлено как доп. материал для лучшего структурирования большого кол-ва страниц при разрешении конфликта. Но скорее всего, эту часть стоит удалить

2023-12-13 19:40 UTC, midas-png commented
Сделал правки по комментариям. Поправил русскую и английскую версии. По главреду читаемость 9.5, в LanguageTool  тоже проверил. Ссылки на route-groups удалил

2023-12-17 19:02 UTC, illright approved these changes
@midas-png Я добавил небольшой моментик про проектные знания. Также я изменил путь импорта в одном месте и убрал остаточные пробелы. Посмотри, пожалуйста, скажи, что думаешь насчет этих изменений. С моей стороны никаких больше комментариев, можем вливать.

2023-12-18 13:54 UTC, midas-png commented
@illright Посмотрел, спасибо, изменения к месту

2023-12-18 14:38 UTC, merged