Feat/translate some files to uz
feature-sliced/documentation pull request #650
Opened 2024-01-25 09:07 UTC by Zukhrik

## Background

## Changelog

2024-01-25 09:11 UTC, Zukhrik commented
@illright Апрувнишь ПР?

2024-01-28 20:05 UTC, illright requested changes
Привет, спасибо за перевод! Единственный моментик — с момента, когда ты писал этот перевод, мы немного переработали секцию FAQ, убрали некоторые вопросы, добавили другие, уточнили ответы. Можешь актуализировать ее, пожалуйста?

2024-09-19 15:30 UTC, illright commented
@Zukhrik этот ПР еще актуален?

2024-09-20 05:57 UTC, Zukhrik commented
@illright Прошу прошения что так долго не мог актуализировать ПР. Файл FAQ сильно отличается. я пока удалил его что бы не задерживать ПР. Займусь им и остальным скоро.

2024-09-20 10:15 UTC, illright commented
Тут просто такое дело, страница Овервью тоже была переработана, а cheatsheet был вообще убран из доки с момента, когда ты делал перевод :) Можно, в целом, с этим не торопиться, и в этом ПРе все актуализировать и влить вместе

2025-02-09 10:07 UTC, illright commented
Закрою этот ПР пока как устаревший. Если еще будет желание вернуться к этому, буду рад, но открой, пожалуйста, новый ПР

2025-02-09 10:07 UTC, closed without merging