feat: update decomposition cheatsheet
feature-sliced/documentation pull request #697
Opened 2024-07-24 08:59 UTC by falkomerr

2024-07-24 21:52 UTC, illright commented
Is there any particular reason that you want this cheatsheet back? I'm hesitant to bring it back even with a disclaimer of some kind because I don't think it's useful in its current form, and it can be rather confusing. Our problem right now is that we have too many definitions that are too narrow, we need to widen the definitions, not constrain them even further

2024-07-25 07:11 UTC, falkomerr commented
this cheat sheet really simplifies both the decomposition process for beginners and the overall understanding of what these layers should do

2024-07-25 22:07 UTC, illright requested changes
I left a few comments regarding the writing, but I still don't want to bring back that decomposition cheatsheet. It propagates the idea that widgets and pages are just combinations of the layers below, an idea that ended up being quite toxic to the codebase and people's understanding of FSD. There are still some other parts of the docs that propagate the same idea, but I'm working on rewriting them. As for the cheatsheet, I would only be willing to merge this once I rewrite the cheatsheet itself a little bit. I'm not sure when I'll get around to this, but I'll try not to make it too long

2024-07-25 22:07 UTC, illright commented on i18n/en/docusaurus-plugin-content-docs/current/get-started/cheatsheet.mdx
> +- A person reading your code, seeing that a slice is not part of the page, may begin to question whether they are breaking part of the display by changing that slice.
issue: it's not clear to me what "display" is

suggestion:
```suggestion
- A person reading your code, seeing that a slice is not part of the page, may begin to question whether this code is used somewhere else, and if they are breaking anything by changing it.
```

2024-07-25 22:07 UTC, illright commented on i18n/en/docusaurus-plugin-content-docs/current/get-started/cheatsheet.mdx
> +If you are sure that your slice will be used in more than one place, you can use the note below.
suggestion:
```suggestion
If you are sure that your slice will be used in more than one place, or you have another very good reason to decompose the code into the lower layers, you can use the note below.
```

2025-04-18 21:59 UTC, illright commented
Closing as stale

2025-04-18 21:59 UTC, closed without merging