Update examples
feature-sliced/documentation pull request #705
Opened 2024-08-07 10:43 UTC by creator-woow

Think it's pretty example

2024-08-10 19:35 UTC, illright commented
I noticed that there are errors when I run Steiger, the FSD linter, on this project. Could you fix them please?

2024-08-11 22:57 UTC, creator-woow commented
@illright Yeah I see, I'm gonna fix it

2024-08-12 20:56 UTC, creator-woow commented
@illright Fixed. Only 4 left, the reason is I can't name pages folder according fsd while using nextjs 14+. As soon as builder sees pages folder it starts build like I use pages router (while I'm using app router)
![Снимок экрана 2024-08-12 в 23 48 43](https://github.com/user-attachments/assets/100d0432-df39-4455-ac21-8d0acf50ac21)

2024-08-13 14:55 UTC, illright commented
What about this solution? https://feature-sliced.design/docs/guides/tech/with-nextjs#moving-the-pages-folder-of-nextjs-to-the-root-folder-of-the-project-recommended

2024-08-13 15:47 UTC, creator-woow commented
@illright The solution is for pages router, I use latest app router, so it's not fit

2024-08-13 16:10 UTC, creator-woow commented
@illright Below was my case solution, I fixed all except these two.  The reason is that they referenced only once, but with app scaling amount on their references will be enough, so I don't thing these are problem
![Снимок экрана 2024-08-13 в 19 08 02](https://github.com/user-attachments/assets/c414e53e-b365-4fd6-b612-6d69ae674db2)

2024-08-17 10:35 UTC, illright requested changes
These errors point to unnecessary slices. Your app looks quite simple, so it doesn't really need the layer of features (and possibly, doesn't even need entities). Consider trying to fit the app in just Shared, Pages, and App, the architecture will be simpler.

2024-08-22 15:30 UTC, creator-woow commented
@illright If I remove unnecessary slices will you merge it?

2024-09-19 14:59 UTC, illright commented
These slices are indeed a blocker, but I may have some more comments after this refactor

2024-10-08 16:58 UTC, creator-woow commented
@illright Okay, no staiger errors had stayed

2024-11-19 14:34 UTC, creator-woow commented
@illright Pls either review & merge, or close pr, if you won't merge it

2024-11-19 14:57 UTC, illright commented
I will review it when I get through other higher-priority things and find the time. I'm intending to merge this PR, so I don't want to close it, but I can't give an estimate for when I can do the review. 

If you'd like to speed up the process of getting this PR merged, I can suggest asking someone in our Telegram chat for review. Perhaps they could point out some improvements and you could implement them ahead of the final review

2024-11-19 17:14 UTC, creator-woow commented
> I will review it when I get through other higher-priority things and find the time. I'm intending to merge this PR, so I don't want to close it, but I can't give an estimate for when I can do the review.
> 
> If you'd like to speed up the process of getting this PR merged, I can suggest asking someone in our Telegram chat for review. Perhaps they could point out some improvements and you could implement them ahead of the final review

Got it, thank you for fast reply

2025-06-19 22:14 UTC, illright commented
I've decided not to stop adding examples to the site because of how much time they take to review and because the example section seems to be a persistent frustration with users. I'd prefer it if in the future we had a completely revised section with examples that would be more curated, but for now, please accept my apology for dragging this PR on for so long and then not merging it.

2025-06-19 22:14 UTC, closed without merging