Add new v2 project for FSD examples
feature-sliced/documentation pull request #712
Opened 2024-08-21 11:30 UTC by ifeelBALANCED

## Background

## Changelog

2024-08-22 04:20 UTC, sanua356 commented
Hello! I tried to register on the site and after sending the forms (registration or login does not matter), I get a message about a redirect. Then nothing happens

![Screenshot_20240822_071718.jpg](https://github.com/user-attachments/assets/daea8246-8db3-430e-a0dd-9c0e881150a6)

![Screenshot_20240822_071810.jpg](https://github.com/user-attachments/assets/8bcf0456-6e88-43e4-8c06-78917334bfdd)

2024-08-23 11:36 UTC, ifeelBALANCED commented
> Hello! I tried to register on the site and after sending the forms (registration or login does not matter), I get a message about a redirect. Then nothing happens
> 
> ![Screenshot_20240822_071718.jpg](https://private-user-images.githubusercontent.com/51795446/360284152-daea8246-8db3-430e-a0dd-9c0e881150a6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTMwMzQsIm5iZiI6MTcyNDQxMjczNCwicGF0aCI6Ii81MTc5NTQ0Ni8zNjAyODQxNTItZGFlYTgyNDYtOGRiMy00MzBlLWEwZGQtOWMwZTg4MTE1MGE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDExMzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYjgxZmQ5NmY2OTlmMGZkMmZkMTEwN2QyMmI1OTZkZmQxNTdlODEwZDE5ZGZjNzEzZjgwNzk4ZmZiOWZmYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a7l2YcNCoWgy7p29VO28O_bMQy2FdF7FRIqI03dtq5s)
> 
> ![Screenshot_20240822_071810.jpg](https://private-user-images.githubusercontent.com/51795446/360284151-8bcf0456-6e88-43e4-8c06-78917334bfdd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTMwMzQsIm5iZiI6MTcyNDQxMjczNCwicGF0aCI6Ii81MTc5NTQ0Ni8zNjAyODQxNTEtOGJjZjA0NTYtNmU4OC00M2U0LThjMDYtNzg5MTczMzRiZmRkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDExMzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMDBlMzgxOWFmN2QxNWYyZWFlMTkyYTQxNzk4NDhjZDYwMTk0NThlN2IwZmFhZjAyODdhOWYyMjI3MDQ4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p4mIK4zVDjHkpb_0dWlrKU7FpcbU5jxSZDrLFNPksIE)

Hi, the current version of the backend is written in python and deployed to render.com, if no requests have gone there, the backend needs to wake up, which can take time, this is the error of free deployment, redirecting means that the request is still pending, after it passes, you will be redirected. I would look at the site from a computer, just not adapted for mobile yet.

2024-09-19 15:01 UTC, illright requested changes
Hi, thanks for the example! I see that there are some Steiger errors, could you investigate please?
```
pnpx steiger ./src
```

2025-04-18 22:01 UTC, illright commented
Closing as stale

2025-04-18 22:01 UTC, closed without merging