Add new example to v2 list
feature-sliced/documentation pull request #721
Opened 2024-09-19 20:29 UTC by s3rxio

## Changelog
New example to v2 list.
[Cat Pinterest](https://github.com/s3rxio/cats-app) where you can look at kittens and like them (=^･ω･^=)

2024-09-21 17:27 UTC, illright requested changes
Hi, thanks for the example! There are no issues found with Steiger, great job! Looking at the project code, I have a few remarks:
1. I often see `export * from`, for example, in `front/src/shared/api/index.ts`. It's usually bad practice for defining public APIs, because the whole point of the public API is to restrict what objects are accessible outside of a slice. Wildcard exports make the public API less dependable and more difficult to read
2. The login modal is located in `entities/user`, which I found quite unexpected. I would expect to find it in a page or maybe a widget.

In general, I think that this application is small enough that having both Entities and Features is probably more distracting than beneficial to the architecture. I would suggest just having two widgets for the cat list and the auth modal, two pages, and then just the Shared layer.

2024-09-21 21:49 UTC, s3rxio commented
Привет, @illright!
Предлагаю продолжить на русском.
По поводу замечаний:
 - Исправлю
 - У меня проблемы с авторизацией. Я хочу сделать открытые модального окна авторизации когда нет токена или при ошибке 401 на уровне API, но не знаю как будет правильно это реализовать на FSD.

2024-09-23 08:22 UTC, illright commented
> Я хочу сделать открытые модального окна авторизации когда нет токена в запросе или ошибка 401 в ответе и все это на уровне Shared API

Не думаю, что это будет правильно с точки зрения FSD. Слой Shared должен быть просто связующим звеном твоего приложения и внешнего мира, а такую логику, как открытие модалки по неудавшемуся запросу, я бы туда класть не стал. Более того, такая привязка может создать больше проблем в будущем, когда логика приложения будет расти. Я бы предложил решить эту проблему на стороне дизайна интерфейса — сделать четко зафиксированные триггеры для показывания этой модалки — например, нажатие на кнопку "логин" или нажатие на сердечко, когда пользователь не залогинен

2024-10-03 00:25 UTC, s3rxio commented
Привет!
Никак не мог найти время на рефакторинг
- Убрал слой entities и перенес все **api queries** в **shared/api** 
- Перенес логику **авторизации** в **features/auth**
- Перенес **cats-list** в слой **widgets**

2024-10-04 10:02 UTC, illright commented
Привет, спасибо!
- "Убрал слой entities и перенес все api queries в shared/api" — супер
- "Перенес cats-list в слой widgets" — тоже круто
- "Перенес логику авторизации в features/auth"  
  Вот тут я обычно рекомендую не создавать фичу под авторизацию. Фичи — это такое уникальное место в FSD-проекте, где в одном глобальном списке должно лежать все самое важное, что стоит знать о продукте, чтоб делать осознанный контрибьюшн. Авторизация — одна из наименее уникальных штук в приложении, и более того, довольно редко изменяемая. Если она лежит в фичах, то она занимает очень ценное пространство на "мысленной карте" проекта в головах разработчиков без особо хорошей причины.
  
 Что с этим можно сделать: вижу, что cats-list использует из этой фичи только `useAuth`, который, в свою очередь, использует только `AuthContext`. Я бы предложил перенести этот хук и этот объект контекста куда-нибудь типа `shared/api/auth` или `shared/auth` (и туда же докинуть AuthGuard), а все остальное из этой фичи (компонент AuthProvider, AuthModal) засунуть куда-нибудь повыше, может, даже вообще в App. Главная цель — чтоб этот код не мешался и не отвлекал от основной бизнес-логики приложения (лайкать котиков)

2025-06-19 22:15 UTC, illright commented
Я принял решение больше не добавлять примеры на сайт, потому что их тяжело ревьюить, и люди все равно не очень много пользы извлекают из примеров небольших проектов. Прошу прощения, что в конце концов не получилось смерджить

2025-06-19 22:15 UTC, closed without merging