docs: guide example page translated into Korean
feature-sliced/documentation pull request #735
Opened 2024-10-13 07:39 UTC by Gaic4o

I have translated the Guide page into Korean.

If you think there are aspects that need improvement, please let me know, and I would be happy to make the adjustments. Thank you!

2024-10-13 16:10 UTC, illright commented
Thanks! Could you also ask someone from Discord to check these translations?

2024-10-13 22:35 UTC, Gaic4o commented
@illright  Got it, thank you.

2024-10-22 13:10 UTC, movie42 requested changes

2024-10-22 13:10 UTC, movie42 commented on i18n/kr/docusaurus-plugin-content-docs/current/guides/examples/index.mdx
> +    description="FSD에서 타입을 어디에 배치하고 활용할지에 대한 가이드"
page layouts을 직접 번역하셨기 때문에 아시겠지만 해당 description이 Types discription의 내용이 섞여 들어간것 같습니다. 원문 내용 확인하셔서 수정해주세요.

2024-10-22 13:12 UTC, movie42 requested changes
코멘트 확인부탁드립니다.

2024-10-24 14:20 UTC, Gaic4o commented
@movie42  제가 타입쪽 `description`을 작성한 것 같네요. `title`에 맞게 다시 `description`을 수정했어요!

2024-10-25 09:59 UTC, movie42 approved these changes
고생하셨습니다! 👍

2024-10-26 17:06 UTC, illright approved these changes

2024-10-26 17:06 UTC, merged