Backticks Added for Layers on /get-started
feature-sliced/documentation pull request #777
Opened 2024-12-15 09:27 UTC by midas-png

## Background
IMHO, the layer names look nondescript [here](https://feature-sliced.design/docs/get-started/overview#layers).

![image](https://github.com/user-attachments/assets/c0b74c19-e89e-4e89-ba75-0aadf93673bf)

## Changelog
I suggest adding backticks to highlight the layers, just like it’s done on the same page with [segments](https://feature-sliced.design/docs/get-started/overview#segments) and the [basic example](https://feature-sliced.design/docs/get-started/overview#basic-example)

![image](https://github.com/user-attachments/assets/b486f84d-611e-4b66-9a8d-68c6a29fea44)

2024-12-15 17:23 UTC, illright requested changes
Hi! These layer names were deliberately formatted as regular text with capital letters — it's to distinguish the name of the layer and the folder of that layer. This is also why the folders have a folder emoji included.

I do agree that the layer names could stand out a bit more, but I don't think code formatting is the way to go here. Maybe bold would look better?

2024-12-16 19:12 UTC, midas-png commented
I agree, bold indeed looks better. I've pushed the commit. Thanks!

![image](https://github.com/user-attachments/assets/ddee367a-f7b4-4255-b8d2-f77e72f08cd3)

2024-12-17 22:57 UTC, illright approved these changes

2024-12-17 22:58 UTC, merged

2024-12-17 22:58 UTC, illright commented
Thanks!