chore: add message in overview
feature-sliced/documentation pull request #782
Opened 2024-12-26 11:06 UTC by sanua356

## Background

Привет команде FSD! После изучения документации показалось недостаточно броским сообщение о том, что структура слой->слайс->сегменты сохраняется для всех слоёв, кроме shared и app (на мой взгляд сообщение об этом достаточно сложно заметить в тексте).

## Changelog

Чуть изменено и добавлено в обертку "warning" сообщение о том, что структура структура слой->слайс->сегменты сохраняется для определённых слоёв.

2025-02-09 10:16 UTC, illright requested changes
Thanks! Sorry for the long wait. Left a few small correction suggestions

2025-02-09 10:16 UTC, illright commented on i18n/en/docusaurus-plugin-content-docs/current/get-started/overview.mdx
> +However, for all other layers: **Entities**, **Features**, **Widgets** and **Pages** retain the structure in which you must first create slides, inside which to describe the segments.
issue: the term "slice" contains a typo "slide"

2025-02-09 10:16 UTC, illright commented on i18n/en/docusaurus-plugin-content-docs/current/get-started/overview.mdx
> +However, for all other layers: **Entities**, **Features**, **Widgets** and **Pages** retain the structure in which you must first create slides, inside which to describe the segments.
suggestion (non-blocking): I think this is better from the point of view of punctuation and grammar
```suggestion
Layers: **App** and **Shared**, unlike other layers, do not have slides and are divided into segments directly.

However, all other layers — **Entities**, **Features**, **Widgets**, and **Pages**, retain the structure in which you must first create slides, inside which you create the segments.
```

2025-02-09 10:16 UTC, illright commented on i18n/ru/docusaurus-plugin-content-docs/current/get-started/overview.mdx
> +Однако для всех остальных слоёв: **Entities**, **Features**, **Widgets** и **Pages** сохраняется структура в которой необходимо сначала создать слайс, внутри которого описывать сегменты.
suggestion: the same here
```suggestion
Слои: **App** и **Shared**, в отличие от других слоев, не имеют слайсов и состоят из сегментов напрямую. 

Однако для всех остальных слоёв — **Entities**, **Features**, **Widgets** и **Pages**, сохраняется структура, в которой необходимо сначала создать слайс, внутри которого создавать сегменты.
```

2025-02-09 12:28 UTC, sanua356 commented on i18n/ru/docusaurus-plugin-content-docs/current/get-started/overview.mdx
> +Однако для всех остальных слоёв: **Entities**, **Features**, **Widgets** и **Pages** сохраняется структура в которой необходимо сначала создать слайс, внутри которого описывать сегменты.
Hi! I agree. All the issues mentioned in the comments have been fixed.

2025-02-15 10:40 UTC, illright commented on i18n/en/docusaurus-plugin-content-docs/current/get-started/overview.mdx
> +However, for all other layers: **Entities**, **Features**, **Widgets** and **Pages** retain the structure in which you must first create slides, inside which to describe the segments.
There are still other instances of this mistake, could you check again please?

2025-02-15 11:08 UTC, sanua356 commented on i18n/en/docusaurus-plugin-content-docs/current/get-started/overview.mdx
> +However, for all other layers: **Entities**, **Features**, **Widgets** and **Pages** retain the structure in which you must first create slides, inside which to describe the segments.
Sorry, I really didn't notice it in one place. I've already corrected it.

2025-02-15 11:30 UTC, illright approved these changes
Thanks for quickly addressing the comments! This is ready to be merged.

2025-02-15 11:30 UTC, merged