Процесс принятия решений
feature-sliced/documentation pull request #84
Opened 2021-04-10 08:12 UTC by sergeysova

Closes #81

2021-04-10 08:52 UTC, martis-git requested changes
В целом все гуд, но:
1. Убрал бы из ридми эту инфу
2. Раскрыл бы получше некоторые моменты
3. (некритично) Возможно бы упростил бы разметку, т.к. оч большое полотно [опять](https://github.com/feature-sliced/wiki/discussions/43) получается...
   > Мб спойлеры или quote-area добавил бы

2021-04-10 08:52 UTC, martis-git commented on README.md
> +## Как мы принимаем решения
Я бы старался держать README максимально простым, насколько это возможно

> Человек, заходя на страницу вики - хочет сначала узнать о чем эта репа и какую пользу может ему принести, а потом уже - всяческие детали 
>
> Потому кста мне и показалось - что лучше такие вещи выносить как ссылки внизу (и то - их кол-во тоже потом бы уменьшить, как структуру добьем)
![image](https://user-images.githubusercontent.com/42924400/114264024-2dd47b00-99f1-11eb-998e-ca67d8a9d26e.png)

А потому - наверное стоит либо это же самое впихнуть в CONTRIBUTING (расширить, как по мне это прям про то), либо в другой файл (тоже в рут положить можно думаю)

2021-04-10 08:52 UTC, martis-git commented on README.md
> +1. **Возможное решение**. Несколько подробных предложений с практическими примерами как предлагается решить проблему из первого пункта. Чем больше подробной информации о том "почему именно так", тем
Очень похоже, что это надо засунуть в issue-template/pr-template не?

2021-04-10 08:52 UTC, martis-git commented on README.md
> +1. **Возможное решение**. Несколько подробных предложений с практическими примерами как предлагается решить проблему из первого пункта. Чем больше подробной информации о том "почему именно так", тем
Возможно то что здесь есть и можно оставить, но в темплейтах - по идее тоже должно быть (для нашего же удобства)

2021-04-10 08:52 UTC, martis-git commented on README.md
> +Дальше есть два пути, что делать с собранной информацией: создать issue или создать pull request.
Мне казалось, что в воркфлоу главным образом должны быть и ответы на вопросы:
1. Когда мне стоит создавать дискуссию/ишью?
> Т.е. если у меня есть вопрос с возможным дополнением в методологию - должен ли я открывать ишью (у нас куча лежит и без подвижек пока) или же лучше начинать с дискуссии?
2. Что делать с открытыми и затянувшимся дискуссиями (которые не связаны с задачей) - стоит их лочить и переписывать в доку или что-то другое?
> Иными словами - есть ли у нас какие-то правила по очистке "бэклога" задач и дискуссий?

2021-04-10 08:52 UTC, martis-git commented on README.md
> +Дальше есть два пути, что делать с собранной информацией: создать issue или создать pull request.
3. И самое главное - для нас - как принимать решения по дискуссии?
> Ну да, кто-то может получить задачу на "расписывание доки по дискуссии" условно. Или же взять дискуссию для написания другой доки. А в какой момент нам нужно уметь остановиться и сделать выводы? (вытекает в каком-то виде из второго вопроса)

2021-04-10 08:52 UTC, martis-git commented on README.md
> +Методология построена на базовых принципах и каждое новое предложение должно укладываться в эти принципы, поэтому после открытия pull request или issue, команда развития методологии будет заниматься
Я бы тут как-то дополнительно подчеркнул, что все то что ты ниже под этим написал (Проблема, Воспроизведение, ЦА, Возможное решение) - это то что нужно сделать **перед ишью/дискуссией/pr**

А потом уже (опираясь на доп. правила) контрибьюторы заводят ишью/дискуссию/pr

> Кста опять же -нет ответа на вопрос, в каком случае можно заводить дискуссию - я бы это тоже проговорил, т.к. все остальное оч подробно описано - а про дискуссии ни слова
> 
> Как будто их сами по себе нельзя открывать

2021-04-11 08:54 UTC, martis-git commented on README.md
> +1. **Возможное решение**. Несколько подробных предложений с практическими примерами как предлагается решить проблему из первого пункта. Чем больше подробной информации о том "почему именно так", тем
Вот кста как вариант - можно этот чеклист еще в темплейты засунуть + твои критерии перечисленные

![image](https://user-images.githubusercontent.com/42924400/114297986-a8b69800-9abc-11eb-97ac-705298ecc1de.png)

2021-04-11 18:14 UTC, binjospookie commented on README.md
> +## Как мы принимаем решения
Можно добавить элемент "у меня есть предложение/проблема"

2021-04-12 17:08 UTC, martis-git commented
@sergeysova добей пож

2022-01-14 19:33 UTC, closed without merging

2022-01-24 16:20 UTC, sergeysova commented
¯\_(ツ)_/¯

2022-01-24 16:28 UTC, azinit commented
@sergeysova До лучших времен оставляем(
Я пинговал чтоб добить эти гайдлайны 🤷‍♂️