Update documentation structure & Add glossary with page about `Shared`
feature-sliced/documentation pull request #98
Opened 2021-04-19 12:23 UTC by karina-drummer

## Changelog

1. New documentation structure
2. Added Glossary section
3. Added spell checking dictionary and setup document for VSCode

## Checklist

- [ ] Discussions were taken into account
- [ ] Checked for compliance with the requirements of the issue(s)
- [ ] Self-review is done

2021-04-19 12:34 UTC, martis-git commented on .vscode/readme.md
> +[Marketplace link](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
Спасибо за инфу 😄

2021-04-19 12:34 UTC, martis-git commented
Ох чую, холиварище будет по PR этому)

Все все намешала))

Но тогда да - Саша поревьювит, и еще кто-нить

2021-04-19 12:35 UTC, karina-drummer commented
Пока ещё в процессе, думаю пару моментов допилить ( форматирование в shared ещё не улучшила )

2021-04-19 12:36 UTC, karina-drummer commented
> Все все намешала))

Неудобно и непонятно как это всё отдельно пушить

2021-04-19 13:38 UTC, martis-git commented
> > Все все намешала))
> 
> Неудобно и непонятно как это всё отдельно пушить

Ну просто я за мелкие, но самодостаточные PR-ы)

А щас тут куча правок полетит по всем фронтам - и придется это расхлебывать все

> Но сама смотри, кнчн

2021-04-19 17:49 UTC, AlexandrHoroshih requested changes

2021-04-19 17:49 UTC, AlexandrHoroshih commented on src/glossary/layers/shared/ru.md
> +**Набор разделяемых библиотек** чистых низкоуровневых элементов, таких как **методы доступа к внешним API**, **вспомогательные функции**, и **переиспользуемые компоненты UI**.
_**Набор разделяемых библиотек** чистых низкоуровневых элементов_

Мне кажется, на русском это звучит сильно менее органично, чем на английском - я прямо "споткнулся" на этой фразе, когда читал

Как насчет такого варианта?
```suggestion
**Набор общедоступных библиотек** и низкоуровневых абстракций, таких как **методы доступа к внешним API**, **вспомогательные функции**, и **переиспользуемые компоненты UI**.
```

2021-04-19 17:49 UTC, AlexandrHoroshih commented on src/glossary/entry/ru.md
> +Каждая из секций, находящихся на самом верхнем уровне приложения.
Думаю, cюда чуть более подробное определение нужно или ссылку на него - кажется, в этом PR есть: https://github.com/feature-sliced/wiki/pull/86

2021-04-19 18:24 UTC, karina-drummer commented on src/glossary/entry/ru.md
> +Каждая из секций, находящихся на самом верхнем уровне приложения.
Да, это пока что черновик, я поэтому ревью пока не запрашивала ( но видимо оно запросилось само )

2021-04-19 18:39 UTC, karina-drummer commented on src/glossary/layers/shared/ru.md
> +**Набор разделяемых библиотек** чистых низкоуровневых элементов, таких как **методы доступа к внешним API**, **вспомогательные функции**, и **переиспользуемые компоненты UI**.
Понятие "разделяемая библиотека" – общепринятое. А вот "общедоступная библиотека" не используется и выглядит скорее как машинный перевод.

Предлог "и" не поставила, потому что здесь говорится именно о *библиотеках абстракций*

В любом случае, нужно указать что библиотеки должны быть чистыми, хотелось это подчеркнуть в самом начале. Перенести в другое предложение?

2021-04-19 18:44 UTC, karina-drummer commented
@AlexandrHoroshih скорее всего, придётся подискутировать про файловую структуру, что можешь сказать на счёт неё?

2021-04-21 19:57 UTC, martis-git requested changes
Имхо - оч много намешано в PR, что может опять привести к тому - что придется за "один присест" чекать кучу всего

> И тебе тоже придется вести дискуссии по нескольким темам в одном реквесте, и правки вносить тоже по нескольким аспектам

---

Ну если совсем не сгущать краски - то базис для MVP хороший, просто много нагромождений

И само собой - есть что улучшить

> Хотя это и драфтовая версия, но предложений накидал

---

**UPD**: Особенно учитывая, как мерджить эти оч ожидаемые изменения вместе с breaking-changes по структуре

> Мы же "по-хорошему" такие вещи обычно, как и массовое форматирование проекта, делаем отдельными пулл-реквестами, не так ли? )

2021-04-21 19:57 UTC, martis-git commented on .vscode/extensions.json
> +}
Я вот понимаю про spell-checker, чтобы каждый себе ставил хотя бы для wiki

Но всякие todo-tree, кучи экстеншенов для md... Не оверхед?

2021-04-21 19:57 UTC, martis-git commented on intro/.gitkeep
> -Get-started, Overview
Вот ты перенесла все в src... А ты проверяла, как работают ссылки в README ?

> Похоже что нет

![image](https://user-images.githubusercontent.com/42924400/115610557-b1e00a00-a2f1-11eb-9c34-ed3f85e9a55a.png)

2021-04-21 19:57 UTC, martis-git commented on src/glossary/entry/ru.md
> +Каждая из секций, находящихся на самом верхнем уровне приложения.
Плюс я бы указал, какие конкретно здесь абстракции

```suggestion
Каждая из секций, находящихся на самом верхнем уровне приложения.

> `app`, `*processes`, `pages`, `features`, `entities`, `shared`
```

2021-04-21 19:57 UTC, martis-git commented on src/glossary/entry/ru.md
> +Каждый из элементов, находящихся на верхнем уровне слоёв `processes`, `features`, `entities`.
**ИМХО, не самая удачная формулировка**

```suggestion
Каждый из слоев на верхнем уровне можно поделить на части - на **слайсы**

Слайсы представляют собой - часть бизнес-логики для конкретного слоя

> - Чаще всего слайсы можно выделить для `processes`, `pages`, `features`, `entities`
> - Для shared - чаще всего весь слой представляет собой единый слайс *инфраструктурной* логики, оторванной от доменной
> - Содержимое `app` - отличается от проекта к проекту, и четкие слайсы выделять сложно и нецелесообразно


```

2021-04-21 19:57 UTC, martis-git commented on src/glossary/entry/ru.md
> +Каждая из секций, находящихся на самом верхнем уровне приложения.
Плюсую, тоже бы добавил линки на существующие доки

2021-04-21 19:57 UTC, martis-git commented on src/glossary/entry/ru.md
> +
Плюс не хватает секции про `Segment`

2021-04-21 19:57 UTC, martis-git commented on src/glossary/layers/shared/en.md
> +In addition, the application also depends indirectly on their internal implementation, because it relies on strictly defined expected behavior of this modules.
Повторюсь,

**Крайне против пилить английскую версию параллельно с русской, ибо:**
- ревьюверу приходится делать двойную работу (смотреть и англ и русскую версию)
- разработчику приходится тратить двойное время на en и ru версию (и если задачи делать обе доки не стоит - разраб обязательно ошибется / недоучтет некоторые моменты при ревью)
    > И при прототипировании, и при внесении правок

2021-04-21 19:57 UTC, martis-git commented on src/intro/.placeholder
> +Get-started, Overview
**Крайне против такой структуры**

Не вижу смысла настолько упарываться пока, считаю, что можно пока удалить все что связано с `glossary` слайсами/сегментами/слоями

Для MVP - этого точно пока не нужно

> Если считаешь иначе, оке - да будет срач, обсудим =)

![image](https://user-images.githubusercontent.com/42924400/115612823-5b27ff80-a2f4-11eb-9ad6-e90e68b25e6f.png)

2021-04-21 19:57 UTC, martis-git commented on src/intro/.placeholder
> +Get-started, Overview
> Плюс с какого фига у нас фичи/энтити/процессы - стали слайсами? :)

2021-04-21 19:57 UTC, martis-git commented on src/glossary/layers/shared/ru.md
> +**Набор разделяемых библиотек** чистых низкоуровневых элементов, таких как **методы доступа к внешним API**, **вспомогательные функции**, и **переиспользуемые компоненты UI**.
Плюсую, я бы скорее сказал **"переиспользуемых"**

> Потому и `shared`, потому и кладется туда только то, что переиспользуется

2021-04-21 20:18 UTC, martis-git commented on src/glossary/entry/ru.md
> +
А кста - тож интересно, почему "glossary/**entry**"?)

> 1. Поч не что-то из имеющихся директорий (about / concepts / ...)
> 2. Зач еще одна прослойка "entry"? Поч не обычный README.md, который по идее как раз описывает на верхнем уровне все основное?

2021-04-21 20:23 UTC, martis-git commented on .vscode/extensions.json
> +}
Если они не идут как обязательные, а будут всплывать как "рекоммендации" - то претензий ноль

> Прост до этого не приходилось так экстеншены указывать, обычно хватало указывания в каком-нить md файле

2021-04-21 20:54 UTC, martis-git commented on intro/.gitkeep
> -Get-started, Overview
Плюс оке - если ты выносишь в `/src` - в этом есть смысл, офк

Я бы сделал отдельный файл `/src/readme.md`, где бы описал структуру **имеющихся** статей по доке, чтобы можно было посмотреть, какие статьи готовы сейчас для ознакомления

> Ведь пока структура у нас не устаканившаяся, и на стенде - тож структура статей тож нигде не отображается

![image](https://user-images.githubusercontent.com/42924400/115619593-b958e080-a2fc-11eb-9939-78de1db06855.png)

2021-04-21 21:08 UTC, martis-git commented on intro/.gitkeep
> -Get-started, Overview
Вот тип такого (как временное решение пока)

![image](https://user-images.githubusercontent.com/42924400/115621226-e3130700-a2fe-11eb-9b71-ae531dad11ab.png)

2021-04-22 01:56 UTC, karina-drummer commented on .vscode/extensions.json
> +}
Да, это workspace recommendations. А вот в setup доке я потом просто оставлю инструкцию как открыть этот рекомендованный список в самом VSCode, остальное уберу

2021-04-22 01:58 UTC, karina-drummer commented on .vscode/extensions.json
> +}
> Я вот понимаю про spell-checker, чтобы каждый себе ставил хотя бы для wiki
> 
> 
> 
> Но всякие todo-tree, кучи экстеншенов для md... Не оверхед?

У нас миллион тудушек, а md тоже нужно писать валидно. Пока у нас с этим всё ужасно.

2021-04-22 02:00 UTC, karina-drummer commented on intro/.gitkeep
> -Get-started, Overview
> Вот ты перенесла все в src... А ты проверяла, как работают ссылки в README ?
> 
> 
> 
> > Похоже что нет
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/42924400/115610557-b1e00a00-a2f1-11eb-9c34-ed3f85e9a55a.png)
> 
> 

Ещё не успела. Но я и ревью не запрашивала, хотела запросить уже когда всё добью. Почему оно само запросилось я не знаю, открытие PR это ещё не сигнал готовности.

2021-04-22 02:01 UTC, karina-drummer commented on intro/.gitkeep
> -Get-started, Overview
> Плюс оке - если ты выносишь в `/src` - в этом есть смысл, офк
> 
> 
> 
> Я бы сделал отдельный файл `/src/readme.md`, где бы описал структуру **имеющихся** статей по доке, чтобы можно было посмотреть, какие статьи готовы сейчас для ознакомления
> 
> 
> 
> > Ведь пока структура у нас не устаканившаяся, и на стенде - тож структура статей тож нигде не отображается
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/42924400/115619593-b958e080-a2fc-11eb-9939-78de1db06855.png)
> 
> 

Учту

2021-04-22 02:05 UTC, karina-drummer commented on src/glossary/layers/shared/en.md
> +In addition, the application also depends indirectly on their internal implementation, because it relies on strictly defined expected behavior of this modules.
Это запрет?

2021-04-22 02:09 UTC, karina-drummer commented on src/intro/.placeholder
> +Get-started, Overview
> > Плюс с какого фига у нас фичи/энтити/процессы - стали слайсами? :)

Присмотрись, это единственное число.
Каждая фича – слайс.

Feature extends Slice
slices/feature

2021-04-22 02:15 UTC, karina-drummer commented on src/intro/.placeholder
> +Get-started, Overview
> **Крайне против такой структуры**
> 
> 
> 
> Не вижу смысла настолько упарываться пока, считаю, что можно пока удалить все что связано с `glossary` слайсами/сегментами/слоями
> 
> 
> 
> Для MVP - этого точно пока не нужно
> 
> 
> 
> > Если считаешь иначе, оке - да будет срач, обсудим =)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/42924400/115612823-5b27ff80-a2f4-11eb-9ad6-e90e68b25e6f.png)
> 
> 

MVP === свалить всё в кучу?

Куда положить страницу про фичу, например, в `/src/abstractions` вместе со всем остальным?

К тому же, у нас в любом случае будет чёткая иерархия, как ты абстракции не назови

2021-04-22 02:22 UTC, karina-drummer commented on src/glossary/layers/shared/ru.md
> +**Набор разделяемых библиотек** чистых низкоуровневых элементов, таких как **методы доступа к внешним API**, **вспомогательные функции**, и **переиспользуемые компоненты UI**.
> Плюсую, я бы скорее сказал **"переиспользуемых"**
> 
> 
> 
> > Потому и `shared`, потому и кладется туда только то, что переиспользуется

Переиспользуется не библиотека, а её юниты. Библиотека переиспользуемых компонентов является разделяемой

2021-04-22 05:31 UTC, martis-git commented on .vscode/extensions.json
> +}
> У нас миллион тудушек, а md тоже нужно писать валидно. Пока у нас с этим всё ужасно.

Я туду-три тож юзаю, но зачем он для доки - не особо понимаю)

С тем же успехом - можно обычный поиск юзать, вряд ли кто сам будет смотреть "Хм, а какие тудушки по документации?"

> а md тоже нужно писать валидно. Пока у нас с этим всё ужасно.

Опять же - не понимаю, где проблемы с валидным md (сегодня развернешь надеюсь)

2021-04-22 05:33 UTC, martis-git commented on src/glossary/layers/shared/en.md
> +In addition, the application also depends indirectly on their internal implementation, because it relies on strictly defined expected behavior of this modules.
Это повод на подумать)

Если оч горит тебе эта тема - то можем и на созвон вынести))

> Есть просто ощущение, что это сильно стопорить при разработке

2021-04-22 05:35 UTC, martis-git commented on src/intro/.placeholder
> +Get-started, Overview
> Feature extends Slice
> slices/feature

Нет же...

```ts
App | Processes | Pages | ... | Shared extends Layer

ProlfePage | InlinePostFeature | ... extends Slice

UI | Model | Lib | Api | ... extends Segment
```

2021-04-22 05:39 UTC, martis-git commented on src/intro/.placeholder
> +Get-started, Overview
> MVP === свалить всё в кучу?
>
> Куда положить страницу про фичу, например, в /src/abstractions вместе со всем остальным?
>
> К тому же, у нас в любом случае будет чёткая иерархия, как ты абстракции не назови

Лан, в любом случае это еще некритичный момент, просто будет обидно, когда придется переделывать структуру

*Старания насмарку могут пойти*

2021-04-22 06:20 UTC, martis-git commented on src/glossary/layers/shared/ru.md
> +**Набор разделяемых библиотек** чистых низкоуровневых элементов, таких как **методы доступа к внешним API**, **вспомогательные функции**, и **переиспользуемые компоненты UI**.
> Переиспользуется не библиотека, а её юниты. Библиотека переиспользуемых компонентов является разделяемой

Не пон аргумент))

2022-01-14 19:31 UTC, closed without merging